### ISSUE TITLE
`plugin.json` in each repo

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/library#316]
This will be a Rack 1.0+ thing, so don't worry about until then.

There should be no manifest data in C++ files except the Plugin slug and Model slugs. Instead a `plugin.json` file should be created alongside the `plugin.{dll,so,dylib}` files with all the information that is currently in the C++ *and* this repo's manifest.

We'll have ~6 months to standardize this after Rack 0.6 is released. The standard will of course be derived with whatever this repo evolves into.

**Comment by cschol** [comment]
As of Rack 1.0+, each plugin has their own `plugin.json`. Closing.
