### ISSUE TITLE
Plugin dependency management

### ISSUE THREAD

**Issue by cschol** [VCVRack/library#335]
@AndrewBelt 

We have a few examples of plugins that require 3rd party libraries to build, e.g. [Stellare Moduar VCV-Link](https://github.com/stellare-modular/vcv-link) (requires `asio.hpp` from, e.g. `libasio-dev`) or IO-Simple still requires `libsamplerate`.

What should the guidance for plugin developers be when it comes to these dependencies? I am thinking specifically of the case where the plugin gets added to the `community` repository and someone else (you, the community) builds it.

A lot of open-source projects just say "install library x or y with your package manager, then make".

What is acceptable for the plugin to require from the build environment?

Example of an acceptable build workflow applicable for all plugins:
- `git clone plugin-repo`
- `git submodule update --init --recursive`
- `make dep`
- `make dist`

Does this roughly match what you had in mind?

Is it acceptable for `make dep` to **install** a 3rd party **binary** library during the build process via package manager **or** do the plugins have to provide source versions (e.g. as submodule) built in the `make dep` step like Rack itself does?
Are some of these considerations actually **requirements** for acceptance into the `community` repository? If yes, what would be the best way to communicate these to the plugin developers?

This question has come up for me while testing plugins for migration into `community`. Some have their *special* requirements, be it custom Makefiles (ParableInstruments, Southpole-Parasites) or build failures due to special library requirements (Stellare-Modular-Link).

**Comment by AndrewBelt** [comment]
If the plugin developer can find a git repo, use git submodules. If not, and the license allows it, simply include the files in the plugin's repo.

There is virtually nothing a makefile can't do. Plugin developers should add pre-build scripts if needed. I'm sure there's a better way, but you could do

```makefile
build:
    <shell commands>
    $(MAKE)
```

>acceptable for make dep to install

No, definitely not. That would be grounds for deletion, since I consider it malware.

**Comment by cschol** [comment]
Right, I use Makefiles a lot and rarely are they inferior to a shell script. 

Now, I would think that for consistency in **execution** of the build, you would want the, let's call it **build interface** to be consistent. 

Meaning that a plugin developer should use either `make dep` or include any preparatory steps in the main target itself executed when just calling `make` and **not** have a magic `build-my-stuff.sh` in a folder in the repo somewhere (unless it is executed from the Makefile). 

The expectation is that the plugin builds with a simple `make`. Do you agree?

**Comment by AndrewBelt** [comment]
Closing since `make cleandep` and `make dep` is what my build scripts do now. If it doesn't work, I build manually.
