### ISSUE TITLE
ImpromptuModular

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/library#356]
I don't know if I should be posting this here, but I would like to **supply** my manifest file for the v2 community repo, and also request an **update** of the repo link to my latest master. Thanks!
ImpromptuModular.json:

```
{
  "name": "ImpromptuModular",
  "author": "Marc Boulé",
  "license": "BSD 3-clause",
  "contactEmail": "marc.boule@etsmtl.ca",
  "websiteUrl": "https://github.com/MarcBoule/ImpromptuModular",
  "manualUrl": "https://github.com/MarcBoule/ImpromptuModular",
  "sourceUrl": "https://github.com/MarcBoule/ImpromptuModular",
  "latestVersion": "0.6.0",
  "status": ""
}
```

**Comment by MarcBoule** [comment]
Thanks Andrew. For the readme url, I was indeed thinking of supplying this link instead:
```https://github.com/MarcBoule/ImpromptuModular/blob/master/README.md```
but I wasn't sure it was the recommended way. Good to know!

P.S. If ever no one volunteers for the Library Team, I could perhaps pitch in, I would just need to learn about the "_knowledge of submitting PRs_" part, in particular relating to the mechanism in play in the ``repos`` folder; it is still unclear to me (I am a github rookie, so still much to learn!) :-)

**Comment by MarcBoule** [comment]
I have added a new module to my plugin and would like to request an update. The version should be bumped up to 0.6.1, and the source corresponds to my current master at
https://github.com/MarcBoule/ImpromptuModular
Thanks!

**Comment by mdemanett** [comment]
@MarcBoule  - you should update your Makefile to bump VERSION to 0.6.1.  Your module went out to the package manager already as 0.6.0 -- so the review/build process needs a version bump to work, and the new version needs to match VERSION in the Makefile.

@AndrewBelt I reviewed the code and it's good...but will hold off on a PR pending the Makefile update.  Set me straight if I've got this wrong.  If I'm not wrong, looks like a few other modules requesting updates will need to do the same thing (bump their version to 0.6.1) -- Valley and Amalgamated are examples.

**Comment by AndrewBelt** [comment]
@mdemanett Looks like you're all correct. Yes, everyone needs to update their version or the plugin manager will not trigger an update.

**Comment by MarcBoule** [comment]
My bad, I totally forgot about that one. thanks to both of you for the follow up, it is now fixed. :+1:

**Comment by MarcBoule** [comment]
By the way, it's good that our Plugin's issue remain permanently open, it helps to remember these things so they don't happen again. And to answer a question from @AndrewBelt in another issue, if the author accidentally deletes his or her Plugin issue, they can indeed re-open it.

**Comment by AndrewBelt** [comment]
Updated build, close until you have a new update.

**Comment by MarcBoule** [comment]
Sounds good!

**Comment by MarcBoule** [comment]
I have added a new sequencer to my plugin and would like to request an update. The new version is 0.6.2, and the source corresponds to my current master at
https://github.com/MarcBoule/ImpromptuModular
My makefile was also updated to 0.6.2. Thanks!

**Comment by MarcBoule** [comment]
Thanks!

**Comment by MarcBoule** [comment]
Major redesign of Phrase-Seq-16, and would like to request an update please. 
The new version is 0.6.3, and the source corresponds to my current master at
https://github.com/MarcBoule/ImpromptuModular
My makefile was also updated to 0.6.3. Thanks!

**Comment by phdsg** [comment]
Updated build.

**Comment by MarcBoule** [comment]
Thanks!

**Comment by MarcBoule** [comment]
Hi, could the following dontation link be added in `ImpromptuModular.json` please:
```"donateUrl": "https://www.paypal.me/marcboule",```
Thank you!

**Comment by MarcBoule** [comment]
Thanks!

**Comment by MarcBoule** [comment]
I would like to request an update of my plugin please, two new sequences were added.
The new version is 0.6.4, and the source corresponds to my current master at
https://github.com/MarcBoule/ImpromptuModular
My makefile was also updated to 0.6.4. Thanks!

**Comment by AndrewBelt** [comment]
Updated builds

**Comment by MarcBoule** [comment]
Update request please for my new version 0.6.5 (added a new semi-modular synthesizer based on Fundamental and PhraseSeq16) and added optional expansion panels on the PhraseSeq sequencers). Thanks!

**Comment by AndrewBelt** [comment]
Updated build

**Comment by MarcBoule** [comment]
Update request please, a few ugly intermittent bugs were fixed, now at 0.6.6.
[Current master](https://github.com/MarcBoule/ImpromptuModular) can be grabbed. Thanks!

**Comment by AndrewBelt** [comment]
Updated build

**Comment by MarcBoule** [comment]
I'd like to request an update please, two new modules were added (Clocked and Tact), now at 0.6.7.
[Current master](https://github.com/MarcBoule/ImpromptuModular) can be grabbed. 

I know we're supposed to give a commit hash, but I never plan any changes until the review team does its job, and this gives me a small window to catch any last minor issues if ever. 

Thanks again!

**Comment by mdemanett** [comment]
Hey Marc - a branch is just fine.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by MarcBoule** [comment]
I'd like to request an update please, now at 0.6.8. [BigButton](https://www.lookmumnocomputer.com/projects/#/big-button/) is now in VCV Rack, and Clocked was updated to use the new BPM CV standard. As usual, current master can be grabbed. Thanks!

**Comment by AndrewBelt** [comment]
I need to build a new Rack SDK before building this.

**Comment by MarcBoule** [comment]
Ok. Is it something that you plan on doing in the next week or two, or you would recommend I revert some changes to bring it back to current SDK compatibility?

**Comment by AndrewBelt** [comment]
Probably tomorrow

**Comment by AndrewBelt** [comment]
Decided that "pulse" is the proper term for gates that last 1ms or so. A "trigger" isn't really a thing but an *event*, which is what `SchmittTrigger` detects. (It doesn't detect pulses, those are on-going things.)

**Comment by MarcBoule** [comment]
All good, and done. I've always thought that good terminology is like a nice form of intrinsic documentation. My repo is ready, and I kept the version at 0.6.8. Thanks 👍

**Comment by MarcBoule** [comment]
Hi Matt and Andrew, I just saw that Impromptu didn't make it in the last build a couple of hours ago, if there's anything specific I need to do, please let me know. Thanks.

**Comment by mdemanett** [comment]
Looks good to go.

**Comment by AndrewBelt** [comment]
I have to update my own Rack SDK before building this one.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by MarcBoule** [comment]
Update request please: Impromptu now at 0.6.9. Clocked can now be sync'ed to external clock sources, Tact looses its expansion panel, and in PS16/32 and SMS16 the right click does same as left click but steps the sequencers. New run modes also added to phrased sequencers. Current master ready at the [usual place](https://github.com/MarcBoule/ImpromptuModular). Thanks!

**Comment by MarcBoule** [comment]
Update request please: Impromptu now at 0.6.9. Clocked can now be sync'ed to external clock sources, Tact looses its expansion panel, and in PS16/32 and SMS16 the right click does same as left click but steps the sequencers. New run modes also added to phrased sequencers. Current master ready at the [usual place](https://github.com/MarcBoule/ImpromptuModular). Thanks!
P.S. Re-entered this comment since my comp's clock was messed up.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by MarcBoule** [comment]
I'd like to request an update please, now at 0.6.10. Advanced gate mode was added to Phrase and Gate sequencers. As usual, current master can be grabbed. Thanks!

**Comment by AndrewBelt** [comment]
Updated build

**Comment by MarcBoule** [comment]
I'd like to request an update please, now at 0.6.11. Two new modules were added (BigButtonsSeq2 and Tact1), along with many other small functionality and performance improvements. Current master is ready. Thanks!

**Comment by AndrewBelt** [comment]
Updated build

**Comment by MarcBoule** [comment]
I'd like to request an update please, now at 0.6.12.  The main changes are: improvements to the advanced gate modes in the phrase and gate sequencers, and performance improvements all around. Current master is ready. Thanks!

**Comment by cschol** [comment]
@AndrewBelt Does the build system use the SDK or a source tree to build the plugin manager plugins? @MarcBoule is using `BooleanTrigger`, which is not currently in the latest SDK version 0.6.2 and the plugin does not build against the SDK. Builds fine with the source tree.

**Comment by MarcBoule** [comment]
@cschol that's weird, since BooleanTrigger was there in my last update from 2 weeks ago and I believe the build went ok, but if it's preferable that I remove it, just let me know. Thanks!

**Comment by cschol** [comment]
No, it should be fine. Just want to make sure that we are not running into issues when I push all the recent plugin updates. Thank you for your patience.

**Comment by AndrewBelt** [comment]
@cschol I use the source tree as the SDK now.

**Comment by cschol** [comment]
@AndrewBelt Cool, updates incoming.

**Comment by MarcBoule** [comment]
Thanks for the update/build guys!

**Comment by AndrewBelt** [comment]
Yes, built update yesterday, failed to mention.

**Comment by MarcBoule** [comment]
I'd like to request an update please, now at 0.6.13. New sequencer Foundry is introduced. Current master is ready. Thanks!

**Comment by AndrewBelt** [comment]
Build updated.

**Comment by MarcBoule** [comment]
I’d like to request an update of Impromptu Modular please, now at 0.6.14. Current master can be grabbed. Detailed changelog below for future reference. Thanks!

Main changes:
- Clocked now keeps its outputs high when resetting a stopped clock, such that when starting again, it will not miss the first step in sequential switches or sequencers that don’t have run inputs 
- Clocked and all sequencers are now running by default when instantiated in a patch. This should have been done a long time ago, and if DeadMau5 ever touches one of my sequencers again, he will not make the same mistake! ;-)
- GateSeq64: we can now right-click steps to turn them off (instead of two left-clicks needed when the cursor is not on the step we want to clear.
- PhraseSeqs and Foundry: rotate offsets are now persistent and stored in the sequencer. Also, ctrl-right-clicking of notes can now be used to automatically copy the note or gate-type over to the next step (not just moving to the next step as is done by normal right-clicking)
- Foundry: added bipolar option for CV2 outputs, available in the right-click menu (outputs will be -5V to 5V when active, instead of 0V to 10V by default). Reworked how CV IN and CV2 IN input writing behaves: writing is now only performed for the active track (unless ALL is selected, then all tracks are written). Unconnected tracks are never written into the sequencer. When the expansion panel is active, an button now allows selecting only CV IN, or CV2 IN, or both, for writing.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by MarcBoule** [comment]
I’d like to request an update of Impromptu Modular please, now at 0.6.16. Current master can be grabbed.  Thanks!

Minor fixes and improvements to Foundry, the slide was broken in 0.6.14 and is now back to working state, P2 and P16 ppqn settings were added to Clocked.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by MarcBoule** [comment]
I’d like to request an update of Impromptu Modular please, now at 0.6.16. Current master can be grabbed. Thanks!

Changes:
* CLOCKED: fix P2 mode with was erroneously loaded as P4 when patches reopened.
* WRITE-SEQs: add 2nd gate mode (held gates) with right click to turn off.
* GATE-SEQ64: add step indication in song mode (white lights), and add right-click initialization on main knob.
* PHRASE-SEQs, SMS16, FOUNDRY: add gate status feedback in step lights.
* FOUNDRY: fix write bug when writing all tracks via CV IN.
* Randomize in the right click menu now only randomizes the active sequence (notes, gates, etc), as opposed to the entire state of the sequencer (which was pretty useless). For sequencers with a SEQ/SONG switch, nothing is randomized in song mode.

**Comment by AndrewBelt** [comment]
Build updated

**Comment by MarcBoule** [comment]
I’d like to request an update of Impromptu Modular please, now at 0.6.17. Current master can be grabbed. Unless a major bug comes up, this is likely the last update until Rack 1.0. Thanks!

Changes:
FOUNDRY: make the SEQ/SONG main switch behave like in the PhraseSeq series, and implement 4 separate SEQ# CV inputs in the expansion panel; Add sync switch for SEQ# CV inputs, such that when activated, the sequence change happens only when reaching the end of the sequence (as opposed to real-time). Remove liquid metal panel theme

**Comment by AndrewBelt** [comment]
Updated build.

**Comment by MarcBoule** [comment]
MyPlugin v1.0.0 is available for adding to the v1 library. Please use the HEAD of my v1 branch. Thanks!

(https://github.com/MarcBoule/ImpromptuModular/tree/v1)

**Comment by MarcBoule** [comment]
Just noticed that the automation automatically added my v1 plugin to the v0.6 queue, not sure if that is what is supposed to happen, since it could break my v0.6 distribution in the plugin manager.

**Comment by cschol** [comment]
Slug update required: https://github.com/MarcBoule/ImpromptuModular/issues/42

**Comment by MarcBoule** [comment]
Fixed, thanks!

**Comment by MarcBoule** [comment]
I’d like to request an update of Impromptu Modular please, now at v1.0.1. The HEAD of my v1 branch can be grabbed. Thanks!
(Now using changelog.md to list changes)

**Comment by MarcBoule** [comment]
I’d like to request an update of Impromptu Modular please, now at v1.1.0. The HEAD of my v1 branch can be grabbed. Thank you!

**Comment by MarcBoule** [comment]
I’d like to request an update of Impromptu Modular please, now at v1.1.1. The HEAD of my v1 branch can be grabbed. Main changes are in CHANGELOG.md. Thank you!

**Comment by MarcBoule** [comment]
I’d like to request an update of Impromptu Modular please, now at v1.1.2. 
I have restarted my repo completely, and am now in the master branch, so I'm pretty sure a **re-clone will be needed** on your end. The head commit can be grabbed in the master branch at:
https://github.com/MarcBoule/ImpromptuModular
I also changed the license to GPLv3. More changes are in the changelog. Thanks!

**Comment by MarcBoule** [comment]
I’d like to request an update of Impromptu Modular please, now at v1.1.3.
The head commit in the master branch can be grabbed. Thanks!

Changes:
- Added a new module called CV-Pad
- Fixed random in tied steps in PhraseSeq16/32, SemiModularSynth and Foundry, i.e. if head step has a probability, make successive tied steps follow this probability also such that it is one big tied step with one single probability
- Reduced range of randomization of notes in all sequencers when module is randomized
- Added an option in Clocked to make the Run CV input level-sensitive, default is trigger-sensitive as before

**Comment by MarcBoule** [comment]
I’d like to request an update of Impromptu Modular please, now at v1.1.4.
The head of the master branch can be grabbed. Thanks!

Changes:
- Allow 4View to function as an expander for ChordKey and CVPad
- Add new module called ChordKey: a keyboard-based chord generator 
- Implement Portable sequence copy/paste in Foundry, PhraseSeq16/32 and SemiModularSynth
- Add new module called Clkd: a half-sized version of Clocked without PW, Swing nor Delay
- Reduced width of CVPad by 2 HP
- Fix bug in Foundry when using expander to sync select sequences with different run modes
- Fix bug in divided clocks in Clocked when launching Rack

**Comment by MarcBoule** [comment]
I’d like to request an update of Impromptu Modular please, now at v1.1.5.
The head of the master branch can be grabbed. Thanks!

Here are a few of the main changes (the changelog has more details):
* Removed the word "Modular" from the plugin's **brand** and **name**. Just to be absolutely sure, I have not changed the module **slug** so I think this will not break anything, but if I'm wrong, please let me know :-) 
* Added a new module called Part (concept suggested by Andrew) 
* Added a chord mode to FourView
* Added quantizer expander for ChordKey

**Comment by MarcBoule** [comment]
I’d like to request an update of Impromptu Modular please, now at v1.1.6.
The head of the master branch can be grabbed. Thanks!

Fixed a few bugs, added a trigger output option to CLKD, and added a CV through output to PART. 

@AndrewBelt Here are some details regardint the _CV through ouput_ that I added to Part if ever you're curious to know why I chose to do this.
It turns out there is a weird little corner case issue that can happen when we chain two Part modules in order to filter for a range.

To illustratre, consider a CV+Gate pair coming from MIDI_CV. When pressing and holding a note below the range, then simultaneously pressing a note above the range, it's possible for a small 1-sample gate to be emmitted by the last Part module, even though no CV was ever produced within the selection range. This happens because the second Part is getting the exact same CV signal as the first Part, however it's gate is getting a supplemental one-sample delay since it's coming from the first Part. So during one sample, the second Part is taking a wrong decision and can thus produce a 1-sample gate glitch (triggering many sequencers for example, when it should not). 

So to fix this, I added the CV through output, which should be used by the second Part for it's CV, such that it's always acting on a CV/Gate pair that is perfectly in sync.

Here's an example where we want to select notes in the range [D4 to F4]. If we press C4 (Z key) and hold it continually, then press A4 (N key), a 1-sample gate is sent out of the last Part when releasing the A4 (the C4 is still held), although no note from D4 to F4 was ever pressed.

![image](https://user-images.githubusercontent.com/33604154/80988572-abffc900-8e01-11ea-9bef-554c8676c467.png)

Here's another version but without the glitch (with use of the CV through):

![image](https://user-images.githubusercontent.com/33604154/80988829-0bf66f80-8e02-11ea-8f2f-f193c55afc2c.png)

Interesting timing sublety :-)

**Comment by MarcBoule** [comment]
I’d like to request an update of Impromptu Modular please, now at v1.1.7.
The head of the master branch can be grabbed. Thanks!

Changelog: 
- Converted all SVGs from px to mm
- Alphabetized modules in module browser and manual
- Added option in WriteSeq32/64 to make arrow controls rotate instead of step (step is default)
- Added auto-return options to Tact and Tact1
- Added tracer option to TwelveKey
- Added auto-patching Clocked and Clkd to a designated clock master

**Comment by MarcBoule** [comment]
I’d like to request an update of Impromptu Modular please, now at v1.1.8.
The head of the master branch can be grabbed. Thanks!

Changelog:
- Made LED displays show when using the Lights Out module (Modular Fungi plugin)
- Add "CV input viewer" option to TwelveKey

**Comment by MarcBoule** [comment]
I’d like to request an update of Impromptu Modular please, now at v1.1.9.
The head of the master branch can be grabbed. Thanks!

Changelog:

* Added a new Tact module with a gate output and two offsets controls
* Reduced width of blank panel

**Comment by MarcBoule** [comment]
I’d like to request an update of Impromptu Modular please, now at v1.1.10.
The head of the master branch can be grabbed. Thanks!

Changelog:
* Fixed parameter entry in Clkd and Clocked ratio knobs, and improved tooltip on main BPM knob when external BPM
* Added lock option to GateSeq64 to prevent steps, gate types and gate p from being clicked
* Added x96 clock ratio to Clocked and Clkd
* Added light version of Blank panel and touched up dark theme

**Comment by MarcBoule** [comment]
I’d like to request an update of Impromptu Modular please, now at v1.1.11. I added a new module called ProbKey. The head of the master branch can be grabbed. Thanks!

![ProbKey](https://user-images.githubusercontent.com/33604154/123524710-23458b80-d69a-11eb-8a68-d4aced962885.jpg)

**Comment by MarcBoule** [comment]
I’d like to request an update of Impromptu Modular please, now at v1.1.12. I made some improvements to Prok-Key and fixed a bug in Phrase sequencers. Full details are in the changelog as usual, and the head of the master branch can be grabbed. Thanks!

**Comment by MarcBoule** [comment]
Ready for v2! I merged my v2 branch back to my master branch and deleted v2, since from now on my master is implicitly v2. So please take the head of master. Impromptu is now v2.0.6. Thanks!

**Comment by cschol** [comment]
Invalid `plugin.json`: https://github.com/MarcBoule/ImpromptuModular/issues/44

**Comment by MarcBoule** [comment]
This should be fixed now, sorry for the glitch

**Comment by MarcBoule** [comment]
I'd like to request an update of Impromptu please, now at v2.0.7.
The head of the master branch can be grabbed.
Changes: updated menus so that they work properly when cmd/ctrl-clicked, and a few other minor changes.
Thanks!

**Comment by MarcBoule** [comment]
I'd like to request an update of Impromptu please, now at v2.1.0.
The head of the master branch can be grabbed. Added two new utility modules and changed how notes are displayed in most modules that display notes.
Thanks!

**Comment by MarcBoule** [comment]
I'd like to request an update of Impromptu please, now at v2.1.1.
The head of the master branch can be grabbed.
Added external clock signal auto detection on BPM input of Clocked, hope this helps the new users!
Thanks!

**Comment by MarcBoule** [comment]
I'd like to request an update of Impromptu please, now at v2.1.2. Head of master can be pulled. Thanks!

**Comment by MarcBoule** [comment]
Requesting an update please, now at v2.1.3: fixed a small but important issue with my frankenstein-ish Schmitt trigger. The head of the master branch can be pulled. Thanks!

**Comment by MarcBoule** [comment]
Requesting an update please, now at v2.4.0: now using the global dark panel setting in Rack; the plugin now has a minRackVersion of 2.4.0. 

The head of the master branch can be pulled. Thanks!

**Comment by MarcBoule** [comment]
Requesting an update please, now at v2.4.1. 
Most of the Cppcheck warnings should be gone, and improved preciseness of clocks' timekeeping.
Head of master branch can be pulled.
Thanks!

**Comment by MarcBoule** [comment]
Requesting an update please, now at v2.4.2.
Deprecated the SMS16 module, created a new module called NoteEcho, made minor changes to the sequencers to make them compatible with NoteEcho, and other very minor changes to BigButton and AdaptiveQuantizer.
The head of master branch can be pulled.
Thanks!

**Comment by cschol** [comment]
Build failure on macOS platform: https://github.com/MarcBoule/ImpromptuModular/issues/73

**Comment by MarcBoule** [comment]
Requesting an update please, now at v2.4.3.
Small tweaks and bugfixes. The head of master branch can be pulled.
Thanks!

**Comment by cschol** [comment]
@MarcBoule please update the version in the `plugin.json` to 2.4.3.

**Comment by MarcBoule** [comment]
Ah, forgot to do a push, sorry about that, done now!

**Comment by AndrewBelt** [comment]
@MarcBoule said via email

>If this plugin ceases to be compatible with the current version of VCV Rack, and no contact can be established with the plugin's author within a reasonable time-frame (a few weeks or so), then this policy statement allows the owner(s) of VCV Rack to designate a new developer who can fork the project and maintain its inclusion in the VCV Library

**Comment by MarcBoule** [comment]
Requesting an update please, now at v2.5.0. Thanks!
