### ISSUE TITLE
MSM

### ISSUE THREAD

**Issue by Phal-anx** [VCVRack/library#376]
MSM v0.6.0 plugin is ready here:
https://github.com/Phal-anx/MSM/releases/tag/0.6.0

  "name": "MSM",
  "author": "Phal-anx",
  "license": "CC BY-NC-ND 4.0",
  "contactEmail": "phal.anx.art@gmail.com",
  "pluginUrl": "https://github.com/Phal-anx/MSM",
  "manualUrl": "https://drive.google.com/file/d/1Cjof90oYVltSJuXu0hqpw9hIN3r3U94T/view",
  "latestVersion": "0.6.0"

**Comment by Phal-anx** [comment]
forgot to include the sha256. Not sure if they are needed from my side but here you go...

win:
a934df9adb9c9b3b89a0fb2617e8e368dfffd7c81914825a9f49c477fe33aec6

lin:
5ef840954b122f94260e41af038d23667a6e4c686728bf65e66b684d06cb4ede

mac:
1563c9fb1bfb88503fc10061473cff132d4fa89c08fc75730449c48cb026d40b

I m gonna release v0.6.1 in a week or maybe 2. which means of course that you will get an update notice here. I hope Andrew will figure out a way to include the closed source modules soon (dont stress yourself!). Anyway I will just keep this issue update-to-date.

**Comment by Phal-anx** [comment]
Because of Andrew's post (plugin support from developers) in the official FB Group I request hereby to add the contactEmail (I think now its called authorEmail) from above to the MSM manifest.

**Comment by AndrewBelt** [comment]
Updated 471ba67

**Comment by mdemanett** [comment]
Think this is up to date; closing it until next time.

**Comment by AndrewBelt** [comment]
Does @Phal-anx  want to add his repo to this build system?

**Comment by Phal-anx** [comment]
@AndrewBelt  I made my plugin closed source a while ago because Rob Hordijk only allowed me to release the TVCF (TwinPeak filter clone) when closed source. Therefor I m not gonna share the source code on github. 

Uploaded a update today (0.6.1)

"name": "MSM",
"author": "Phal-anx",
"authorUrl": "https://phal-anx.github.io",
"license": "CC BY-NC-ND 4.0",
"contactEmail": "phal.anx.art@gmail.com",
"manualUrl": "https://drive.google.com/file/d/1Cjof90oYVltSJuXu0hqpw9hIN3r3U94T/view",
"latestVersion": "0.6.1"

**Comment by AndrewBelt** [comment]
Opening discussion at https://github.com/VCVRack/community/issues/353#issuecomment-395866042 about free closed plugins.

**Comment by Phal-anx** [comment]
From my point of view I’ve got a few options as of right now.
a: get rid of the TVCF filter completely and make the plugin open source again.
b: create an additional plugin which is closed source for the TVCF and share it through my github website, while having the rest in another plugin open source again.
c: get my plugin deleted from the plugin manager and share it only through my website.
d: stop sharing my plugin at all.

I actually dont want to do any of those things above but since a few weeks I m strongly thinking about those points and what I gonna do. But probably it will be c and come back when there is a solution for free closed source plugins

**Comment by AndrewBelt** [comment]
Okay, we now allow free closed-source plugins. https://github.com/VCVRack/community#addingupdating-your-plugins-build-for-closed-source-free-and-commercial-plugins

**Comment by netboy3** [comment]
I've adopted MSM and am the new maintainer. I would like to update MSM in the plugin library. Please note that the repo URL has changed:

Location: https://github.com/netboy3/MSM-vcvrack-plugin
Version: 1.0.0
Commit Hash: 95288c447f1eaf723ccf907cf06b7225eb9a2c4d

**Comment by netboy3** [comment]
Location: https://github.com/netboy3/MSM-vcvrack-plugin
Version: 2.0.1
Commit Hash: a93513a1b0b29d24b81bb4ae85c3fa970e61b250

**Comment by netboy3** [comment]
Fix a few bugs and buttons enhancements
Location: https://github.com/netboy3/MSM-vcvrack-plugin
Version: 2.0.3
Commit Hash: da38052ab9bc846a7d0ed40471a39f943bef89c2
