### ISSUE TITLE
AmalgamatedHarmonics

### ISSUE THREAD

**Issue by jhoar** [VCVRack/library#384]
Tag here: https://github.com/jhoar/AmalgamatedHarmonics/tag/0.6.0

"name": "Amalgamated Harmonics"
"author": "John Hoar"
"license": "BSD-3-Clause"
"contactEmail": "amalgamatedharmonics@outlook.com"
"manualUrl": "https://github.com/jhoar/AmalgamatedHarmonics/wiki"
"sourceUrl": "https://github.com/jhoar/AmalgamatedHarmonics"
"latestVersion": "0.6.0"

**Comment by mdemanett** [comment]
Hi @jhoar - please update your Makefile to have VERSION 0.6.1.  This will unblock the review/build process -- a version of your module already went out to the package manager as 0.6.0, and so to get a new one out, the version needs to bump up, and that new version needs to match the Makefile.  More discussion at #356.

**Comment by jhoar** [comment]
Done - thanks!

**Comment by phdsg** [comment]
updated: https://github.com/VCVRack/community/commit/918539d7e9e735964c24ca1d730437dc5e438324

**Comment by AndrewBelt** [comment]
Updated build.

**Comment by jhoar** [comment]
version: 0.6.2
hash: 28eaf8c715f1dc3689a6d9195cdc14a6005011c5

Can you please set the email link in the plugin page to 

amalgamatedharmonics@outlook.com

thanks!

**Comment by jhoar** [comment]
version 0.6.3
hash: 219b05037d27136b557214c0aec0c634bc7426e5

thanks!

**Comment by jhoar** [comment]
version: 0.6.3.1
hash: ceaaf8b0268dc7acf8cf47a5426ab02f8592d7d1

Sorry!

**Comment by jhoar** [comment]
Version: 0.6.3.1
Hash: ceaaf8b0268dc7acf8cf47a5426ab02f8592d7d1

Sorry!

**Comment by AndrewBelt** [comment]
Updated build, keeping open

**Comment by AndrewBelt** [comment]
Updated build

**Comment by jhoar** [comment]
Version: 0.6.4
Hash: e6aeac2934d99b9ee7fcb357f74fa55c79fb056d

**Comment by AndrewBelt** [comment]
Updated build

**Comment by jhoar** [comment]
Version: 1.0.0
b5f1e62eb44b0804cc80425138001236e8db5048

**Comment by cschol** [comment]
Compile error on Mac platform: https://github.com/jhoar/AmalgamatedHarmonics/issues/25

**Comment by jhoar** [comment]
Fix for jhoar/AmalgamatedHarmonics#26

4a832e9a0cfb513ccd23ecd6273735e3a0c69769

**Comment by jhoar** [comment]
Roll up of bug fixes for v1

dbb00832e92dc1bf8a7cf77bd71650c2487737a0

**Comment by cschol** [comment]
Version needs to be updated in the `plugin.json`.

**Comment by jhoar** [comment]
8425ebdfa7c7f263e2195a4129bba54d8cfb165a

**Comment by AndrewBelt** [comment]
@jhoar I build with `CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ STRIP=x86_64-w64-mingw32-strip RACK_DIR={RACK_SDK} make dist` with `x86_64-w64-mingw32-gcc (GCC) 7.3.0`.

**Comment by jhoar** [comment]
OK, so I'm using gcc 8.3.0 as I re-installed msys recently. Going to see if I can roll back to 7.3.0.

**Comment by jhoar** [comment]
version: 1.0.2
hash: 0dc7ff19e295e5a493ac6b70028bc2da3806d661

**Comment by jhoar** [comment]
Sorry, this one:

e6fd69efc53270a2bccc0ff7e12b7ed597526abc

**Comment by jhoar** [comment]
version: 1.0.3
hash: 25a0f239ec1089b3e400bec791c9bdaae122c820

**Comment by jhoar** [comment]
While this is still open can you use this hash:

796a9616a8a6ae047dbbf4d081ca2bb416ff4aa9

thanks

**Comment by jhoar** [comment]
version: 1.0.4
hash: 7aff0aab7de66f7ad5afae56986eda54138d6a2c

**Comment by cschol** [comment]
Compile failure on Mac platform: https://github.com/jhoar/AmalgamatedHarmonics/issues/41

**Comment by jhoar** [comment]
Fixed in commit c27092decfaff08fcc4e9371c19f70b3763a6baa

**Comment by cschol** [comment]
One more issue on Linux: https://github.com/jhoar/AmalgamatedHarmonics/issues/42

**Comment by jhoar** [comment]
Oops, sorry:
Hopefully fixed in
7264486735e1a856b605656f7d29145acebd6a70

**Comment by jhoar** [comment]
version: 2.0.0
hash: cc50e849ff14636ab164919c270627ce9c17e106

**Comment by rubyglow** [comment]
Thanks John! I think you need to re-open this issue for it to be noticed.

**Comment by jhoar** [comment]
version: 2.0.1
hash: bf74c2b7674c610cfc57421157d814c98bd92438
