### ISSUE TITLE
moDllz

### ISSUE THREAD

**Issue by dllmusic** [VCVRack/library#389]
Just downloaded Rack 0.6 (Mac) and my bin Build does not include the latest module. Poly XBender (Source including latest module was updated a couple of days ago...so I guess the build was done before that)... 
Manual is updated too but with the same link, so it's showing up fine.
Could the Team please rebuild?... I don't think it's necessary to renumber to 0.6.1 but it could be done if it's necessary... Thank you
https://github.com/dllmusic/moDllz

**Comment by dllmusic** [comment]
Version 0.6.1. Updated new module.

**Comment by dllmusic** [comment]
Updating info as requested...

version 0.6.1
hash : commit 59c14cf1064f4b3b539228cf728b56d4bc970348
branch master
https://github.com/dllmusic/moDllz

Thank you

**Comment by phdsg** [comment]
updated: https://github.com/VCVRack/community/commit/e31fbb73226f78cef2ff826fbe258794615f0c13

**Comment by AndrewBelt** [comment]
Updated build.

**Comment by dllmusic** [comment]
Thanks...closing until next update.

**Comment by dllmusic** [comment]
fixed 3 wrong svgs wrongfully uploaded on previous version. Bumped version 1 digit...

version : 0.6.2
commit 4165f04295184a2f6f0292bcbd839ddc308a8ca2
branch master

Thanks

**Comment by dllmusic** [comment]
Thanks. closing until next update

**Comment by dllmusic** [comment]
version 0.6.4
commit hash : 0c6e4ddf890334a24c4876049f6dadb5bf25b453
Master branch

new Module MIDI MPE / Poly 8  + updated MIDI Dual CV  + Updated Midi Panels

**Comment by AndrewBelt** [comment]
Build error on Linux

```
g++  -Wsuggest-override -std=c++11  -DSLUG=moDllz -fPIC -I/Rack-SDK/include -I/Rack-SDK/dep/include -DVERSION=0.6.4 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/MIDI8MPE.cpp.o src/MIDI8MPE.cpp
src/MIDI8MPE.cpp: In member function 'void MIDI8MPE::releaseNote(uint8_t, uint8_t, uint8_t)':
src/MIDI8MPE.cpp:334:67: error: no matching function for call to 'find(std::vector<unsigned char>::iterator, std::vector<unsigned char>::iterator, uint8_t&)'
   auto it = std::find(cachedNotes.begin(), cachedNotes.end(), note);
                                                                   ^
In file included from /usr/include/c++/5/bits/locale_facets.h:48:0,
                 from /usr/include/c++/5/locale:40,
                 from /usr/include/c++/5/iomanip:43,
                 from src/moDllz.hpp:4,
                 from src/MIDI8MPE.cpp:6:
/usr/include/c++/5/bits/streambuf_iterator.h:369:5: note: candidate: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^
/usr/include/c++/5/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
src/MIDI8MPE.cpp:334:67: note:   '__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char> >' is not derived from 'std::istreambuf_iterator<_CharT>'
   auto it = std::find(cachedNotes.begin(), cachedNotes.end(), note);
                                                                   ^
src/MIDI8MPE.cpp:340:70: error: no matching function for call to 'find(std::vector<unsigned char>::iterator, std::vector<unsigned char>::iterator, uint8_t&)'
    auto it = std::find(cachedMPE[i].begin(), cachedMPE[i].end(), note);
                                                                      ^
In file included from /usr/include/c++/5/bits/locale_facets.h:48:0,
                 from /usr/include/c++/5/locale:40,
                 from /usr/include/c++/5/iomanip:43,
                 from src/moDllz.hpp:4,
                 from src/MIDI8MPE.cpp:6:
/usr/include/c++/5/bits/streambuf_iterator.h:369:5: note: candidate: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^
/usr/include/c++/5/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
src/MIDI8MPE.cpp:340:70: note:   '__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char> >' is not derived from 'std::istreambuf_iterator<_CharT>'
    auto it = std::find(cachedMPE[i].begin(), cachedMPE[i].end(), note);
 ```

**Comment by dllmusic** [comment]
fixed missing  libraries . new commit.
version 0.6.4
hash: 1cbee780bae5147b0c105141d963aa5e22489047
Master branch
https://github.com/dllmusic/moDllz

**Comment by AndrewBelt** [comment]
Updated build

**Comment by dllmusic** [comment]
Updated.   Better (7x less) cpu load on MIDI Poly 16

version 0.6.5
hash: eb5687066f1ceda99a9162a49f309a269632cb8c
Master branch
https://github.com/dllmusic/moDllz

**Comment by dllmusic** [comment]
Update. Better (7x less) cpu load on MIDI Poly 16

version 0.6.5
hash: eb5687066f1ceda99a9162a49f309a269632cb8c
Master branch
https://github.com/dllmusic/moDllz

**Comment by dllmusic** [comment]
Update... MIDI 8 MPE . New Plus mode and 6x user ccs. MIDI Poly 16 fixed: voice count, continue seq.(Updated Manual)

version 0.6.6
hash: d646313b4d1eef323a9e294856f017252b6161fc
Master branch
https://github.com/dllmusic/moDllz

**Comment by AndrewBelt** [comment]
Updated build

**Comment by dllmusic** [comment]
moDLLz plugins updated to v1 Rack. (same functionality for now...). Thanks!

version: 
1.0.0
Commit HASH:
4950b648239a1b3a8a2553b9974676b3c1b01a39

**Comment by cschol** [comment]
Invalid entries in `plugin.json`: https://github.com/dllmusic/moDllz/issues/14

**Comment by dllmusic** [comment]
Fixed json license info and author url

version:
1.0.0
Commit HASH:
28c0d9a140895754bfe27618a22f3b0fefba73e2

**Comment by dllmusic** [comment]
plugins updated to v1.1 .Added new module. Thanks.

version 1.1.0
commit hash:
f7b71c298eaae3990acdb54ca37c9df3158d248b

**Comment by dllmusic** [comment]
I just fixed a small detail with the display...so if you guys haven't proceed with the update, please use this hash instead... Thank you
version 1.1.0
commit hash:
bdf0f043ae9aad2718c46a6eee9875af049d6e89

**Comment by dllmusic** [comment]
Updated. Fixed voice channel outputs in MPE. Added auto re-scan midi missing device. Thanks!
 
version 1.1.1
hash: feeb5a38c601ad172b831daf2658355dd297b4f3

**Comment by dllmusic** [comment]
Updated ! Fixed MIDI display/select on Windows system. Added Dynamic MPE Voice channels. Thanks!
 
version: 1.1.4
hash: 1f729936d3be732859ca9710fd60d7d27c23435b

**Comment by dllmusic** [comment]
The svg panel of latest module was not displaying correctly. It's fixed now.... (sorry to update just for this svg file) Thank you

version 1.1.5
hash e5e5062dc39e95c7e6382654cca7fdad5971c9d7

**Comment by dllmusic** [comment]
Updated. Thanks. Added mpe ch voices dyn lock to midi chnls. Param edit focus 10 sec timeout.

version# 1.1.6
commit# bda3b8f64c11fb7336376c99aacdd608e2a1c5d0

**Comment by dllmusic** [comment]
Updated.. fixed outputs num on MPE module
Version# 1.1.7
Commit# f8bdf5101eec4e5c71b74e29c0eb46b47bc4e20b

**Comment by dllmusic** [comment]
Version # 2.0.0
Commit# 0b8876b69e3be58a117538374823a7aa71fe218b

MIDIpolyMPE module ... I will be adding other ones on next versions. Thank you.

**Comment by dllmusic** [comment]
Version # 2.0.2
Commit# 088440c2342716d4f664c7129d795e5231598902
Please use this one ( fixed sustain param  and panel)
Thank you

**Comment by cschol** [comment]
Crash when using module with VST: https://github.com/dllmusic/moDllz/issues/25

**Comment by dllmusic** [comment]
I wrote to VCVrack support to get the Studio Version to test VST. Thank you.

**Comment by dllmusic** [comment]
Version # 2.0.3
Commit # 90704089e9e8142580f16df5f8f7de48170820a2
VST now reloads fine. I had a font set on instantiating a widget that was causing the crash.
Thanks

**Comment by dllmusic** [comment]
Version # 2.0.4
Commit # a5ffa6d1254be9ee8b603420ebc1c7208eadc1fc
(Fixed filters lambda for CCs and PBend)
Thanks

**Comment by dllmusic** [comment]
Version # 2.0.5 
commit # 0a57fb80c13199ea14e879562cc9b7a764f4e311

Thank you
MIDI Poly MPE Updated poly modes. Added steal modes, & unison spread
New modules PolyGlider & Kn8b

**Comment by cschol** [comment]
Failed to load SVG panel: https://github.com/dllmusic/moDllz/issues/26

**Comment by dllmusic** [comment]
Fixed PolyGlider.svg name warning
version# 2.0.5
commit# 287233af347434744e2e7f27c3bd17f82fea02dc

**Comment by dllmusic** [comment]
...if possible please use this commit instead...(fixed json info and display on Kn8b module). Thank you
version# 2.0.5
commit# 4d888b77194ea46b1af6e6ba02a62067bc31b540

**Comment by dllmusic** [comment]
version# 2.1.0
Commit# 5fe6a59e182da3402aa9e7dba0538dcd3c2399a0
New module Xpand (voice & output expander for MIDI Poly) + minor fixes
Thank you

**Comment by dllmusic** [comment]
version# 2.1.2
commit# 7a038e02ba175a524a16ac5e2f9e3d2baac2066f
Fixed MPE+ HiRes + updated KnobVCA
Thank you
