### ISSUE TITLE
TheXOR

### ISSUE THREAD

**Issue by The-XOR** [VCVRack/library#397]
.gitmodules for my repository  (TheXOR) has an invalid url, it should be corrected as:

url = https://github.com/The-XOR/RackPlugins

the same for the .json file in manifest folder

Thank you

**Comment by phdsg** [comment]
Updated information

**Comment by mdemanett** [comment]
Hello @The-XOR -- please update your Makefile to bump the VERSION to 0.6.1 -- this will unblock the review/build process.  Same deal as at #356.

**Comment by phdsg** [comment]
updated: https://github.com/VCVRack/community/commit/fd939843b1e5ce5492f0dc997f875c635d96b59c

@The-XOR srry only saw your comment in #269 today
next time, reply here for a (probably) faster update

**Comment by phdsg** [comment]
Updated build.

**Comment by The-XOR** [comment]
New version: 0.6.15
branch: master
git rev-parse HEAD: 0dc5dc25bb264f6d52d20a14a80c6db791487603

**Comment by phdsg** [comment]
@The-XOR assuming this is meant as a half step towards 0.6.2.
@AndrewBelt may correct me here but i think it's actually stepping forward to "fifteen".

**Comment by AndrewBelt** [comment]
Updated builds

**Comment by The-XOR** [comment]
New version: 0.6.2
branch: master
git rev-parse HEAD: a1e49f04f9c09edd90a5ab1f868a902a5ccea89e

thanks.

**Comment by The-XOR** [comment]
Migration to V1 completed,
git rev-parse HEAD:  7d3dcbc671c7d6a316d0bd4ebd5921b57eff23c6

Cheers

**Comment by cschol** [comment]
Compilation failed: https://github.com/The-XOR/RackPlugins/issues/23

**Comment by The-XOR** [comment]
A file case mismatch for inferior (case sensitive) OSes?
Will check asap,  I am on the beach 🌞 now


Il sab 3 ago 2019, 15:14 cschol <notifications@github.com> ha scritto:

**Comment by cschol** [comment]
`plugin.json` issues: https://github.com/The-XOR/RackPlugins/issues/24

**Comment by The-XOR** [comment]
... in the meanwhile, version 1.1.1 is out
 git rev-parse HEAD:
cdb3e61c32eebcee2327e3bba00eb6743c0c72c1

thanks

**Comment by cschol** [comment]
This commit does not exist in the repository. Please provide a valid commit and a branch name if applicable.

**Comment by The-XOR** [comment]
sorry, my fault  :-(

$ git rev-parse HEAD
6878ae0187043ed317cf90026ed455cb26a6ef1f

branch is "uno". sorry again.

**Comment by cschol** [comment]
No worries.

The dependency on `-lopengl32` is a problem on macOS and Linux platforms and won't work this way. Have you tried building this on macOS and Linux platforms?

**Comment by AndrewBelt** [comment]
Updated build to 1.0.1.

**Comment by The-XOR** [comment]
> No worries.
> 
> The dependency on `-lopengl32` is a problem on macOS and Linux platforms and won't work this way. Have you tried building this on macOS and Linux platforms?

I updated the makefile and now is os-dependent. The problem is that I can only guess what is needed in other OSes,  If it is not working, someone with a strange, non windows operating system should send me the correct makefile.

**Comment by cschol** [comment]
Strange?! You Windows people are strange. ;)

Those changes fixes the cross-compilation issues and we are good to go. Thanks!

**Comment by The-XOR** [comment]
1.1.1 is out (please note that the last version was 1.1.**0** , not 1.1.1 as I wrongly commented above)
$ git rev-parse HEAD
8ead6c0e7d65aa87a162ab69e32477041faa977d

cheers
X:

**Comment by The-XOR** [comment]
small bug corrected, head is now
8e454702f6b64f40ff229016ea94a3591122094c

**Comment by cschol** [comment]
Compile failure on Mac platform: https://github.com/The-XOR/RackPlugins/issues/31

**Comment by cschol** [comment]
The GitHub URL for this project is invalid and the submodule has been removed from the library repository. Please resubmit a valid URL for this plugin in this thread and we will re-add the plugin. Note, that this does not affect availability of existing binaries of the plugin via the VCV Rack Plugin Manager.
