### ISSUE TITLE
NonLinearInstruments

### ISSUE THREAD

**Issue by NonLinearInstruments** [VCVRack/library#420]
name: NonLinearInstruments
author: Ignasi Alvarez Garriga
license: BSD-3-Clause
pluginUrl: https://github.com/NonLinearInstruments/NLNRI_VCVRackPlugins
authorUrl: https://www.ignasialvarez.cat
manualUrl: https://github.com/NonLinearInstruments/NLNRI_VCVRackPlugins/blob/master/README.md
sourceUrl: https://github.com/NonLinearInstruments/NLNRI_VCVRackPlugins
latestVersion: 0.6.0

**Comment by NonLinearInstruments** [comment]
version: 0.6.0
commit: 551e5f84b49849f2b472214992ee8a406791ee24
branch: master

**Comment by phdsg** [comment]
updated: https://github.com/VCVRack/community/commit/e83f11ca79e9d7ce7cf63231e0327ff5632a3321

**Comment by AndrewBelt** [comment]
Updated build.

**Comment by dizzisound** [comment]
Update: 
version: 1.0.0
commit: fffadfeefeb2b93f707143a888648b56e6a3ab15
branch: master

[NonLinearInstruments/NLNRI_VCVRackPlugins@fffadfee](https://github.com/NonLinearInstruments/NLNRI_VCVRackPlugins/commit/fffadfeefeb2b93f707143a888648b56e6a3ab15)

thanks

**Comment by dizzisound** [comment]
On behalf of @NonLinearInstruments 

Update:
version: 2.0.0
commit: 215f17aaa69e945b09d88f4619f2993fffd7d151
branch: master

thanks!
