### ISSUE TITLE
Koralfx-Modules

### ISSUE THREAD

**Issue by koralfx** [VCVRack/library#436]
Change slug name (from KoralfxVCV).
{
  "name": "Koralfx Modules",
  "author": "Tomek Sosnowski",
  "authorEmail": "koralfx@gmail.com",
  "license": "BSD-3-Clause",
  "pluginUrl": "https://github.com/koralfx/Koralfx-Modules/",
  "authorUrl": "https://github.com/koralfx/",
  "manualUrl": "ttps://github.com/koralfx/Koralfx-Modules/blob/master/README.md",
  "sourceUrl": "https://github.com/koralfx/Koralfx-Modules/",
  "latestVersion": "0.6.2",
  "status": "available",
  "donateUrl": "https://www.paypal.me/koralfx/"
}

**Comment by phdsg** [comment]
@koralfx 
before we can queue this for the next build cycle, there's a few things in your [`Makefile`](https://github.com/koralfx/Koralfx-Modules/blob/master/Makefile#L34-L49) that are incompatible with the current build system.
removing the marked lines should fix it.

**Comment by koralfx** [comment]
Ok. Thx.

**Comment by koralfx** [comment]
- NEW VERSION: 0.6.3
- the new commit hash: bb0204bf577a0007093a9734e669bf465fddd358
- branch: master

```
{
"name": "Koralfx Modules",
"author": "Tomek Sosnowski",
"authorEmail": "koralfx@gmail.com",
"license": "BSD-3-Clause",
"pluginUrl": "https://github.com/koralfx/Koralfx-Modules/",
"authorUrl": "https://github.com/koralfx/",
"manualUrl": "ttps://github.com/koralfx/Koralfx-Modules/blob/master/README.md",
"sourceUrl": "https://github.com/koralfx/Koralfx-Modules/",
"latestVersion": "0.6.3",
"status": "available",
"donateUrl": "https://www.paypal.me/koralfx/"
}
```

**Comment by koralfx** [comment]
- NEW VERSION: 0.6.4
- the new commit hash: b0625c1ea1522ec4f8d61c6b3eb7f0d4ae5ef793
- branch: master

```
{
  "name": "Koralfx Modules",
  "author": "Tomek Sosnowski",
  "authorEmail": "koralfx@gmail.com",
  "license": "BSD-3-Clause",
  "pluginUrl": "https://github.com/koralfx/Koralfx-Modules/",
  "authorUrl": "https://github.com/koralfx/",
  "manualUrl": "ttps://github.com/koralfx/Koralfx-Modules/blob/master/README.md",
  "sourceUrl": "https://github.com/koralfx/Koralfx-Modules/",
  "latestVersion": "0.6.4",
  "status": "available",
  "donateUrl": "https://www.paypal.me/koralfx/"
}
```

**Comment by koralfx** [comment]
- NEW VERSION: 0.6.7
- the new commit hash: 4340525a669294b8b893b951294bf24463ad91f8
- branch: master
```
{
  "name": "Koralfx Modules",
  "author": "Tomek Sosnowski",
  "authorEmail": "koralfx@gmail.com",
  "license": "BSD-3-Clause",
  "pluginUrl": "https://github.com/koralfx/Koralfx-Modules/",
  "authorUrl": "https://github.com/koralfx/",
  "manualUrl": "ttps://github.com/koralfx/Koralfx-Modules/blob/master/README.md",
  "sourceUrl": "https://github.com/koralfx/Koralfx-Modules/",
  "latestVersion": "0.6.7",
  "status": "available",
  "donateUrl": "https://www.paypal.me/koralfx/"
}
```

**Comment by AndrewBelt** [comment]
No need to post the JSON, just the changes you need (e.g. updated to 0.6.7)

**Comment by phdsg** [comment]
updated build

**Comment by koralfx** [comment]
- NEW VERSION: 0.6.8
- the new commit hash: f074262982d75883359cf3dccbd0702429b6a205
- branch: master

**Comment by mdemanett** [comment]
Updated.

**Comment by AndrewBelt** [comment]
Updated build.

**Comment by koralfx** [comment]
- NEW VERSION: 0.6.9
- the new commit hash: 4775be2c6b5d454cdb80de6dcaca8902d3473622
- branch: master

**Comment by koralfx** [comment]
Hi! This is first update to V1

- NEW VERSION: 1.0.0
- repo: https://github.com/koralfx/Koralfx-Modules.git
- commit hash: 454fabc5e2f21b5388f40f371ed693e47b63c6a4
- branch: master

**Comment by koralfx** [comment]
Sorry, last commit hash is:
26234dc958d89682b5a616e648a389ef5440d037
and version is 1.0.1

**Comment by cschol** [comment]
The following issues were found in the manifest:

```
Validating Koralfx-Modules
authorUrl: no URL specified
sourceUrl: no URL specified
Invalid license ID: proprietary
```

Please provide a `sourceUrl`, which is pointing to your Github repo.

The license seems to have changed from BSD-3-Clause to **proprietary**. Is that correct?

@AndrewBelt Does this license change sound OK? I am still a little confused about the new plugin licensing requirements and "grandfathering".

**Comment by AndrewBelt** [comment]
The LICENSE.txt file is 3-clause BSD. That needs to be changed in the manifest.

In general, I think all source-available plugins should be allowed in this library repo.

**Comment by cschol** [comment]
Cool. @koralfx can you please clarify the license in the `plugin.json`? Thanks.

**Comment by koralfx** [comment]
Ok, so...

- repo: https://github.com/koralfx/Koralfx-Modules
- commit hash: ba3caca1dc290c62932906097bd3b80021e0a1a7
- version 1.0.2

Thanks!
