### ISSUE TITLE
Qwelk

### ISSUE THREAD

**Issue by raincheque** [VCVRack/library#442]
commit: ed6a9d1c6a8075feef7177bac735986d782e0efc
branch: master

```
name: Qwelk
author: raincheque
license: MIT
pluginUrl: https://github.com/raincheque/qwelk
manualUrl: https://github.com/raincheque/qwelk/blob/master/README.md
sourceUrl: https://github.com/raincheque/qwelk
latestVersion: 0.6.0
```

**Comment by phdsg** [comment]
updated build

**Comment by cschol** [comment]
Migrated from #545:

Hello everyone. Requesting an update for the Qwelk modules, new version is 0.6.1. commit: f62ec1e88e6630540b9fbdcbc018653c4a7bc5a5 branch: master

**Comment by AndrewBelt** [comment]
Updated build.

**Comment by raincheque** [comment]
requesting update

new version: 1.0.0
commit hash: f3a359c71719d0fbf80e2c95925fb4555756dfe2

thank you

**Comment by cschol** [comment]
Welcome back. :)
