### ISSUE TITLE
alto777_LFSR

### ISSUE THREAD

**Issue by alto777** [VCVRack/library#446]
~ I didn't find a "permanent communication channel" thread, I think the current listing for alto777_LFSR is leftover from an old time pull request I thought had died in the 5->6 frenzy. So here I start it.

NEW VERSION: 0.6.01
the new commit hash: 9c21e187bcc916e175f5200ac8678a43481c383b
branch: master

{
  "name": "alto777 LFSR",
  "author": "Robert A Moeser",
  "authorEmail": "ram32768@gmail.com",
  "license": "BSD-3-Clause",
  "sourceUrl": "https://github.com/alto777/LFSR"
  "latestVersion": "0.6.01",
  "repoVersion": "master"
  "status": "available"
}

**Comment by mdemanett** [comment]
I forgot to link the PR here -- but this is ready to build.

**Comment by alto777** [comment]
**Thank you**, I see the progress. I was caught off guard by the offer of  a manual for my plugin, since it is only a dream at this time - someone on the community volunteers team added it to my manifest.

The link in the manifest leads only to "Not Found", which I interpreted as a subtle suggestion to get busy writing, but when I looked into it a bit, I determined that the link is incorrect, and should read (I think)

https://github.com/alto777/LFSR/blob/master/README.md

based on looking at a few others.

**Comment by mdemanett** [comment]
That's my bad -- I saw the manual URL set in your src/LFSR.cpp and figured it should be in the manifest as well (one gets used on the plugin manager, the other by Rack itself) -- and it's typical to link the README as the manual if there isn't a real one -- but I didn't check the link and missed that it was invalid.

Anyway, fixed it!

**Comment by alto777** [comment]
Well, record it as _my_ bad - that thing in the LFSR.cpp no doubt got created when I global-changed the Template. I'll fix it and look for other things like that when I clean things up a bit.

No doubt there will be a number of pesky issues. I'll let them accumulate unless a show-stopper crops until advancing the version. Or can little things still be under 0.6.02? I've never dealt with any real versioning regime or etiquette.

I am still going on my skills at mimicry - see Star Trek TOS “A Piece of the Action” but I am coming away from totally faking this to a certain level of competence.

Thanks for you help and rapid attention to this matter.

**Comment by phdsg** [comment]
updated build.

**Comment by alto777** [comment]
Okay, I think this is fixed. I made changes online, but checkout gave me unchanged files (?), finally just made a new version.

NEW VERSION 0.6.21 at https://github.com/alto777/LFSR
commit 00cfcf740cc079d6faa7f6230b3f46c0e4ff8767
branch v0.6.21

{
"name": "alto777 LFSR",
"author": "Robert A Moeser",
"authorEmail": "ram32768@gmail.com",
"license": "BSD-3-Clause",
"sourceUrl": "https://github.com/alto777/LFSR",
"manualUrl": "https://github.com/alto777/LFSR/blob/v0.6.21/README.md",
"repoVersion": "0.6.21",
"latestVersion": "0.6.21",

"status": "available"
}

**Comment by alto777** [comment]
Thank you tireless community workers, @mdemanett!

I got my own stuff using the plugin manager, it's all there. The manual link is incorrect, I tested

https://github.com/alto777/LFSR/blob/v0.6.21/README.md

which is in my manifest posted above but not the manifest in rack/community/manifests, I am guessing this is still a hand-control op that got missed.

And I would change the default branch of my repo to v0.6.21, but the warnings and what reading I have done reduce my enthusiasm for doing, the git ice I'm on is pretty thin - if it ain't broke…

So I suppose we expect anyone poking around in the source or building it themselves would also be smart enough to clone/checkout to get v0.6.21?

Lastly, I did have a bit of excitement with this, can I assume the appearance in the plugin manager means you were able to build out v0.6.21 all platforms?

Again, thank you for the help and your work. Now I suppose the errors will show themselves.

**Comment by AndrewBelt** [comment]
In the future, it's better to state what changes you want in English. We don't take the JSON manifest directly from developers in these request threads. We have to scan for changes against the existing manifest if developers dump the raw JSON, which is an additional step.

**Comment by alto777** [comment]
Thank you, will comply. 

TBH I'm not sure what I am doing with all those branches either. I have to stop and figure out git for real. Git/github seems to be without my grasp ATM.

**Comment by alto777** [comment]
OK, I manned up (pun intended) and raised my level of git/hub incompetence. I seem to have without excitement or mystery or collateral damages merged v0.6.21 into the master branch. I made the default branch v0.6.21 for now, that makes AFAIK everything on the plugin manager page work as desired and does not disenfranchise work you already did.

I'll know more before anything goes up again and land on something I understand and works well for you guys.

THANK YOU. I love Rack - my family, not so much. :-)

**Comment by alto777** [comment]
I merged a pull request which puts my work at version 1.0.0 for Rack V1x

Thank you, netboy3!

LFSR - v1.0.0
Source: https://github.com/alto777/LFSR.git
Branch: master
SHA: c9b0feef18e7f79c444cdd62f9b0628afb354fa6
Version: 1.0.0

**Comment by cschol** [comment]
Integrated. Welcome back!

**Comment by alto777** [comment]
Update to V2
Location: https://github.com/alto777/LFSR
Branch: V2X
Version: 2.0.0
Commit Hash: 9e23b5d4e4f55437d34351f0f7149e067689f8bc

**Comment by cschol** [comment]
Fonts stored across multiple frames: https://github.com/alto777/LFSR/issues/10

**Comment by alto777** [comment]
Update to V2
Location: https://github.com/alto777/LFSR
Branch: V2X
Version: 2.0.0
Commit Hash: 7b977dbc81a76b1c00e86e943a7a2af8ecc8bf51
