### ISSUE TITLE
SubmarineFree

### ISSUE THREAD

**Issue by david-c14** [VCVRack/library#456]
Slug: SubmarineFree
Version: 0.6.1
Source repository: https://github.com/david-c14/SubmarineFree.git
Commit: 5c4f6985d74178be885f749cde0c4ac27ecfeeed
Tag: v0.6.1
License: GPL-3
Author: carbon14
Website: https://github.com/david-c14/SubmarineFree
Manual: https://github.com/david-c14/SubmarineFree/blob/master/manual/index.md

**Comment by david-c14** [comment]
Licence is incorrect. This plugin is BSD 3.

**Comment by phdsg** [comment]
Updated build.

**Comment by david-c14** [comment]
Plugin updated 25th April - 6 new devices

Slug: SubmarineFree
Version: 0.6.2
Source repository: https://github.com/david-c14/SubmarineFree.git
Commit: 83e92a672052da52719b71d441a42a6383f8d4ed
Tag: v0.6.2
License: BSD-3
Author: carbon14
Website: https://github.com/david-c14/SubmarineFree
Manual: https://github.com/david-c14/SubmarineFree/blob/master/manual/index.md

**Comment by phdsg** [comment]
Update build.

**Comment by david-c14** [comment]
Plugin updated 6th May - 2 new devices; improvements to LA-108
Please note that the author name should be carbon14 - it is currently out of date in the plugin manager.
Thank you.

Slug: SubmarineFree
Version: 0.6.3
Source repository: https://github.com/david-c14/SubmarineFree.git
Commit: ac5713cb5f76bed0dc92235e9e94f8f771508593
Tag: v0.6.3
License: BSD-3
Author: carbon14
Website: https://github.com/david-c14/SubmarineFree
Manual: https://github.com/david-c14/SubmarineFree/blob/master/manual/index.md

**Comment by david-c14** [comment]
Plugin updated 7th June - 6 new devices; visual change to knobs across all devices

Thank you.

Slug: SubmarineFree
Version: 0.6.4
Source repository: https://github.com/david-c14/SubmarineFree.git
Commit: 2125b79d4e3dd9a39a452338d8dc75d1927a7e6c
Tag: v0.6.4
License: BSD-3
Author: carbon14
Website: https://github.com/david-c14/SubmarineFree
Manual: https://github.com/david-c14/SubmarineFree/blob/master/manual/index.md

**Comment by AndrewBelt** [comment]
Updated build

**Comment by AndrewBelt** [comment]
I've pulled the build because I'm getting linkage issues with Mingw and the Rack 0.6.0 SDK. The previous build was with the Rack 0.6.1dev SDK, but the loggerLog symbols don't load on Rack 0.6.0.

**Comment by david-c14** [comment]
Should I take out my calls to warn and info?At least for now. I guess that any module using these deprecated calls will have this problem.

**Comment by AndrewBelt** [comment]
They're not deprecated. What I did in 0.6.1dev was turn them into macros which call a new function `loggerLog`, to support filenames and line numbers.
Removing the calls will solve this, if I build against the current 0.6.1dev SDK.
I don't know why the Mingw build was not working against the 0.6.0 SDK, but I don't have time to look at that.

**Comment by david-c14** [comment]
Sorry, I used the word deprecated, because that's what's in the logger.cpp source. I see now that it refers to something subtly different.

**Comment by david-c14** [comment]
I've commited changes to my master branch to comment out all uses of warn, info and debug until this stabilizes.

commit 9afc3858427a75b9857a018c663ebabdc158aa35

**Comment by mdemanett** [comment]
Updated the repo pointer, build should be good to go again.

**Comment by AndrewBelt** [comment]
Okay, we now allow free closed-source plugins. https://github.com/VCVRack/community#addingupdating-your-plugins-build-for-closed-source-free-and-commercial-plugins

**Comment by AndrewBelt** [comment]
Let's wait until Rack 0.6.1 releases with this. I've spent too much time on it as it is.

**Comment by david-c14** [comment]
Fine with me.

**Comment by AndrewBelt** [comment]
Re-added.

**Comment by david-c14** [comment]
Plugin updated 20th July - 13 new devices; 1 updated device; significant refactoring

Thank you.

Slug: SubmarineFree
Version: 0.6.5
Source repository: https://github.com/david-c14/SubmarineFree.git
Commit: bb7849affcf57b2c78904c691934ad2d8315e465
Tag: v0.6.5
License: BSD-3
Author: carbon14
Website: https://github.com/david-c14/SubmarineFree
Manual: https://github.com/david-c14/SubmarineFree/blob/master/manual/index.md

**Comment by cschol** [comment]
@mdemanett I reviewed the code for `0.6.5` and it looks good. For some reason I can't commit to the `community` repo to update the manifest (despite GitHub Collaborator status).

**Comment by AndrewBelt** [comment]
@cschol Fixed, you now have write access.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by david-c14** [comment]
Plugin updated 28th July - 7 new devices; 4 updated devices; updated visuals

Thank you. Apologies for the short turnaround - it was unexpected

Slug: SubmarineFree
Version: 0.6.6
Source repository: https://github.com/david-c14/SubmarineFree.git
Commit: 3806a06e5bac7bdd953aa6134fe7f842d5c81363
Tag: v0.6.6
License: BSD-3
Author: carbon14
Website: https://github.com/david-c14/SubmarineFree
Manual: https://github.com/david-c14/SubmarineFree/blob/master/manual/index.md

**Comment by cschol** [comment]
@david-c14 Compilation fails on Ubuntu 18.04.

```
src/AO1.cpp: In member function ‘void AO1<x, y>::step()’:
src/AO1.cpp:388:37: error: there are no arguments to ‘isfinite’ that depend on a template parameter, so a declaration of ‘isfinite’ must be available [-fpermissive]
    outputs[OUTPUT_Y_1 + iy].value = isfinite(vy)?vy:0.0f;
                                     ^~~~~~~~                                                           
src/AO1.cpp:388:37: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
src/AO1.cpp: In instantiation of ‘void AO1<x, y>::step() [with unsigned int x = 6; unsigned int y = 6]’:
src/AO1.cpp:421:144:   required from here                         
src/AO1.cpp:388:45: error: ‘isfinite’ was not declared in this scope
    outputs[OUTPUT_Y_1 + iy].value = isfinite(vy)?vy:0.0f;
                                     ~~~~~~~~^~~~     
src/AO1.cpp:388:45: note: suggested alternative:       
In file included from ../../include/util/math.hpp:3:0,
                 from ../../include/util/common.hpp:85,
                 from ../../include/rack.hpp:4,
                 from src/SubmarineFree.hpp:1,         
                 from src/AO1.cpp:1:                               
/usr/include/c++/7/cmath:585:5: note:   ‘std::isfinite’
     isfinite(_Tp __x)                                                                                  
     ^~~~~~~~                                                     
src/AO1.cpp:391:45: error: ‘isfinite’ was not declared in this scope
    outputs[OUTPUT_X_1 + ix].value = isfinite(vx[ix])?vx[ix]:0.0f;
                                     ~~~~~~~~^~~~~~~~ 
src/AO1.cpp:391:45: note: suggested alternative:       
In file included from ../../include/util/math.hpp:3:0,
                 from ../../include/util/common.hpp:85,
                 from ../../include/rack.hpp:4,
                 from src/SubmarineFree.hpp:1,         
                 from src/AO1.cpp:1:
/usr/include/c++/7/cmath:585:5: note:   ‘std::isfinite’
     isfinite(_Tp __x)                                                                                  
     ^~~~~~~~                            
```

Add `std::` prefix to `isfinite` functions to fix this for all .cpp files that use `isfinite` (AO1.cpp, LightKnob.cpp).

**Comment by david-c14** [comment]
I was about to say that this same code built for you last week! Thanks for the heads up. I'll add it to the list along with createParamCentered.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by david-c14** [comment]
Plugin updated 14th August - 2 new devices; minor bug fixes; updated visuals 

Thank you.

Slug: SubmarineFree 
Version: 0.6.7 
Source repository: https://github.com/david-c14/SubmarineFree.git 
Commit: dfa8e0937f4e059a3a59ea0fc9a3bef62d779966 
Tag: v0.6.7 
License: BSD-3 
Author: carbon14 
Website: https://github.com/david-c14/SubmarineFree 
Manual: https://github.com/david-c14/SubmarineFree/blob/master/manual/index.md
--

**Comment by AndrewBelt** [comment]
Updated build

**Comment by david-c14** [comment]
Plugin updated 28th August - 2 bug fixes, one of which is serious

Thank you.

Slug: SubmarineFree 
Version: 0.6.8
Source repository: https://github.com/david-c14/SubmarineFree.git 
Commit: c7e78414ae627364ee4e85981b4aa157d0615aeb 
Tag: v0.6.8 
License: BSD-3 
Author: carbon14 
Website: https://github.com/david-c14/SubmarineFree 
Manual: https://github.com/david-c14/SubmarineFree/blob/master/manual/index.md

**Comment by AndrewBelt** [comment]
Updated build

**Comment by david-c14** [comment]
I am migrating this plugin to v1. I do not currently require any help. Thank you.

**Comment by david-c14** [comment]
Plugin updated 4th July - Ported to v1

Slug: SubmarineFree
Version: 1.0.0
Source repository: https://github.com/david-c14/SubmarineFree.git
Commit: 03e1928100b3a02ce6fed7d552cc76e4a46621eb
Tag: v1.0.0
License: BSD-3
Author: carbon14
Website: https://github.com/david-c14/SubmarineFree
Manual: https://github.com/david-c14/SubmarineFree/blob/master/manual/index.md

**Comment by cschol** [comment]
`plugin.json` issues: https://github.com/david-c14/SubmarineFree/issues/31

**Comment by david-c14** [comment]
Updated - mainly with bug fixes 5th July

Slug: SubmarineFree
Version: 1.0.0
Source repository: https://github.com/david-c14/SubmarineFree.git
Commit: 65458da82d02c178455620d9ad3843cbca17dcb9
Version 1.0.1
Tag v1.0.1

**Comment by david-c14** [comment]
Updated: Ported WireManager from SubmarineUtilities plugin v0.6 to SubmarineFree v1

Slug: SubmarineFree
Version: 1.0.2
Source repository: https://github.com/david-c14/SubmarineFree.git
Commit: e92dd4fa26deb2724a5a31d29a3168593b8059de
Tag v1.0.2

**Comment by david-c14** [comment]
Updated: Significant bug fix in WM-101. Caused wires to be transparent even when device not loaded into rack.

Slug: SubmarineFree
Version: 1.0.3
Source repository: https://github.com/david-c14/SubmarineFree.git
commit: ff881fdd06285107875c88e46bbf6a3782bf03d6
Tag: v1.0.3

**Comment by david-c14** [comment]
Updated: More features in WM-101 and more control of text formatting in TD-xxx devices

Slug: SubmarineFree
Version: 1.0.4
Source repository: https://github.com/david-c14/SubmarineFree.git
commit: 81f25c6421f04e4860c38327662c7d586c4ab386
Tag: v1.0.4

**Comment by david-c14** [comment]
The introduction of LightSlider in the VCV Rack api has led to a conflict in the SubmarineFree plugin.

I'm not requesting that the plugin is updated at this stage, but I have renamed my conflicting component; so if at some point the plugin fails to build in the library, there is an interim release which can be used:

Tag: v1.0.4a

https://github.com/david-c14/SubmarineFree/commit/5f0fc4736fc2bcd3a64226f285f218fce83f1123

**Comment by AndrewBelt** [comment]
Okay, no need for update so I'll keep this issue closed, but good to hear that it is fixed when you update to v1.0.5 or so.

**Comment by david-c14** [comment]
Updated: New DO-1xx Digital Operators device

Slug: SubmarineFree
Version: 1.1.0
Source repository: https://github.com/david-c14/SubmarineFree.git
commit: 3a4419fcd742dd2045131d630f82e25ed1b8da6c
Tag: v1.1.0

Thank you

**Comment by david-c14** [comment]
Updated: New SN-101 Smooth Noise Oscillator

Slug: SubmarineFree
Version: 1.1.1
Source repository: https://github.com/david-c14/SubmarineFree.git
commit: dc63fc3d97c18f03c72ce0ad9892b605006594af
Tag: v1.1.1

Thank you

**Comment by david-c14** [comment]
Updated: New LT-116 Linear Transformations
Additional functionality in WM-101 Wire Manager

Slug: SubmarineFree
Version: 1.1.2
Source repository: https://github.com/david-c14/SubmarineFree.git
commit: b17c3fc43ad5908f96b75b5eb4a69f067df0c4d0
Tag: v1.1.2

Thank you

**Comment by david-c14** [comment]
Oops,  urgent bug fix and other things.

Added WM-102 Wire manager standalone billboard
And fixed a serious crashing bug

Slug: SubmarineFree
Version: 1.1.3
Source repository: https://github.com/david-c14/SubmarineFree.git
commit: 76cd00de4c5485e4636968e7e4ec1b4f2aac5d40
Tag: v1.1.3

Thank you

**Comment by david-c14** [comment]
Added HS-101 Hi-Res Storage Scope
Added TD-410 Multi Text Display
Added XF-301 Small Form Factor Cross Fader
Added color tracking to WM-102

Slug: SubmarineFree
Version: 1.1.4
Source repository: https://github.com/david-c14/SubmarineFree.git
commit: f53626d1817d2855dfbb54f7f997ac4092476bf3
Tag: v1.1.4

Thank you

**Comment by david-c14** [comment]
Slug: SubmarineFree
Version: 1.1.5
Source repository: https://github.com/david-c14/SubmarineFree.git
commit: 6bf18aacef55987204818feda5748cd31c80000d
Tag: v1.1.5

Thank you

**Comment by david-c14** [comment]
Slug: SubmarineFree
Version: 1.1.6
Source repository: https://github.com/david-c14/SubmarineFree.git
commit: 6f8077875320a77e03fa2057e907b8f4ad274464
Tag: v1.1.6

Thank you

**Comment by cschol** [comment]
Build failure on Windows and Mac platforms: https://github.com/david-c14/SubmarineFree/issues/133

**Comment by david-c14** [comment]
updated

tag v1.1.6
commit f9d9a61d896bbec67116c08f1b7426067ad9d171

**Comment by david-c14** [comment]
Slug: SubmarineFree
Version: 1.1.7
Source repository: https://github.com/david-c14/SubmarineFree.git
commit: 1b7249fa5f1ff929d7e62fbf96391e6600966121
Tag: v1.1.7

Thank you

**Comment by david-c14** [comment]
Slug: SubmarineFree
Version: 1.1.8
Source repository: https://github.com/david-c14/SubmarineFree.git
commit: f5d96c4b6dea97ca4182dcc2be3bb14292a539ea
Tag: v1.1.8

Thank you

**Comment by david-c14** [comment]
Slug: SubmarineFree
Version: 1.1.9
Source repository: https://github.com/david-c14/SubmarineFree.git
commit: 2bcd18991eb635291ecc6c503ac94b56e0a112c7
Tag: v1.1.9

Thank you

**Comment by david-c14** [comment]
Slug: SubmarineFree
Version: 1.1.10
Source repository: https://github.com/david-c14/SubmarineFree.git
commit: 8ef8f9d4eccf0093f97a9fb8931256ec185a0f4e
Tag: v1.1.10

Thank you

**Comment by david-c14** [comment]
Slug: SubmarineFree
Version: 2.0.0
Source repository: https://github.com/david-c14/SubmarineFree.git
Branch v2.
commit: 50ac076e5fdddb68fafeea76a4e292dd648fce88
Tag: v2.0.0.Beta.1

Thank you

**Comment by david-c14** [comment]
Slug: SubmarineFree
Version: 2.0.1
Source repository: https://github.com/david-c14/SubmarineFree.git
commit: e0a4b18eb9166bc500137cada78334e04e8563b3
Tag: v2.0.1

This is for VCVRack v2 obviously.

Thank you

**Comment by david-c14** [comment]
Slug: SubmarineFree
Version: 2.0.2
Source repository: https://github.com/david-c14/SubmarineFree.git
commit: d5f1c10a069bfa52e5552b615fd7e1ca9d465dee
Tag: v2.0.2

Includes bugfix which is expected to resolve a crash using SS-212 module in VCVRack 2.0.3b

Thank you

**Comment by david-c14** [comment]
Slug: SubmarineFree
Version: 2.0.3
Source repository: https://github.com/david-c14/SubmarineFree.git
commit: f1d9e81e9d67463b4281998d281785bdd5e971f9
Tag: v2.0.3

Includes bugfix for reported crash caused by uninitialized variable in XF-301  h.t. AndrewBelt, cschol

Thank you

**Comment by david-c14** [comment]
Slug: SubmarineFree
Version: 2.0.4
Source repository: https://github.com/david-c14/SubmarineFree.git
commit: 16796663a6e75a9d8fd003961329e98c531e848f
Tag: v2.0.4

Includes bugfix for sizing issue in TD-316, wiring bugs in AG-202, OG-202 and XG-202 and new device AO-101

Thank you
