### ISSUE TITLE
Mental

### ISSUE THREAD

**Issue by Strum** [VCVRack/library#458]
Mental modules community thread

**Comment by Strum** [comment]
Mental Modules
By Strum
strum@softhome.net
Version 0.6.0
License BSD 3
Code : https://github.com/Strum/Strums_Mental_VCV_Modules
Manual (work in progress) : https://github.com/Strum/Strums_Mental_VCV_Modules/wiki

**Comment by AndrewBelt** [comment]
@mdemanett You've mistakenly set "latestVersion", instead of repoVersion. Reverted your commit.

**Comment by Strum** [comment]
@AndrewBelt,

What happened there?

Is there something I need to change?

I realised I'd forgotten to add some graphics to the res folder, though git added them automatically, updated hour or so ago, should all be there now.

**Comment by phdsg** [comment]
@mdemanett let's pause here before a new try.
i recommended to Strum to purge his git history from old zips and stuff (~100mb).

**Comment by Strum** [comment]
@mdemanett 
@phdsg 

Sorted, should be ready to go.

**Comment by phdsg** [comment]
had a bit of a struggle with the changed history and syncing/fetching and then broke the repo for a few minutes, but i think it's fixed now.

**Comment by mdemanett** [comment]
Sorry about that...@phdsg thanks for fixing!

**Comment by phdsg** [comment]
Updated build.

**Comment by Strum** [comment]
I'm really sorry guys but I made a cock up with one of the background graphics and had to rescale it.

It's the MedKnob.svg in /res/components, no changes to the code you can just overwrite that file without rebuild the .dll

Sorry again, I'll test more thoroughly in future.

Cheers

**Comment by AndrewBelt** [comment]
Updated builds

**Comment by Strum** [comment]
@AndrewBelt , thanks Andrew, sorry again, I am slowing learning though
:)

**Comment by cschol** [comment]
`plugin.json` issues: https://github.com/Strum/Strums_Mental_VCV_Modules/issues/45

**Comment by Strum** [comment]
OK .json fixed, let me know if there are any further issues

**Comment by Strum** [comment]
Update ready, on the master branch.

**Comment by cschol** [comment]
`make dist` fails: https://github.com/Strum/Strums_Mental_VCV_Modules/issues/52

**Comment by Strum** [comment]
@cschol ,
oops, sorry, forgot about that, removed the demo patches and am moving them to the wiki.
sorted now.

**Comment by Strum** [comment]
Fixed json issue
updated version to 1.0.2

**Comment by Strum** [comment]
Hi,

I've made an update finally, new code is on the 103_update branch.

Thanks

Strum

**Comment by Strum** [comment]
New version 1.0.3
Commit Hash : 7f1cf3807d226786e8537c0a7c7bed3de1838d75

**Comment by cschol** [comment]
@Strum it looks like you have changed the module slugs in this version. Unfortunately, that is not allowed since it breaks backwards compatibility with patches created with previous versions. Please revert the module slug changes and resubmit. Thanks.

**Comment by Strum** [comment]
Andrew had asked me to make those changes.
Given there have been a number of updates in the past that have broken old patches I find it a bit strange developers are now concerned about it. Perhaps you could talk to Andrew about it.

Cheers

Strum

**Comment by AndrewBelt** [comment]
@Strum I don't remember asking you to make changes, but plugin and module slugs can't be changed once submitted to the VCV Library. However, you can change plugin or module names. See https://vcvrack.com/manual/Manifest for a reference of these properties.

**Comment by Strum** [comment]
text of your emails on the subject

Hello,
I'm emailing to suggest the following changes to your plugin manifest for your plugin's next update, at your convenience/discretion.

- Change the brand from "Strum's VCV Modules" to "Mental". Your plugin's brand name should match the brand name text on the panel, which is "Mental".
- Remove the "Mental" string from module names. The module name should match the module name on the panel. For example, https://library.vcvrack.com/Mental/MentalMults should be "Mults", and https://library.vcvrack.com/Mental/MentalMixer should be "Master Mixer".
- The screenshot generated from https://library.vcvrack.com/Mental/MentalButtons is nonexistent. Make sure that the module correctly displays in Rack's Module Browser, which it currently doesn't. For help with plugin development, ask questions at https://community.vcvrack.com/c/development/8.

Your plugin URL on the VCV Library: https://library.vcvrack.com/Mental
Reference for the `plugin.json` file: https://vcvrack.com/manual/Manifest
Instructions for requesting an update to the VCV Library: https://github.com/VCVRack/library#adding-your-plugin-to-the-vcv-library-for-open-source-plugins

Andrew Belt
VCV https://vcvrack.com/


Hi,
I noticed the brand of your plugins is "Strum's VCV Modules". I'd prefer that the name "VCV" is left out since it's a trademarked name. But regardless, it probably makes more sense to set the brand to "Mental" and remove the "Mental" string from all module names. That way, instead of the full module name being "Strum's VCV Modules MentalMuxes", it would be "Mental Muxes" which is cleaner and more organized.
See https://github.com/VCVRack/library#vcv-library-database for requesting an update to the VCV Library.

Best,
Andrew Belt
VCV https://vcvrack.com/

**Comment by AndrewBelt** [comment]
Those suggestions are still valid, but they apply to names, brands, etc. The slugs should remain unchanged to maintain patch compatibility.

**Comment by cschol** [comment]
Closing until plugin is updated.

**Comment by Strum** [comment]
Sorry it's taken me a while to get back to this.

Will leave names as they were.

The basic update to get them working in version 2 is done, it's on the 200_update branch.

I'm working on adding the tool tips for another update and should get that done in the next week or 2.

Let me know if you have any further issues.

Cheers 

Strum

**Comment by cschol** [comment]
Caching font references crashes VST: https://github.com/Strum/Strums_Mental_VCV_Modules/issues/57

**Comment by Strum** [comment]
Thanks,

    Sorry about that, I hadn't tested it with VST, will fix as soon as I can.

**Comment by Strum** [comment]
Okay, think I've fixed it, hope it's right this time.

Strum.
