### ISSUE TITLE
ByteBeatMachine

### ISSUE THREAD

**Issue by bokontep** [VCVRack/library#465]
BokontepByteBeatMachine is an oscillator that renders 8KHz audio using javascript, inspired by bytebeat programs. It uses the duktape javascript engine. You can paste your javascript expression in the textarea and right click and select initialize to compile the javascript program.It uses a trig input (resets the t to zero) and an output and 2 additional inputs X and Y acting as 8 bit parameters (mind the case, it is t,X and Y). You can see a video with the module in action here: https://www.youtube.com/watch?v=AQctoH3ucmQ
The module code can be found here:
https://github.com/bokontep/BokontepByteBeatMachine
Currently it is built against 0.6 version of VCVRack
I only tested it on windows and I consider this module alpha. I posted this to get some feedback from the users. The module will be free open source. 
I used this expression for testing
`(([1.122,1.259,1.498,1.681,1.887][((t >> 12) ^ ((t >> 10)+ 3561)) %5]) * t & 128 | (([1.122,1.259,1.498,1.681,1.887][((t >> 11) ^ ((t >> 9) +2137)) %5]) * t) & ((t>>14)%120+8) | (t>>4) )`

**Comment by bokontep** [comment]
My current version hash is  30d6b28d4ad5215e935da1862c554e57f19e3c96
on master branch.
Question: How do I upload the manifest?
 
BokontepByteBeatMachine.json
{
  "name": "Bokontep Byte Beat Machine",
  "author": "ВОКОИТЕР",
  "license": "Public Domain"
  "authorUrl": "http://bokontep.blogspot.gr/",
  "authorEmail": "bokontep@gmail.com",
  "manualUrl": "https://github.com/bokontep/BokontepByteBeatMachine/blob/master/README.md",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  "sourceUrl": "https://github.com/bokontep/BokontepByteBeatMachine",
  "donateUrl": "https://www.paypal.me/AnastasiosKleisas",
  "latestVersion": "0.6.1",
  "status": "available"
}

**Comment by bokontep** [comment]
"status":"available" is not in the manifest published. Is there a problem with the build? Do you perform builds and then update the status?

Thanks in advance!

**Comment by mdemanett** [comment]
The build will happen when Andrew runs it (for everyone at once), usually once a week...when that happens the "available" flag will show up.

**Comment by cschol** [comment]
Module browser crash: https://github.com/bokontep/ByteBeatMachine/issues/1

**Comment by Coirt** [comment]
Someone on community reported a crash. Had a crash also when I searched "B"

https://community.vcvrack.com/t/plugin-crashes-vcv/4741/3

**Comment by cschol** [comment]
Known issue (see above). The build should not have gone out.

**Comment by AndrewBelt** [comment]
Removed manifest from library. Users can delete `plugins-v1/ByteBeatMachine` from their Rack user folder and relaunch Rack.

**Comment by AndrewBelt** [comment]
Closing until fixed by developer.
