### ISSUE TITLE
Automated compile possible issue?

### ISSUE THREAD

**Issue by AScustomWorks** [VCVRack/library#466]
I'm not sure about what to look for about this, so I'm asking for help:

Somehow the BPM clock module on AS modules from the automated compile is doing something strange for one Mac user(with OSX 10.8.5.)

When he sets the bpm clock value below 100 the display stops working, also the signature display settings are working strange.

Some other users tested it without any problems so I'm wondering if the automated compile + that particular combination of OS could cause the issue? 

The same user tested the module with the compiled plugin I uploaded to github, everything worked fine.

This is the code running on the module, working fine since v0.5:
```C++
//initial value for tempo
 float tempo =120.0f;
//on step();
tempo = std::round(params[TEMPO_PARAM].value);

//BpmDisplayWidget drawing code
    float *value;
    std::stringstream to_display;   
    to_display << std::setw(3) << *value;
    nvgText(vg, textPos.x, textPos.y, to_display.str().c_str(), NULL);

//BpmDisplayWidget instantiation 
  BpmDisplayWidget *display = new BpmDisplayWidget();
  display->box.pos = Vec(23,45);
  display->box.size = Vec(45, 20);
  display->value = &module->tempo;
  addChild(display); 

```
Screenshot from the user showing the error(using the plugin downloaded from plugin manager):

![32378516_10155401659942551_2928531439416770560_n](https://user-images.githubusercontent.com/34798768/40089887-e1010c38-5873-11e8-9ea9-8976bd1cf785.jpg)

My tests on Mac and Linux trying similar settings(Mac version tested with both local and pm compiles, Linux tested with local compile):

![bpm-clock](https://user-images.githubusercontent.com/34798768/40089900-f44f5c0e-5873-11e8-8a3e-d0f69a564c7e.jpg)

**Comment by AndrewBelt** [comment]
Closing since [VCV Support](https://vcvrack.com/support) is a better place for asking questions to VCV.
