### ISSUE TITLE
huaba

### ISSUE THREAD

**Issue by dhuber81** [VCVRack/library#480]
name: huaba
author: Daniel Huber
license: MIT
contactEmail: dhuber318@gmail.com
pluginUrl: https://github.com/dhuber81/huaba
authorUrl: https://github.com/dhuber81
manualUrl: https://github.com/dhuber81/huaba
sourceUrl: https://github.com/dhuber81/huaba
donateUrl: https://paypal.me/DanielHuber81
latestVersion: 0.6.1
Branch: master

**Comment by AndrewBelt** [comment]
@mdemanett Yes, they set `RACK_DIR` (I assume that's what you mean.)

**Comment by mdemanett** [comment]
Right, RACK_DIR.  @dhuber81 you're good to go then.

**Comment by dhuber81** [comment]
i changed the RACK_DIR to the standard, thanks guys.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by dhuber81** [comment]
huaba is updated to version 0.6.2
new module switched multiple added

commit abea99d00177dde6fba561e3d1962c9ec5e0914f

thank you,
Daniel

**Comment by AndrewBelt** [comment]
Updated build

**Comment by mdemanett** [comment]
Sure...however, please bump your Makefile version to 0.6.3 -- a build went out as 0.6.2, so the version needs to change for things to work.

**Comment by dhuber81** [comment]
Updated the Makefile and changed name of the module from swmultiple to ab bus.
version 0.6.3
branch: master
latest commit b8d69c8f659438546396f65bd878bc23d68d68cf

**Comment by AndrewBelt** [comment]
Updated build

**Comment by dhuber81** [comment]
finaly updated to rack v1
Version: 1.1.0
Commit Hash: c8e08fe39e2ca55a05c2fb40f963cbc2d511697b
