### ISSUE TITLE
FrankBuss

### ISSUE THREAD

**Issue by FrankBuss** [VCVRack/library#482]
I wrote a new plugin see here:
https://github.com/FrankBuss/Formula
Feel free to add it, if there is not already such a plugin available. It is public domain (CC0).

**Comment by AndrewBelt** [comment]
Updated build

**Comment by FrankBuss** [comment]
New version 0.6.1:
https://github.com/FrankBuss/Formula/tree/40876113610f2b8573d7f535637ec350d998c51f
Please change the documentation link to the README file as well instead of linking to the repository root:
https://github.com/FrankBuss/Formula/blob/master/README.md
And I have a donation link now: 
https://www.paypal.me/frankbuss

**Comment by AndrewBelt** [comment]
Updated build

**Comment by FrankBuss** [comment]
New version with performance improvements: simple expressions like x+1 are about 8 times faster, and more complex expressions are 2-3 times faster. Current head:
https://github.com/FrankBuss/Formula/tree/5ea8733bbc72d11d383a0dcd7b929bf915c68d87

**Comment by AndrewBelt** [comment]
Build fails on MacOS

```
x86_64-apple-darwin15-clang++-libc++ -std=c++11 -stdlib=libc++ -DSLUG=FrankBussFormula -fPIC -I/home/vortico/src/VCV/public/community/Rack-SDK/include -I/home/vortico/src/VCV/public/community/Rack-SDK/dep/include -DVERSION=0.6.2 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -c -o build/src/formula/Parser.cpp.o src/formula/Parser.cpp
src/formula/Parser.cpp:313:10: error: target exception specification is not superset of source
                return function;
                       ^
src/formula/Parser.cpp:323:10: error: target exception specification is not superset of source
                return function;
                       ^
src/formula/Parser.cpp:333:10: error: target exception specification is not superset of source
                return function;
 ```

**Comment by FrankBuss** [comment]
Should work now:
https://github.com/FrankBuss/Formula/tree/6638244558048824ac505f385fd5cda70a795cd6

**Comment by AndrewBelt** [comment]
Updated build

**Comment by FrankBuss** [comment]
I updated my Formula module for 1.0. Tested on Linux, but should work on the other systems as well. The polyphony function uses the same formula for all channels.

I also changed the slug of the plugin, because I plan to write more modules, and then I think it makes more sense that it looks like the other plugins, so the manufacturer name as the plugin name, and then the individual modules, like "Formula", instead of "FrankBussFormula". I know it breaks patches, but I think this is ok for a major version change to 1.0. Breaking patches could be avoided, if the load-function in VCV Rack replaces FrankBussFormula with Formula, but I don't know if it is worth the trouble.

https://github.com/FrankBuss/FrankBussRackPlugin/tree/1eaa27c0bbeab71c56dd50ad4b56b9421e65b93e

**Comment by cschol** [comment]
`plugin.json` issue and missing `Makefile`: https://github.com/FrankBuss/FrankBussRackPlugin/issues/1

**Comment by AndrewBelt** [comment]
Why not keep the old slug and just change the name? Humans other than us don't see the slug name.

**Comment by FrankBuss** [comment]
I wouldn't like it, because it was not the right thing to do in the first place. But I've added the porting instructions to the manual now as well:
https://github.com/FrankBuss/FrankBussRackPlugin/blob/master/README.md#porting-old-frankbussformula-vcv-files-to-the-new-plugin

**Comment by FrankBuss** [comment]
New version:
https://github.com/FrankBuss/FrankBussRackPlugin/releases/tag/1.1.0
Changes: the Formula module has now the Polyphonic tag as well, and there is a new Shaker module.

**Comment by cschol** [comment]
Amazing what type of "meta modules" people come up with.

**Comment by Ahornberg** [comment]
port to rack 2
version 2.0.0
commit f9280536fa37cae51a72406cdc01f6c109e887f7

**Comment by Frank-Buss** [comment]
Updated to VCV Rack 2, https://github.com/FrankBuss/FrankBussRackPlugin commit hash: 5074123c6296ad239a0f31739ad7dd959455878a 
Tested on Linux, but should work on Windows and Mac as well.
