### ISSUE TITLE
Alikins

### ISSUE THREAD

**Issue by alikins** [VCVRack/library#484]
name: Alikins
author: Adrian Likins
authorEmail: alikins@gmail.com
pluginUrl: https://github.com/alikins/Alikins-rack-plugins
sourceUrl: https://github.com/alikins/Alikins-rack-plugins
authorUrl: https://github.com/alikins
manualUrl: https://github.com/alikins/Alikins-rack-plugins/blob/master/README.md
license: BSD-3-Clause
latestVersion: 0.6.1
productId:

Manifest exists at https://github.com/VCVRack/community/blob/master/manifests/Alikins.json

(manifest not updated yet, just setting up the plugin thread/issue)

**Comment by alikins** [comment]
New version: 0.6.1
commit hash: 7e531ae1f996bec5a2d9d5b2a4ee8075f5e4ccb0  (https://github.com/alikins/Alikins-rack-plugins/commit/7e531ae1f996bec5a2d9d5b2a4ee8075f5e4ccb0)

**Comment by AndrewBelt** [comment]
Updated build

**Comment by alikins** [comment]
Update request.

version: 0.6.2
commit hash: 1a7f83f36beb82a7c303975c0feebb0e4dcd84e3

 (https://github.com/alikins/Alikins-rack-plugins/commit/1a7f83f36beb82a7c303975c0feebb0e4dcd84e3)

**Comment by cschol** [comment]
@AndrewBelt This plugin didn't get picked up in the last update.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by cschol** [comment]
@alikins At the above mentioned revision, the version number in the Makefile is still 0.6.3.

**Comment by alikins** [comment]
@cschol Ah, indeed. New version/sha:

Version: 0.6.5
commit hash: 6430f43ecd29a7693bce95078338d2fa5b14b10c 

(https://github.com/alikins/Alikins-rack-plugins/commit/6430f43ecd29a7693bce95078338d2fa5b14b10c)

**Comment by AndrewBelt** [comment]
Updated build

**Comment by alikins** [comment]
Update request for the port to v1 API, version 1.0.0.
The master branch is updated to v1 API, 505c735f102181f7764b0c974db70498f8b3dcf6

Version: 1.0.0
commit hash: 505c735f102181f7764b0c974db70498f8b3dcf6

(https://github.com/alikins/Alikins-rack-plugins/commit/505c735f102181f7764b0c974db70498f8b3dcf6)

**Comment by cschol** [comment]
Compile failure: https://github.com/alikins/Alikins-rack-plugins/issues/12

**Comment by alikins** [comment]
@cschol Should be fixed in https://github.com/alikins/Alikins-rack-plugins/commit/f69196284d5858214e81c6e394f372bd123f3a8a

Version: 1.0.0
commit hash: f69196284d5858214e81c6e394f372bd123f3a8a

**Comment by AndrewBelt** [comment]
@alikins The pluginUrl and sourceUrl in your manifest are broken links.

**Comment by alikins** [comment]
Update request for v1.0.1 
The master branch at a04f173753c8c7408ea79d2418efd5ed2fc726f5

Version: 1.0.1
commit hash: a04f173753c8c7408ea79d2418efd5ed2fc726f5

Includes the fixes for plugin.json mentioned in https://github.com/VCVRack/library/issues/484#issuecomment-501661038
and a few other fixes like the Nan handling mentioned in the forum.

(https://github.com/alikins/Alikins-rack-plugins/commit/a04f173753c8c7408ea79d2418efd5ed2fc726f5)

**Comment by AndrewBelt** [comment]
Build failed on Linux. Use `std::isfinite`
```
g++ -std=c++11 -Wsuggest-override -fPIC -I/Rack-SDK/include -I/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/ParamFloatField.cpp.o src/ParamFloatField.cpp
In file included from src/SpecificValue.cpp:21:0:
src/cv_utils.hpp: In function 'int volts_to_octave(float)':
src/cv_utils.hpp:80:24: error: 'isfinite' was not declared in this scope
     if (!isfinite(volts)) {
                        ^
```

**Comment by cschol** [comment]
Strange, I wonder why I didn't catch this. What g++ are you using?

**Comment by AndrewBelt** [comment]
```
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
```

**Comment by AndrewBelt** [comment]
@alikins

**Comment by alikins** [comment]
Update request for v1.0.1
The master branch at bd6825081c142319a5c8f27287e1434fd4f45434

Version: 1.0.1
commit hash: bd6825081c142319a5c8f27287e1434fd4f45434

This includes fix for the 'isfinite' build issue mentioned in https://github.com/VCVRack/library/issues/484#issuecomment-509750684
(https://github.com/alikins/Alikins-rack-plugins/commit/bd6825081c142319a5c8f27287e1434fd4f45434)

**Comment by alikins** [comment]
update request for v2.0.0

The master branch at c403f2c04e10dbb1513c9632c77801de6f8e9af2

Version: 2.0.0
commit hash: c403f2c04e10dbb1513c9632c77801de6f8e9af2

Updates to port to v2.0.0 API
