### ISSUE TITLE
s-ol

### ISSUE THREAD

**Issue by s-ol** [VCVRack/library#486]
my modules have been updated to the version v`0.6.1`, the commit and tag are here:
s-ol/vcvmods@39c442b

**Comment by AndrewBelt** [comment]
Updated build

**Comment by s-ol** [comment]
Updated to ABI/API v1 at  s-ol/vcvmods@77d1f54c  / https://github.com/s-ol/vcvmods/releases/tag/v1.0.0

**Comment by cschol** [comment]
`plugin.json` is missing: https://github.com/s-ol/vcvmods/issues/6

**Comment by s-ol** [comment]
apologies for that - since the last tag was technically unbuild-able I fixed the issue and promoted the tag v1.0.0 to s-ol/vcvmods@17f7b13479
