### ISSUE TITLE
LindenbergResearch

### ISSUE THREAD

**Issue by lindenbergresearch** [VCVRack/library#487]
Hi all,
I request an update of my modules.
The current source can be found here:
https://github.com/lindenbergresearch/LRTRack/tree/v0.6.1

I updated the Makefile and set the new Version.
I hope this is OK so far.

Thanks in advance,
Patrick

**Comment by AndrewBelt** [comment]
Updated build

**Comment by lindenbergresearch** [comment]
Thanks!

**Comment by lindenbergresearch** [comment]
Please update to current version: 
Version: v0.6.2
Hash: 8aaf3778b673cd190dec3c665c95854fe363fcb5

Changes in manifest:
{
  "name": "Lindenberg Research",
  "author": "Patrick Lindenberg / Lindenberg Research Tec.",
  "license": "proprietary",
  "authorUrl": "https://https://github.com/lindenbergresearch/",
  "authorEmail": "heapdump@icloud.com",
  "sourceUrl": "https://github.com/lindenbergresearch/LRTRack",
  "manualUrl": "https://github.com/lindenbergresearch/LRTRack/wiki/Generell-help-and-manuals",
  "latestVersion": "0.6.2",
  "repoVersion": "0.6.2",
  "status": "available"
}

Thanks!

**Comment by AndrewBelt** [comment]
Updated build

**Comment by lindenbergresearch** [comment]
Thanks

**Comment by lindenbergresearch** [comment]
Update requested:
Version: v0.6.2b (performance update)
Hash: b800881158c1a566dd0d4f2685a47aedb20fb07e

TIA,
Patrick

**Comment by AndrewBelt** [comment]
Updated build

**Comment by lindenbergresearch** [comment]
Hi, requesting update to v0.6.3, hash: 2b9a4199db271beb81af62b8f57b95b36014e3ad
Thanks in advance!

**Comment by lindenbergresearch** [comment]
Hi all,
requesting a new update for my modules with version v0.6.4 and hash: 54e5cdb532f8edfa2154e9d35f1f09e625728b3b

Thank you much in advance!

Patrick

**Comment by AndrewBelt** [comment]
Please remove all the afdesign files from the repository, or put them in a fork. I don't want to distribute 20MB of useless files.

**Comment by lindenbergresearch** [comment]
OK, makes sense, I just moved it to a non-distributable folder.
You can use hash: 78ce4ee8dc76bb2e8eff1baa01a22415a1b0533f

**Comment by AndrewBelt** [comment]
Updated build

**Comment by lindenbergresearch** [comment]
Thanks!

**Comment by lindenbergresearch** [comment]
Hi all,

requesting an update to version v0.6.5 of Lindenberg Research: 1b6ad3124082bfea5b4c5fc29feba8e4d7521334

Thanks in advance!
Patrick

**Comment by AndrewBelt** [comment]
Updated build

**Comment by lindenbergresearch** [comment]
Thanks!

**Comment by lindenbergresearch** [comment]
Hi all,

finally requesting an update to v1.0.0 of my modules at hash: 6b12618ac454a781c3f61ac2ded25474a4645d28

TIA, Patrick

**Comment by AndrewBelt** [comment]
Just a note for myself and others that this repo switched to close-source on Oct 21, 2019, hence the out of date GitHub repo and up-to-date VCV Library builds.

**Comment by cschol** [comment]
OK. Are we removing the submodule from the library repo?

**Comment by AndrewBelt** [comment]
It's already removed.
