### ISSUE TITLE
SynthKit

### ISSUE THREAD

**Issue by JerrySievert** [VCVRack/library#489]
please update SynthKit:

https://github.com/JerrySievert/SynthKit

branch: `master`
version: `0.6.1`

building:

* `git submodule update --init`
* `make`

**Comment by AndrewBelt** [comment]
Updated build

**Comment by JerrySievert** [comment]
this was closed, I was not aware that we were to open up closed tickets for new requests.

---

please update SynthKit:

https://github.com/JerrySievert/SynthKit

branch: master
version: 0.6.2

building:

git submodule update --init
make

**Comment by JerrySievert** [comment]
SynthKit has been updated to v1.0 and is ready for review:

repo: https://github.com/JerrySievert/SynthKit
branch: v1.0

build instructions:

```
$ git submodule init
$ git submodule update
$ make
```

**Comment by cschol** [comment]
git submodule checkout fails: https://github.com/JerrySievert/SynthKit/issues/15

**Comment by JerrySievert** [comment]
should now be working.

**Comment by cschol** [comment]
Please update the `plugin.json` as follows:

- `sourceUrl`: include the **full clone URL** including the `.git`
- `license`: please use the [SPDX](https://spdx.org/licenses/) designation for the license

**Comment by JerrySievert** [comment]
license updated

**Comment by JerrySievert** [comment]
SynthKit has been updated to v1.0.1 and is ready for review:

repo: https://github.com/JerrySievert/SynthKit
branch: v1.0

build instructions:

$ git submodule init
$ git submodule update
$ make

**Comment by JerrySievert** [comment]
Can you please update SynthKit:

repo: https://github.com/SVModular/SynthKit
tag: v2.0.0

build instructions:

$ git submodule init
$ git submodule update
$ make

**Comment by cschol** [comment]
It does not look like an issue with these modules, but FYI that the components in `deps/rack-components/display.hpp` (`rackcomponents`) are not loading the fonts correctly per requirements of `v2` (not storing font references across frames).
