### ISSUE TITLE
21kHz

### ISSUE THREAD

**Issue by jakehuryn** [VCVRack/library#491]
not sure if i'm doing this right

{
    "name": "21kHz",
    "author": "Jake Huryn",
    "license": "MIT",
    "authorEmail": "jakehuryn@gmail.com"
    "manualUrl": "https://github.com/21kHz/21kHz-rack-plugins/blob/master/README.md"
    "sourceUrl": "https://github.com/21kHz/21kHz-rack-plugins"
    "donateUrl": "https://www.paypal.me/JakeHuryn"
    "latestVersion": "0.6.0"
    "status": "available"
}

**Comment by 21kHz** [comment]
hey, hopefully this isn't too soon but i made a small fix to the plugin. if necessary i can update the makefile to version 0.6.1.

https://github.com/21kHz/21kHz-rack-plugins
branch: master

thanks!

**Comment by mdemanett** [comment]
The build hasn't been done yet, so I pulled in the update -- good to go.  (Had the build gone out, you'd have to bump the version.)

**Comment by AndrewBelt** [comment]
Updated build

**Comment by AndrewBelt** [comment]
Updated build

**Comment by 21kHz** [comment]
apologies if i've forgotten how this works, but it appears that the new build hasn't gone out to the plugin manager. is this waiting period after the build normal? thanks

**Comment by AndrewBelt** [comment]
What about now?

**Comment by netboy3** [comment]
I've adopted 21kHz and am the new maintainer. I would like to update 21kHz in the plugin library. Please note that the repo URL has changed:

Location: https://github.com/netboy3/21kHz-rack-plugins
Version: 1.0.1
Commit Hash: e241f019e728f03e738c1a5c335fdb541ce7cac0

**Comment by SteveRussell33** [comment]
I have permission from Jake to take over as maintainer moving forward.
Here is the new v2 repo link:
https://github.com/SteveRussell33/21kHz-v2

**Comment by AndrewBelt** [comment]
@jakehuryn Who is the current maintainer of this plugin?

**Comment by SteveRussell33** [comment]
@AndrewBelt You emailed me earlier from VCV support about this

 > would I be able to submit my 21kHz v2 repo to the VCV library as the new maintainer?

 > Yes, because it sounds like you have his permission. Just use the original VCV Library repo thread with a link to the updated git repo.

I got permission from Jake as the new maintainer. As I told netboy3 (current maintainer) in a forum PM I had no way of contacting him to ask whether he was going to continue with this particular slug (it’s been 2 years) and noted to you that he had done the v1 migration - which was added to the library 2 years ago. https://library.vcvrack.com/21kHz

It should also be noted what Jake said here: https://github.com/jakehuryn/21kHz-rack-plugins/issues/5#issuecomment-585229505

> I am glad to hear your enthusiasm about
> my modules but unfortunately they're pretty much abandoned at this point
> and I don't see myself returning to VCV rack stuff in the foreseeable
> future.

**Comment by AndrewBelt** [comment]
Okay, correct me if you're wrong, but it looks like @jakehuryn gave maintainer-ship to @netboy3, so if you want to adopt maintainer-ship, you'll need to ask @netboy3 to transfer that to you.

**Comment by SteveRussell33** [comment]
OK I understand, I assumed that because I couldn't contact the current maintainer, as a remedy to that, I could ask for the explicit permission of the original owner.

**Comment by netboy3** [comment]
@SteveRussell33, if you want to assist in maintaining, you can easily submit your V2 update as a PR to the current maintainer repo

**Comment by SteveRussell33** [comment]
@netboy3 If you're going to continue with the maintainance then I'll do that.

**Comment by netboy3** [comment]
Location: https://github.com/netboy3/21kHz-rack-plugins
Version: 2.0.1
Commit Hash: 0bee82247151e2fe2885f1e15fbbd74ddb4f48d0
