### ISSUE TITLE
CharredDesert

### ISSUE THREAD

**Issue by JerrySievert** [VCVRack/library#493]
please update CharredDesert:

https://github.com/JerrySievert/CharredDesert

branch: master
version: 0.6.2

building:

git submodule update --init
make

**Comment by JerrySievert** [comment]
please update CharredDesert:

https://github.com/JerrySievert/CharredDesert

branch: master
version: 0.6.3

building:

git submodule update --init
make

**Comment by AndrewBelt** [comment]
Updated build

**Comment by JerrySievert** [comment]
please update CharredDesert:

https://github.com/JerrySievert/CharredDesert

branch: master
version: 0.6.4

building:

git submodule update --init
make

**Comment by AndrewBelt** [comment]
Updated build

**Comment by JerrySievert** [comment]
please update CharredDesert:

https://github.com/JerrySievert/CharredDesert

branch: master
version: 0.6.5

building:

git submodule update --init
make

**Comment by AndrewBelt** [comment]
Updated build

**Comment by JerrySievert** [comment]
please update CharredDesert:

https://github.com/JerrySievert/CharredDesert

branch: master
version: 0.6.6

building:

git submodule update --init
make

**Comment by cschol** [comment]
git submodule checkout fails: https://github.com/JerrySievert/CharredDesert/issues/10

**Comment by JerrySievert** [comment]
should now be working

**Comment by cschol** [comment]
Compile error on Windows and Linux: https://github.com/JerrySievert/CharredDesert/issues/11

**Comment by cschol** [comment]
Also, please update the `plugin.json` as follows:

- `sourceUrl`: include the **full clone URL** including the `.git`
- `license`: please use the [SPDX](https://spdx.org/licenses/) designation for the license

**Comment by JerrySievert** [comment]
license updated.

**Comment by JerrySievert** [comment]
please update CharredDesert:

https://github.com/JerrySievert/CharredDesert

branch: v1.0
version: 1.0.1

building:

git submodule update --init
make

**Comment by JerrySievert** [comment]
FYI, I realized I had left a debug `fprintf` in and pushed an update at 8:30am Pacific.  Hoping that quick change makes it in this build.

**Comment by JerrySievert** [comment]
please update CharredDesert:

https://github.com/JerrySievert/CharredDesert

branch: v1.0
version: 1.1.0

building:

git submodule update --init
make

**Comment by AndrewBelt** [comment]
Skipping this build for now because the Mac 10.11 SDK breaks when including <unordered_map>.

**Comment by JerrySievert** [comment]
I'll remove the dependency, it doesn't *need* it right now.

**Comment by JerrySievert** [comment]
the dependency has been removed for now - I'll use functionality that will work with 10.11 when I add it back.

**Comment by cschol** [comment]
My SDK is 10.13 and it worked fine. Just as a data point.

**Comment by JerrySievert** [comment]
I couldn't get rack to compile in 10.10, so couldn't go that far back to test - fine removing it for now, I hadn't released a module that was doing anything with that data yet, just collecting it.

**Comment by cschol** [comment]
Compile failure on Windows: https://github.com/JerrySievert/CharredDesert/issues/15

**Comment by JerrySievert** [comment]
thanks, looking now.

**Comment by JerrySievert** [comment]
pushed the fix.

**Comment by JerrySievert** [comment]
please update CharredDesert:

https://github.com/JerrySievert/CharredDesert

branch: v1.0
version: 1.2.0

building:

git submodule update --init
make

**Comment by JerrySievert** [comment]
please update CharredDesert:

https://github.com/JerrySievert/CharredDesert

branch: v1.0
version: 1.3.0

building:

git submodule update --init
make

**Comment by JerrySievert** [comment]
as an aside, this update also adds `manualUrl` for each module.

**Comment by JerrySievert** [comment]
please update CharredDesert:

https://github.com/SVModular/CharredDesert

branch: v1.0
tag: v1.3.1

building:

git submodule update --init
make

note the changed repo location.

**Comment by JerrySievert** [comment]
please update CharredDesert:

https://github.com/SVModular/CharredDesert

branch: v2.0
version: 2.0

building:

git submodule update --init
make

**Comment by cschol** [comment]
Great job! Your plugin passed all integration tests and builds successfully against the current SDK `git.219bbaf1` for all supported platforms using the new `v2` toolchain.

However, we are not accepting submissions to the library for v2 of Rack yet. 
We will let developers know when to submit their v2 plugins to the library. Thank you.

**Comment by JerrySievert** [comment]
please update CharredDesert:

https://github.com/SVModular/CharredDesert

tag: v2.0.0
version: 2.0

building:

git submodule update --init
make

**Comment by cschol** [comment]
References to fonts stored across frames: https://github.com/SVModular/CharredDesert/issues/17

**Comment by JerrySievert** [comment]
fixed. same tag.
