### ISSUE TITLE
mscHack

### ISSUE THREAD

**Issue by mschack** [VCVRack/library#500]
0.6.3 
https://github.com/mschack/VCV-Rack-Plugins

**Comment by AndrewBelt** [comment]
Build error
```src/mscHack.cpp:46:14: error: 'unsigned int index' redeclared as different kind of symbol
 unsigned int index = 4095;
              ^
In file included from /Rack-SDK/include/util/common.hpp:7:0,
                 from /Rack-SDK/include/rack.hpp:4,
                 from src/mscHack.hpp:1,
                 from src/mscHack.cpp:1:
/usr/include/string.h:477:1: note: previous declaration 'const char* index(const char*, int)'
 index (const char *__s, int __c) __THROW
 ^
```
Use a different variable name than `index`

**Comment by mschack** [comment]
fixed

**Comment by AndrewBelt** [comment]
Updated build

**Comment by mschack** [comment]
1.0.0
https://github.com/mschack/VCV-Rack-Plugins

**Comment by mschack** [comment]
btw, unsure if I should open a new issue or use this one?

**Comment by cschol** [comment]
This one is preferred. Thank you!

**Comment by cschol** [comment]
Some `plugin.json` issues: https://github.com/mschack/VCV-Rack-Plugins/issues/88

**Comment by mschack** [comment]
1.0.1
https://github.com/mschack/VCV-Rack-Plugins

**Comment by mschack** [comment]
1.0.2
https://github.com/mschack/VCV-Rack-Plugins

**Comment by baconpaul** [comment]
Hi Folks

As pgatt and i shared with you a few months ago, we've been in touch with the original author of these plugins and they were happy for paul and i to do a 2.0 port, which we've done.

It has moved the repo and the hash.

The new repo is: https://github.com/baconpaul/mschack-VCV-Rack-Plugins

And the hash for 2.0.0 is : 42668cc2bc4c6b9ecd473586bdcddfa5e4174a0c

It was quite a lift to get these to 2.0.0 but they seem to work and we had some pre-testing by the community group which found some more bugs. My guess is there will be a 2.0.1 after that 2.0.0 hits the library though!

Thanks as always
