### ISSUE TITLE
noobhour

### ISSUE THREAD

**Issue by NicolasNeubauer** [VCVRack/library#508]
Hi,

I created a plugin, here's the content of my manifest. I'm not 100% sure if the parts in the docs about adding the repo and the manifest mean that I should do that and submit a PR, or if that's done by the community members. From a first look, it seems the latter, but please let me know if I should submit the PR. Thanks!
Nic 

{
  "name": "noobhour modules",
  "author": "Nicolas Neubauer",
  "license": "BSD-3-Clause",
  "manualUrl": "https://github.com/NicolasNeubauer/noobhour_modules/blob/master/README.md",
  "pluginUrl": "https://github.com/NicolasNeubauer/noobhour_modules",	
  "authorEmail": "noobhourmusic@gmail.com",
  "latestVersion": "0.6.0",
  "status": "available"
}

**Comment by cschol** [comment]
You don't need to submit a PR. I'll take it from here and let you know if I need anything else. Thank you for creating and submitting a module!

**Comment by cschol** [comment]
This looks good. I added the module to the community manifest. When Andrew builds the next round of plugins your module will be included in the distribution and be available via the Plugin Manager. This takes usually a few days. You don't need to do anything else, except let us know in **this issue** when a new version becomes available. We will reopen the issue and process the new module information.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by NicolasNeubauer** [comment]
Hi, 

a new version is available, it fixes two issues and introduces a new module, CustomScale.
Please find the manifest below.
Thanks!
Nic


{
  "name": "noobhour modules",
  "author": "Nicolas Neubauer",
  "license": "BSD-3-Clause",
  "manualUrl": "https://github.com/NicolasNeubauer/noobhour_modules/blob/master/README.md",
  "sourceUrl": "https://github.com/NicolasNeubauer/noobhour_modules",	
  "authorEmail": "noobhourmusic@gmail.com",
  "latestVersion": "0.6.1",
  "status": "available"
}

**Comment by NicolasNeubauer** [comment]
Btw, where would I define the tags for modules? Haven't found anything, so maybe here? If so:
- Baseliner is an attenuator and a switch
- CustomScale is a quantizer

**Comment by cschol** [comment]
It's one of the arguments of the Model definition, usually at the end of the module source code file.

**Comment by NicolasNeubauer** [comment]
Ah! Thanks - repo's updated.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by NicolasNeubauer** [comment]
Hi, 

there's a new version available under https://github.com/NicolasNeubauer/noobhour_modules/tree/0.6.2
Can you add it please? Thanks!

- introducing Bsl1r
- Customscaler:
  - renamed from CustomScale
  - significant performance improvements
  - new layout
  - randomize functionality overhauled (randomizes selected tones)
- Baseliner:
  - daisy-chaining inputs and outputs

{
"name": "noobhour modules",
"author": "Nicolas Neubauer",
"license": "BSD-3-Clause",
"manualUrl": "https://github.com/NicolasNeubauer/noobhour_modules/blob/0.6.2/README.md",
"sourceUrl": "https://github.com/NicolasNeubauer/noobhour_modules",
"authorEmail": "noobhourmusic@gmail.com",
"latestVersion": "0.6.2",
"status": "available"
}

**Comment by NicolasNeubauer** [comment]
Hi, found a bug playing around, re-made the 0.6.2 release, could you rebuild please? Correct commit is c3fae38 
Thanks & sorry for the hassle

**Comment by AndrewBelt** [comment]
Updated build

**Comment by NicolasNeubauer** [comment]
Hi,

new version 1.0.0 available under https://github.com/NicolasNeubauer/noobhour_modules/releases/tag/1.0.0 (commit
3d4ac0b4f1b60c6911bc85c8f09fcf530b1cba96)

Thanks
Nic

**Comment by cschol** [comment]
Minor `plugin.json` issues: https://github.com/NicolasNeubauer/noobhour_modules/issues/6

**Comment by NicolasNeubauer** [comment]
new version 1.0.1 available under https://github.com/NicolasNeubauer/noobhour_modules/releases/tag/1.0.1 (commit
ba3c35b162e81117446cc2a4a139a79e8ebab03d)

Thanks!

**Comment by NicolasNeubauer** [comment]
new version 1.0.2 available under https://github.com/NicolasNeubauer/noobhour_modules/releases/tag/1.0.2 (commit
1e1a908466b518261b36cf56eca54fd1365b2557)

**Comment by NicolasNeubauer** [comment]
new version available 1.0.3 under 
https://github.com/NicolasNeubauer/noobhour_modules/releases/tag/1.0.3
(commit 48f11951a147a49453e7c5463e56dd2823a679e1)

**Comment by NicolasNeubauer** [comment]
is it possible to retract this release? nothing wrong with it, just that I'd follow up with another one very soon as I've created another bugfix

**Comment by cschol** [comment]
Sure. Let us know when a new version is available.

**Comment by NicolasNeubauer** [comment]
new version available 1.0.3 under
https://github.com/NicolasNeubauer/noobhour_modules/releases/tag/1.0.3
commit c5bac4207e3fff4a2cff761523d2d7ad95de75bb

bugfixes and new module: Normaliser

**Comment by NicolasNeubauer** [comment]
new version available 2.0.0 under
https://github.com/NicolasNeubauer/noobhour_modules/releases/tag/2.0.0
commit fd172d0cd62ee6ca5612950ba22de0cca622d1ef

Migration to v2
