### ISSUE TITLE
DrumKit

### ISSUE THREAD

**Issue by JerrySievert** [VCVRack/library#510]
please update DrumKit:

https://github.com/JerrySievert/DrumKit

branch: master
version: 0.6.1

building:

git submodule update --init
make

**Comment by AndrewBelt** [comment]
Updated build

**Comment by AndrewBelt** [comment]
Should be now, failed to push I think?

**Comment by JerrySievert** [comment]
looks like, it's updated now - and showing up.   thanks.

**Comment by JerrySievert** [comment]
please update:

branch: master
version: 0.6.2

**Comment by AndrewBelt** [comment]
Updated build

**Comment by JerrySievert** [comment]
please update:

branch: master
version: 0.6.3

note, this time an update of the submodules is required, as there is functionality used from a more recent version of a dependency.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by JerrySievert** [comment]
please update:

branch: master
version: 0.6.4

**Comment by AndrewBelt** [comment]
Updated build

**Comment by JerrySievert** [comment]
DrumKit has been updated to v1.0 and is ready for review:

repo: https://github.com/JerrySievert/DrumKit
branch: v1.0

build instructions:

```
$ git submodule init
$ git submodule update
$ make
```

**Comment by cschol** [comment]
Branch `v1` does not exist in the repository!

**Comment by JerrySievert** [comment]
not sure why it didn't exist before, but it's definitely there now:

```
/tmp  git clone https://github.com/JerrySievert/DrumKit
Cloning into 'DrumKit'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 274 (delta 18), reused 11 (delta 6), pack-reused 238
Receiving objects: 100% (274/274), 6.49 MiB | 45.00 KiB/s, done.
Resolving deltas: 100% (155/155), done.
 /tmp  cd DrumKit/
 /t/DrumKit   master  tmp/DrumKit  git checkout v1.0
Branch 'v1.0' set up to track remote branch 'v1.0' from 'origin'.
Switched to a new branch 'v1.0'
```

**Comment by cschol** [comment]
It is there now. Not sure what happened. Thanks.

**Comment by cschol** [comment]
Please update the `plugin.json` as follows:

- `sourceUrl`: include the **full clone URL** including the `.git`
- `license`: please use the [SPDX](https://spdx.org/licenses/) designation for the license**

**Comment by AndrewBelt** [comment]
I usually recommend `sourceUrl` to actually just be the GitHub page. It should be the human portal for the source code, not the computer portal.

**Comment by cschol** [comment]
Oh. Sorry about that. I remembered that we had some people add it in the past. Never mind then about that.

**Comment by JerrySievert** [comment]
on license, wondering if it is worthwhile to change `helper.py` to be more intelligent about licenses - there is precedent with `npm`, would probably save some headaches.

**Comment by JerrySievert** [comment]
license updated

**Comment by AndrewBelt** [comment]
@JerrySievert In what way would you suggest?

**Comment by JerrySievert** [comment]
npm uses an spdx license package to validate licenses - obviously this wouldn't work for the python script, but there is a python spdx license package: https://pypi.org/project/spdx/

requiring a `pip install` isn't really an onerous requirement for someone who already has a development environment.

**Comment by AndrewBelt** [comment]
Storing a list of SPDX IDs is trivial, I was asking in what way the UI should work, in order to handle *all* use cases.

**Comment by baconpaul** [comment]
sorry to butt in - just saw this thread while looking for a few other 1.0 modules. Why not have make dist eject a warning to screen if you have a plugin license which isn't in the SPDX set. It's literally a couple of lines of jq and curl to get the list and check. Or add a make rule like "community_check" which starts accreting things you want to do before you send to the community list?

**Comment by JerrySievert** [comment]
"in what way" is a pretty open question - but to answer your specific one, `npm` is a pretty good example of handling it that many developers would be familiar with; when initializing a module (`package.json` in its specific case using `npm init`) it prompts much like `helper.py` does:

```
license: (ISC) Foo
Sorry, license should be a valid SPDX license expression (without "LicenseRef"), "UNLICENSED", or "SEE LICENSE IN <filename>".
license: (ISC) npm ERR! Invalid argument. Expected non-empty string.
```

where "ISC" is its default, "Foo" is what I entered.  not a perfect example since `npm` is obviously bugged here, but providing a link and doing checks at this stage would be useful.

**Comment by AndrewBelt** [comment]
What if the user wants to use a license not in the SPDX list? What if the user doesn't know what they want to license their plugin when they run `./helper.py`?

**Comment by JerrySievert** [comment]
then they can always edit the `plugin.json` file manually, since they're already doing something out of the ordinary.

**Comment by AndrewBelt** [comment]
I'm going to reject this feature request, since I feel that validation should be left up to discussions on issue tracker.

**Comment by JerrySievert** [comment]
perhaps provide a hint about what you consider valid licenses when requesting a license string in `helper.py`?

**Comment by AndrewBelt** [comment]
That feature is already present.

**Comment by JerrySievert** [comment]
DrumKit has been updated to v1.1:

repo: https://github.com/JerrySievert/DrumKit
branch: v1.0
tag: v1.1.0

build instructions:

$ git submodule init
$ git submodule update
$ make

**Comment by JerrySievert** [comment]
is there any sort of ETA for release?  seems like some things are stuck.

**Comment by JerrySievert** [comment]
DrumKit has been updated to v1.1.1:

repo: https://github.com/JerrySievert/DrumKit
branch: v1.0
tag: v1.1.1

build instructions:

$ git submodule init
$ git submodule update
$ make

**Comment by JerrySievert** [comment]
wow, that was quick. thanks!

**Comment by JerrySievert** [comment]
DrumKit has been updated to v1.1.2:

repo: https://github.com/JerrySievert/DrumKit
branch: v1.0
tag: v1.1.2

build instructions:

$ git submodule init
$ git submodule update
$ make

**Comment by JerrySievert** [comment]
DrumKit has been updated to v1.1.3:

repo: https://github.com/JerrySievert/DrumKit
branch: v1.0
tag: v1.1.3

build instructions:

$ git submodule init
$ git submodule update
$ make

**Comment by cschol** [comment]
Tag `v1.1.3` does not exist in repository. Can you check?

**Comment by JerrySievert** [comment]
oops! sorry about that.  should be there now!

**Comment by JerrySievert** [comment]
DrumKit has been updated to v1.1.4:

repo: https://github.com/JerrySievert/DrumKit
branch: v1.0
tag: v1.1.4

build instructions:

$ git submodule init
$ git submodule update
$ make

**Comment by JerrySievert** [comment]
did this somehow get lost in the ether?

**Comment by cschol** [comment]
No. Just busy with work. Did you push the changes? I don't see any updates in the repo.

**Comment by JerrySievert** [comment]
I did push the changes - the repo got moved, but GitHub usually just forwards it.

perhaps try https://github.com/SVModular/DrumKit ?

tag and changes are showing up here: https://github.com/SVModular/DrumKit/tree/v1.1.4

**Comment by cschol** [comment]
Got it. I needed to update the URL of the submodule to point to the new repo.

**Comment by JerrySievert** [comment]
DrumKit has been updated to v2.0.0:

repo: https://github.com/SVModuklar/DrumKit
tag: v2.0.0

build instructions:

$ git submodule init
$ git submodule update
$ make

**Comment by cschol** [comment]
References to fonts stored across frames: https://github.com/SVModular/DrumKit/issues/15

**Comment by JerrySievert** [comment]
update pushed, same tag.

thanks!

**Comment by JerrySievert** [comment]
DrumKit has been updated to v2.0.1:

repo: https://github.com/SVModuklar/DrumKit
tag: v2.0.1

build instructions:

$ git submodule init
$ git submodule update
$ make

**Comment by JerrySievert** [comment]
is this no longer the way for updates to the library?  if not, please let me know what the new procedure is.

**Comment by cschol** [comment]
It is. Integrator was on vacation.

**Comment by JerrySievert** [comment]
thanks much!
