### ISSUE TITLE
Sculpt-O-Sound

### ISSUE THREAD

**Issue by josbouten** [VCVRack/library#515]
plugin name: Vocode-O-Matic
slug name: Sculpt-O-Sound_-_Vocode-O-Matic
version: 0.6.0
repository: https://github.com/josbouten/Sculpt-O-Sound
email address: josbouten@gmail.com

**Comment by AndrewBelt** [comment]
Kind of an unusual slug. Would `Sculpt-O-Sound` be better? What if you decided to add other modules to the plugin?

**Comment by josbouten** [comment]
Hi,

Did I misunderstand the meaning of slug?

Sculpt-O-Sound is meant as a ‘brand' name for several plugins.

Vocode-O-Matic is the first plugin.


Best regards,

Jos

**Comment by AndrewBelt** [comment]
Yes, that's how to do it. However, for open-source plugins it's easier to combine multiple modules into a single plugin so we don't have to manage several plugins containing only a single module. Some developers (e.g. https://vcvrack.com/plugins.html#Martin%20Lueders) have multiple plugins because they are sold as different units, or the collection of modules are different enough to make sense when combined in separate plugins.

**Comment by josbouten** [comment]
Ok, then I think it is best to follow your suggestion and change the slug to Sculpt-O-Sound since for the moment I’m not planning to write separate plugins but are more likely to add single modules to the existing one.

I will change the slug in the Makefile on GitHub presently.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by cschol** [comment]
From #542:

plugin name: Vocode-O-Matic
slug name: Sculpt-O-Sound
version: 0.6.04
repository: https://github.com/josbouten/Sculpt-O-Sound
email address: josbouten@gmail.com
commit hash: 66d78a4..387e01a

This is an update with bug fixes and some added functionality.

**Comment by josbouten** [comment]
When will the updated version be available in Rack? On the website it still says 'build updated' 5 months ago.

**Comment by josbouten** [comment]
plugin name: Vocode-O-Matic
slug name: Sculpt-O-Sound
version: 0.6.05
repository: https://github.com/josbouten/Sculpt-O-Sound
email address: josbouten@gmail.com
commit hash: 14b5689..59b124a

This is an update

**Comment by cschol** [comment]
When I have had time to review it and Andrew updates the build. Will probably be a few days.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by josbouten** [comment]
Could you point me to some example code / has anyone done this in one of the open source modules?

**Comment by josbouten** [comment]
plugin name: Vocode-O-Matic
slug name: Sculpt-O-Sound
version: 0.6.4
repository: https://github.com/josbouten/Sculpt-O-Sound
email address: josbouten@gmail.com
commit hash: 10a2e43..5b64cf2

This is an update where I've added:
- text to the front panel
- mute of output channels
- trigger inputs to shift the filter matrix L or R
- storing internal state in json settings

**Comment by josbouten** [comment]
plugin name: Vocode-O-Matic
slug name: Sculpt-O-Sound
version: 0.6.4
repository: https://github.com/josbouten/Sculpt-O-Sound
email address: josbouten@gmail.com
commit hash: c63b896..6f706c3

Added a new example file + screendump

**Comment by AndrewBelt** [comment]
Updated build

**Comment by josbouten** [comment]
plugin name: Vocode-O-Matic
slug name: Sculpt-O-Sound
version: 0.7
repository: https://github.com/josbouten/Sculpt-O-Sound
email address: josbouten@gmail.com
commit hash: 7830ec7..f2b727f

This updates the plugin to VCV-Rack 1.x (from 0.6.4).
- Added tooltips. 
- Resolved a filter initialisation bug.

**Comment by cschol** [comment]
`plugin.json` issues: https://github.com/josbouten/Sculpt-O-Sound/issues/7

**Comment by josbouten** [comment]
plugin name: Vocode-O-Matic
slug name: Sculpt-O-Sound
version: 1.0.0
repository: https://github.com/josbouten/Sculpt-O-Sound
email address: josbouten@gmail.com
commit hash: f2b727f..43e1c6a

This updates the plugin to VCV-Rack 1.x (from 0.6.4).
- changed license identifier
- changed version number to 1.0.0
- code cleanup
- added some comments

**Comment by josbouten** [comment]
plugin name: Vocode-O-Matic
slug name: Sculpt-O-Sound
version: 1.0.1
repository: https://github.com/josbouten/Sculpt-O-Sound
email address: josbouten@gmail.com
commit hash: e37817a..f657911

This updates the plugin to v1.0.1

- changed tags
- fixed bug in setting led brightness
- updated example patch

**Comment by josbouten** [comment]
I'm not sure the discussion we had about the slug (have a look at the start of this thread) lead to the result I thought it would have. And I must admit I only just discovered this. I build a vocoder called Vocode-O-Matic and chose as a slug Sculpt-O-Sound. However, in the library I do not find the plugin under Sculpt-O-Sound, but under Vocode-O-Matic. I compares my slug.json with the one from mscHack and I think the slug name and module names are in accordance what I found with mscHack, however I do not see this reflected in the plugin name in the vcvrack library. Can you please enlighten me?

**Comment by josbouten** [comment]
I'm not sure the discussion we had about the slug (have a look at the start of this thread) lead to the result I thought it would have. And I must admit I only just discovered this. I build a vocoder called Vocode-O-Matic and chose as a slug Sculpt-O-Sound. However, in the library I do not find the plugin under Sculpt-O-Sound, but under Vocode-O-Matic. I compares my slug.json with the one from mscHack and I think the slug name and module names are in accordance with what I found with mscHack, however I do not see this reflected in the plugin name in the vcvrack library. Can you please enlighten me? I'm planning on adding more modules, so the name Vocode-O-Matic would not be appropriate for the set as a whole.

**Comment by AndrewBelt** [comment]
Looking at https://github.com/josbouten/Sculpt-O-Sound/blob/v0.6_to_v1.1/plugin.json, your plugin slug is `Sculpt-O-Sound`, which contains one module with a module slug of `Vocode_O_Matic`. This is fine. If you wish to add more modules to your plugin, simply pick a new module slug and add it to the `"modules"` list.

Your plugin *name* is "Vocode-O-Matic", which should probably be changed to "Sculpt-O-Sound", especially if you add more modules to your plugin. Slugs cannot be changed, but names definitely can, so simply change its name and release an update here.

**Comment by josbouten** [comment]
plugin name: Vocode-O-Matic_XL
slug name: Sculpt-O-Sound
version: 1.1.0
repository: https://github.com/josbouten/Sculpt-O-Sound
email address: josbouten@gmail.com
commit hash: 9695b08..b75e094
This updates the plugin to 1.1.0 and adds an XL-version of the vocoder module
- added sliders for panning
- added sliders for modulator level
- added sliders for envelope attack and release time

**Comment by josbouten** [comment]
In the library the module looks different from what it looks when I load it in Rack. The vocoder buttons are shown all as not pressed, but at startup the vocoder ( both Vocode-O-Matic and Vocode-O-Matic-XL ) will show a pattern of buttons that are pressed ( in linear mode a line of buttons are pressed from the bottom left to the top right of the matrix ). On github you can find examples like this one: 

![Vocode-O-Matix-XL in log mode](https://github.com/josbouten/Sculpt-O-Sound/raw/master/doc/Vocode-O-Matic-XL_v1.1.1.png)


Can the pictures in the library be made so that they will show the buttons pressed?

**Comment by cschol** [comment]
I am not sure. @AndrewBelt ?

**Comment by AndrewBelt** [comment]
The screenshots generated by `./Rack -t <zoom>` should be identical to the module displayed in the Module Browser, which is just your `ModuleWidget` with a NULL `Module`.

**Comment by josbouten** [comment]
I'm afraid I don't understand what you are saying. What would the effect of a NULL module be? And what am I supposed to substitute for ?zoom? 

What strikes me as odd is that all sliders are in the up most position. They are not initialised like that.

**Comment by josbouten** [comment]
Anyway, in the doc dir of the repository there are 2 pictures, one of Vocode-O-Matic and one of Vocode-O-Matic-XL. Could these be used?

**Comment by josbouten** [comment]
I think I should rephrase that. If I make a screendump that shows only the module (after initialization), could that be used instead of the probably automatically (but in this case inadequately) generated image? One could choose a default name for a picture taken in such a way. E.g. module_name_-_screendump.png or something like that so that it can be added automatically to the library? @AndrewBelt ?

**Comment by AndrewBelt** [comment]
No, all PNG screenshots in the VCV Library are generated with `./Rack -t 2`, which should be identical to its appearance in the Module Browser. If this is not the case, open a Rack bug report.
If you don't like the appearance of your module in the Module Browser, fix it on your end. If you need assistance, https://community.vcvrack.com/c/development is the best resource.

**Comment by josbouten** [comment]
Update plugin to V2
Location: https://github.com/josbouten/Sculpt-O-Sound
Version: 2.1.0
Commit Hash: ab493b8823b889f5e1998c1ccc07dcb5317557dd
