### ISSUE TITLE
Does anyone have a working travis yaml config for their plugin ?

### ISSUE THREAD

**Issue by JTriggerFish** [VCVRack/library#519]
I'd like to have an automated build ( at least for linux ) that checks out the vcv rack repo then my repo to the folder and then builds it.
Wondering if someone has already done that ?

**Comment by cschol** [comment]
I don't have one. I would ask in the VCVRack Official Facebook group. A lot of developers are in that group.

**Comment by AndrewBelt** [comment]
`ls repos/*/.travis.yml` gives ErraticInstruments, Southpole-parasites, and Southpole

**Comment by JTriggerFish** [comment]
Awesome, thank you!

**Comment by JTriggerFish** [comment]
I had issues with those configs but with a bit of work my config now builds fine on linux and osx, for those that may be interested:
https://github.com/JTriggerFish/TriggerFish-VCV/blob/master/.travis.yml

**Comment by wapiflapi** [comment]
Adding mine as I had some issues with what I could find on the internet as well. https://github.com/wapiflapi/admiral/blob/v1.0/.travis.yml
