### ISSUE TITLE
NocturnalEncoder

### ISSUE THREAD

**Issue by djpeterso23662** [VCVRack/library#521]
Initial public release of NocturnalEncoder plugin.  

Thanks very much for your help!

David Peterson

name: Nocturnal Encoder,
author: David Peterson,
license: BSD-3-Clause,
manualUrl: https://github.com/djpeterso23662/NocturnalEncoder/blob/master/README.md,
sourceUrl: https://github.com/djpeterso23662/NocturnalEncoder,
latestVersion: 0.6.1,
status: available

**Comment by cschol** [comment]
One nitpick: You should use `TOSTRING(SLUG)` in your `NocturnalEncoder.cpp` to pull the slug from the `Makefile` definition:

```
p->slug = "NocturnalEncoder";
```
becomes
```
p->slug = TOSTRING(SLUG);
```
That way there is only 1 definition of the slug.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by djpeterso23662** [comment]
Version 1.0.0 release of NocturnalEncoder plugin.
Commit 1e4cc02724746d4dc337c72f9a0d6a142350759b

Thanks very much for your help!

David Peterson
https://github.com/djpeterso23662/NocturnalEncoder

**Comment by cschol** [comment]
@djpeterso23662 Dave, can you check the license, please? It says "proprietary", but this is an open source plugin? Thanks.

**Comment by djpeterso23662** [comment]
Commit 5421ff57c0170705440b3b8f542e2f676ff60dfe

Thanks, @cschol, you are correct.  It is BSD 3-clause.  I corrected plugin.json.  Thanks for your help!

David Peterson
https://github.com/djpeterso23662/NocturnalEncoder

**Comment by djpeterso23662** [comment]
Version 2.0.0 release of NocturnalEncoder plugin.
Commit 7008233b9990fa8bc2749857cdb76260313fe7c8

Thanks very much for your help, @cschol and friends!

David Peterson
https://github.com/djpeterso23662/NocturnalEncoder
