### ISSUE TITLE
ModularFungi

### ISSUE THREAD

**Issue by david-c14** [VCVRack/library#523]
First plugin manager release

Thank you.

Slug: ModularFungi
Version: 0.6.2
Source repository: https://github.com/david-c14/ModularFungi.git 
Commit: 7a8489871c265f90daf791ea65989e12dffc66a7 
Tag: v0.6.2 
License: BSD-3 
Author: Omri Cohen 
Website: https://github.com/david-c14/ModularFungi
Manual: https://github.com/david-c14/ModularFungi/blob/master/README.md
DonateURL: https://paypal.me/omricohencomposer

**Comment by AndrewBelt** [comment]
Updated build

**Comment by cschol** [comment]
@AndrewBelt FYI, I don't see the updated builds in the plugin manager (no commit in repo either).

**Comment by AndrewBelt** [comment]
@cschol My mistake, fixed.

**Comment by david-c14** [comment]
I am migrating this plugin to v1. I do not currently require any help. Thank you

**Comment by david-c14** [comment]
I have ported this to v1.

Please can this plugin be built for v1

repo:   https://github.com/david-c14/ModularFungi
tag: v1.0.0.
commit: https://github.com/david-c14/ModularFungi/commit/a70be4b875ac19dbac8a11b970ddf50522ade634


Thank you

**Comment by cschol** [comment]
`plugin.json` issues: https://github.com/david-c14/ModularFungi/issues/6

**Comment by david-c14** [comment]
Changing the slugs in the manifest meant that they didn't match the names in createModel, so the plugin wouldn't load.

I've checked it in again:

https://github.com/david-c14/ModularFungi/commit/08b29723a82e374f1c6cf9c2a0340539e094d910

Sorry.

**Comment by cschol** [comment]
Argh. I should have caught that. I will add a check of the CPP slugs to the validation script.

**Comment by AndrewBelt** [comment]
Plugin build has been removed. Fix to re-add:
```
[0.038 warn src/plugin.cpp:147] Could not load plugin /home/vortico/.Rack/plugins-v1/ModularFungi: Manifest contains module Blank1HP but it is not defined in the plugin
```

**Comment by david-c14** [comment]
Now, I'm really confused. I changed the calls to createModel  to use the same string that's in the json. Are you saying that's not compiling/running?

**Comment by AndrewBelt** [comment]
Just waiting on @cschol  now

**Comment by cschol** [comment]
Done.

**Comment by david-c14** [comment]
Updated

repo: https://github.com/david-c14/ModularFungi
tag: v1.0.1
commit: 9ad3b014175f97a294094e13dbd017e3ef951cc1

Thank you

**Comment by david-c14** [comment]
Updated

repo: https://github.com/david-c14/ModularFungi
tag: v1.1.0
commit: 2d7f44dea393656267bcf38db1321fdb2bdb533c

Thank you

**Comment by david-c14** [comment]
Updated

repo: https://github.com/david-c14/ModularFungi
tag: v1.1.1
commit: 6703e80064ef671570c4326b5f31e0e5d5afb774

Thank you

**Comment by david-c14** [comment]
Sorry another update (bug fix)

repo: https://github.com/david-c14/ModularFungi
tag: v1.1.2
commit: bd556880dc4ff9d1c32688bafa3d56b1c56c444e

**Comment by curlymorphic** [comment]
Another update, improvements to the scope

repo: https://github.com/david-c14/ModularFungi
tag 1.1.3
commit 65155b1435c75956618b1a660543996d8ec04588

If there is a concern as to why I am submitting and not @david-c14  please see https://github.com/david-c14/ModularFungi/pull/26

**Comment by curlymorphic** [comment]
Another update, improvements to the scope

repo: https://github.com/david-c14/ModularFungi
tag 1.1.4
commit f64ab899a7fe3b192fdcb8e359244187be7eb880

Thank you.

**Comment by david-c14** [comment]
For the immediate future we have decided that we would prefer that this module is *not* ported to v2. Thank you.

https://community.vcvrack.com/t/modular-fungi-in-v2/14369

**Comment by david-c14** [comment]
Omri has expressed a wish that this plugin is NOT migrated to v2 for the time being
