### ISSUE TITLE
STS

### ISSUE THREAD

**Issue by SmallTownSound** [VCVRack/library#524]
First plugin manager release

Thank you.

Slug: STS
Version: 0.6.0.1
Source repository: https://github.com/SmallTownSound/STS
Commit: edea8d0bb50c8e823f602bb2e2ec3f86faa2533b
License: BSD-3
Author: Don Turnock

**Comment by cschol** [comment]
Your plugin has been integrated and will be included in the next Plugin Manager update. This might take a few days for Andrew to pick up the changes. If you have a new version of your plugin available, please **reuse this issue**. We will open the issue back up if a new version is ready to be integrated. Thank you for providing your plugin!

**Comment by AndrewBelt** [comment]
Updated build

**Comment by AndrewBelt** [comment]
Updated build

**Comment by cschol** [comment]
@SmallTownSound Use this top-level issue for updates. Thanks!

```
Updated build
commit 3ffc360f727b802038fd019ea34de3114842802b
0.6.0.2
```

**Comment by AndrewBelt** [comment]
Updated build

**Comment by SmallTownSound** [comment]
STS 1.0.0 port
https://github.com/SmallTownSound/STS/
095ac5d

**Comment by cschol** [comment]
`plugin.json` updates required: https://github.com/SmallTownSound/STS/issues/7

**Comment by SmallTownSound** [comment]
plugin.json updated

**Comment by SmallTownSound** [comment]
since still in progress, small updates

version : 1.0.1
branch : V1
Latest commit 9e7de39

**Comment by cschol** [comment]
One more request: please fill in an `authorUrl` in the manifest. Set it to the GitHub repo's README if you don't have another website to link to. Thanks!

Other than that it looks good.

**Comment by SmallTownSound** [comment]
Done

**Comment by cschol** [comment]
Transferred from #563:

STS V1.0.2 is ready for library
https://github.com/SmallTownSound/STS/
commit e634dff

**Comment by cschol** [comment]
Compile fails on Mac platform: https://github.com/SmallTownSound/STS/issues/11

**Comment by SmallTownSound** [comment]
Fixed, do a new pull

**Comment by SmallTownSound** [comment]
STS V1.0.3 is ready for library
https://github.com/SmallTownSound/STS/
commit b84a238b69819e7dc865629e506ea39429d51d9b

**Comment by SmallTownSound** [comment]
found small issue
new commit
commit 580a029c830928c19f9076143c8c3c7d05154c3a

**Comment by SmallTownSound** [comment]
STS V1.0.4 is ready for library
https://github.com/SmallTownSound/STS/
commit/68b1aa8eb11c2e927634ee9c27aeca92d5b6fa18

**Comment by SmallTownSound** [comment]
Fixed plugin.json
new commit a44faf85e5d48d312101e80606bc8700dbeab251

**Comment by cschol** [comment]
Compile failure on Windows: https://github.com/SmallTownSound/STS/issues/16

**Comment by SmallTownSound** [comment]
oops...   Fixed

https://github.com/SmallTownSound/STS/commit/0caf260a10bfdcaaecf69dc5d820c4605e677a20

**Comment by SmallTownSound** [comment]
Version v1.1.1

https://github.com/SmallTownSound/STS

https://github.com/SmallTownSound/STS/commit/a6711dfaeb3826eea1788c919e4a0bbdf31599dd
thanks

**Comment by SmallTownSound** [comment]
Git currupted the json file.  Fixed

New commit

https://github.com/SmallTownSound/STS/commit/ddac7dd5311f84d047f8aab3fd3dee7a125433cd

**Comment by SmallTownSound** [comment]
More git screw ups....  
fixed  
https://github.com/SmallTownSound/STS/commit/e7974317844e5fc071281f0e55a96ee6b7f73d1b

**Comment by SmallTownSound** [comment]
ooops, wrong click...

**Comment by SmallTownSound** [comment]
Version v1.1.2

https://github.com/SmallTownSound/STS

https://github.com/SmallTownSound/STS/commit/433c96c5664b17f9398a0b15c688753c39b39d6b

thanks

**Comment by Coirt** [comment]
Is this no longer available? No source or repo available, looks like all the links have been deleted https://github.com/SmallTownSound/STS/tree/433c96c5664b17f9398a0b15c688753c39b39d6b

**Comment by AndrewBelt** [comment]
@SmallTownSound has requested to no longer provide the source of this plugin. Since it was licensed under GPLv3, anyone who has a copy of v1.1.2 or earlier may continue distributing it, but further updates will use a closed-source freeware license and will go through VCV directly.

**Comment by fractalgee** [comment]
but this way no bugs can be reported as github repro is completely gone
too, so no issues thread. How to report them then? Given no contact detail
either to be found.....  Oddy is a crashy beast in 1.6.2b, which is
sad...., but no way to report it which is a bit weird....

**Comment by AndrewBelt** [comment]
@fractalgee The author's email address is in the plugin manifest.

**Comment by fractalgee** [comment]
Aha, that was the one place I hadn't checked yet @Andrew Belt
<contact@vcvrack.com>  Thanks, bug email being composed....

**Comment by abcsds** [comment]
If the repository of the plugin has been made private. Shouldn't the subrepo under `repos/STS' be removed?

**Comment by AndrewBelt** [comment]
@abcsds Sure, removed in ae3ac27
