### ISSUE TITLE
Changelog for plugins

### ISSUE THREAD

**Issue by cschol** [VCVRack/library#529]
I was just updating plugins and thought it would be nice to see what changed in this current release that was just updated or installed. Some kind of a "What's new in this release", per plugin.

Here is an idea to discuss:
- Include an **optional** `changelog.json` in the plugin repository, for example
```
{
	"slug": "myPlugin",
	"changelog": {
		"1.0.0": "- Added new module Foo\n - Fixed crash in module Bar",
		"1.0.1": "- Fixed panel layout in module Baz"
	}
}
```

- After all plugins are downloaded generate a popup with the combined changelog for all updated/installed plugins from information the `changelog.json` files for the downloaded version. Only include plugins that have a `changelog.json` file. Maybe this could be included as a scrollable text field in the current popup that ask the user to restart Rack.

**Comment by AndrewBelt** [comment]
I don't think changelog content should go in the JSON itself, but we should definitely have a URL to access a CHANGELOG file. Users can click this if they want to see the changelog, and the developer can serve it in any format they want.

The only issue is that some developers may want to distribute CHANGELOGs along with the package itself. A URL couldn't access that.

**Comment by cschol** [comment]
If the CHANGELOG was part of the package, could the URL point to the location relative to the plugin's directory? 

If it was a structured file format, Rack could extract the relevant information from the file and display it. For example: Markdown with [markdown++](https://github.com/goldsborough/markdownpp). This is not intended to be an all encompassing rendering solution for Markdown, but a simple way to convey what changed. That's why I proposed to include in a **a** JSON file, e.g. `changelog.json`. Rack already supports handling it.

Personally, I like the idea to have the CHANGELOG be part of the package. This keeps the change information and the package content in sync.

**Comment by Coirt** [comment]
In v1 context menu, how about as an example. 
`"bugReport": "https://github.com/Coirt/Bark/issues/new",`

Which would take users straight a new issue tracker.

**Comment by AndrewBelt** [comment]
How would either of those work for, say VCV Pulse Matrix or Vult Modules?

**Comment by Coirt** [comment]
I see what you're saying but it would just open a link anyway. The majority of plugins being on GitHub rely on the issue tracker. It would just open a link in a default browser, if there was a dedicated menu item already in the context menu (>) it would make it easier for users to report a bug to the developer or view a changelog without the need to leave Rack to decide to do those steps. I know there is a way to add custom context menu items, which I'm currently looking into doing myself, it would make it easier for others is all.

**Comment by AndrewBelt** [comment]
Okay, `"changelogUrl"` is now a valid property in `plugin.json` for Rack v1.
