### ISSUE TITLE
EH_modules

### ISSUE THREAD

**Issue by eh2k** [VCVRack/library#533]
Hi,
I would like to add my Module to the public VCV Plugins.

URL: https://github.com/eh2k/vcvrack-fv1-emu
License: GPL
Minifest: https://github.com/eh2k/vcvrack-fv1-emu/blob/master/plugin.json

Thanks!

**Comment by cschol** [comment]
Build was updated by Andrew. Your plugin is now available.

**Comment by cschol** [comment]
@AndrewBelt FYI, the official macOS build always crashes on my macOS system: https://github.com/eh2k/fv1-emu/issues/1

**Comment by eh2k** [comment]
@cschol, the missing fx folder, and some file-handling cases (missing files/directory) are fixed in the master (Commit Hash fe916dc14f487bd5c04dc349522e694a898d4ad3) now...

I have testet it only on linux so far, hope it is working on Windows, macOS also...
Sorry and Thanks for the additional efford...

**Comment by AndrewBelt** [comment]
You'll need to bump the version number to distribute a new package version.

**Comment by cschol** [comment]
Thank you for fixing the plugin. I tested on macOS and it works now correctly as far as I can tell.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by eh2k** [comment]
The slug is chaned back to "EH_modules".

New Version: 1.0.0
Commit Hash: f3c1b74f21be5a4904d265bc75ce1065b6f6e6de

Thanks!

**Comment by AndrewBelt** [comment]
Looks good. As you figured out, you can change the name at will, but the slug must stay the same.

**Comment by cschol** [comment]
Closing as this appeared in the updates.

**Comment by eh2k** [comment]
New Version 1.0.1
Commit Hash: dda5029d988707796deb39f7a19345dfbbcc316c

Thanks you!

**Comment by eh2k** [comment]
New Version 1.0.2
Commit Hash: ec7377f2aeb517e02dc9216247e23c45eb3cae5d

Thank you!

**Comment by cschol** [comment]
Version update needed: https://github.com/eh2k/fv1-emu/issues/10

**Comment by eh2k** [comment]
New Version 1.0.2
Commit Hash: 589e2176178a785dd0859c42cadc78b7e3b9a028  (plugin.json version fixed)

**Comment by eh2k** [comment]
New Version 1.0.3
Commit Hash: 64eb8e0aa432f9436ac8ccff52b28c16fd738ab0

Thank you!

**Comment by eh2k** [comment]
Hi, me again:

Have a new Version 1.0.4 (fixed: https://github.com/eh2k/fv1-emu/issues/11)
Commit Hash: fc16afd2259a0873e9d53cba47717ace749e8fe8

Thanks!

**Comment by eh2k** [comment]
New Version 1.0.5
Commit Hash: 37eaa7d6e4321955b334f71405415c004e49c9c9

Thanks!

**Comment by eh2k** [comment]
New Version 2.05
Url: https://github.com/eh2k/vcvrack-fv1-emu.git
Commit Hash: 53c958c71b2f814f38174f153056190160adb84b

Thanks
