### ISSUE TITLE
Skylights, SkJack

### ISSUE THREAD

**Issue by Skrylar** [VCVRack/library#536]
Manifest for SkJack (think I got this right):
```
{
    "name": "SkJack",
    "author": "Skrylar",
    "license": "BSD",
    "authorEmail": "joshua.cearley@gmail.com",
    "sourceUrl": "https://github.com/Skrylar/skjack-vcv",
    "latestVersion": "0.6.6"
}
```
And Skylights:
```
{
    "name": "Skylights",
    "author": "Skrylar",
    "license": "BSD",
    "authorEmail": "joshua.cearley@gmail.com",
    "sourceUrl": "https://github.com/Skrylar/skylights-vcv",
    "latestVersion": "0.6.2"
}
```

Cheers.

**Comment by cschol** [comment]
@Skrylar Is the name in the `Skylights` manifest snippet correct? It is also "SkJACK".

**Comment by Skrylar** [comment]
@cschol Fixed the slugs :cry:

**Comment by cschol** [comment]
For **Skylights**:
-  One suggestion: please add the appropriate tags to your modules. Right now, they are all tagged as `EXTERNAL_TAG`, which I take to generally mean "communicating with external equipment", e.g. via OSC. See [include/tags.hpp](https://github.com/VCVRack/Rack/blob/v0.6/include/tags.hpp) for all available tags.

Let me know if you want to update this now, or just go with the current tags and update this later. It is ready for integration otherwise.

For **SkJack**:
- The `JACK` dependency is likely going to be a problem. Generally, you cannot assume that the build system has **any** dependencies installed and it won't install **any** additional packages to support your plugin build. Therefore, the plugin build must be entirely self-contained, i.e. provide **all** build dependencies, `JACK` in this case, itself. If anything needs to be "made" pre-build there is the `make dep` target, which is executed when available. See [Fundamental](https://github.com/VCVRack/Fundamental) for an example on how to use `make dep`.

- It looks like this plugin is not supported on Windows. @AndrewBelt how do you exclude a platform from being built by the build system?

**Comment by AndrewBelt** [comment]
>how do you exclude a platform from being built by the build system?

You can't, that would frustrate people. Better to make builds and distribute yourself.
I think JACK can be linked statically on all OS's, is that right? See https://github.com/VCVRack/Fundamental/blob/v0.6/Makefile#L10-L17 for an example of compiling libraries during `make dep`.

**Comment by Skrylar** [comment]
You’re right about the tags. I’ll fiddle with those tonight.

With JACK:

I don’t assume there is a library anywhere. Originally I did, but macOS and
Windows weren’t compatible with it. What I do is use dlsym and
GetProcAddress at runtime, so we detect the presence of a JACK client on
all three platforms and without one we simply no-op the DSP code. We can
assume those calls are present because they are part of either WinAPI and
Rack always has dl to load plugins itself. This technique seems to be
holding up, since volunteers in the forums have sent in test builds and
haven’t reported issues.

I can do some double checks to make everyone more comfortable, but we
do/are supposed to build on Windows. There shouldn’t be any external
link/include requirements at build time.

**Comment by AndrewBelt** [comment]
Oh yeah, as long as it doesn't crash Rack when JACK is not installed on Win/Mac/Lin, you're fine.

**Comment by Skrylar** [comment]
@dizzisound I already fixed this particular bug, I just forgot to push it from the windows machine :cry: 

SkJACK should compile now (pushed as 0.6.6)

**Comment by dizzisound** [comment]
@Skrylar Me silly, I put the `-Isrc` flag in the CFLAGS macro, so it didn't work with C++ compiler... :-D 
Never mind, I just git-pulled and everything works fine now, I can build without other issues or workarounds and no external dependencies. 
Nice! I like the new graphics by David Rodriguez too. 
Should you implement Jack MiDI support in the future (I noted that in your Discourse / Github timeline), it will be awesome! ...some MuseScore sheets search for VCO friends here :-)

**Comment by Skrylar** [comment]
@cschol Tags have been fixed and released as 0.6.2. ALAN itself is now a Sequencer, the expanders are Utilities (there is no tag for expansion modules.) No longer does the CV tuner think it's an I/O port :wink: 

JACK remains marked as an external because, well, it is.

**Comment by Skrylar** [comment]
Is still waiting on something? :confused:

**Comment by cschol** [comment]
Just waiting for me to have time to review and integrate. This is done now and as soon as Andrew updates the builds your plugin will be available in the Plugin Manager. Thank you for your submission!

**Comment by AndrewBelt** [comment]
Update build

**Comment by Skrylar** [comment]
Skylights has a 0.6.3 update, fixing some memory holes in the vactrol mixer.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by Skrylar** [comment]
0.6.4 :tada:

**Comment by Skrylar** [comment]
0.6.5 pushed with audible bug fixes :tada:

**Comment by Skrylar** [comment]
SkJACK has 0.6.7 out :tada:

**Comment by AndrewBelt** [comment]
Updated build

**Comment by Skrylar** [comment]
SkJACK updated to 0.6.8 (fixes weird performance issues) :tada:

**Comment by cschol** [comment]
Cross-compilation for Windows on Linux failed:

```
x86_64-w64-mingw32-g++ -o plugin.dll build/src/hashids.cc.o build/src/jack-audio-module.cc.o build/src/skjack.cc.o build/src/jack-audio-module-widget.cc.o build/src/jaq.cc.o  -shared -L/home/cschol/src/Rack-SDK/Rack-SDK -lRack
build/src/jaq.cc.o: In function `jaq::port::register_audio(jaq::client&, char const*, unsigned long)':
/home/cschol/src/library/repos/SkJack/src/jaq.cc:43: undefined reference to `jack_get_client_name'
build/src/jaq.cc.o: In function `jaq::port::rename(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/cschol/src/library/repos/SkJack/src/jaq.cc:86: undefined reference to `jack_get_client_name'
collect2: error: ld returned 1 exit status
/home/cschol/src/Rack-SDK/Rack-SDK/compile.mk:55: recipe for target 'plugin.dll' failed
make: *** [plugin.dll] Error 1
```

Can you take a look please? Thanks.

**Comment by dizzisound** [comment]
@Skrylar It appears that adding `JackWeakAPI.c` (from [Jack2 repo](https://github.com/jackaudio/jack2/tree/develop/common)) to the plugin _src_ folder (and to Makefile SOURCES inside a `#ifdef ARCH_WIN` clause) can solve the build issue, without breaking the plugin (tested on Win 8.1 x64).

**Comment by cschol** [comment]
@Skrylar Do you have any update for this plugin or can we close this for now?

**Comment by cschol** [comment]
Closing until further update occur.

**Comment by Skrylar** [comment]
Skylights should be working on the v1 API now (via the `master` branch.)

**Comment by cschol** [comment]
Skylights - Invalid license ID: https://github.com/Skrylar/skylights-vcv/issues/15

**Comment by Skrylar** [comment]
fixed

**Comment by Skrylar** [comment]
skjack is v1 now

**Comment by Skrylar** [comment]
Updated Skylights to 1.0.1

**Comment by Skrylar** [comment]
updaed to 1.0.2
