### ISSUE TITLE
LabSeven

### ISSUE THREAD

**Issue by LabSevenDevVCVRack** [VCVRack/library#537]
Planning to release free + open source modules, starting with the VCO-3340 oscillator :-)

**Comment by AndrewBelt** [comment]
Just list the following information in a comment here. https://github.com/VCVRack/library#manifest-files Comment when ready and I'll reopen.

**Comment by LabSevenDevVCVRack** [comment]
{
  "name": "LabSeven",
  "author": "Gernot Wurst",
  "authorEmail": "highcarbschwabe@prospectum.com",
  "license": "???",
  "pluginUrl": "https://labseven.prospectum.com/",
  "manualUrl": "https://labseven.prospectum.com/",
  "sourceUrl": "https://github.com/LabSevenDevVCVRack/LabSeven_VCVRack_modules.git",
  "donateUrl": "https://labseven.prospectum.com/",
  "latestVersion": "0.6.1",
  "status": "available"
}

I am not sure which license to use. I am leaning towards "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International Public License" but I saw that some module developers have released their work free&open source but under a proprietary license...

**Comment by LabSevenDevVCVRack** [comment]
{
  "name": "LabSeven",
  "author": "Gernot Wurst",
  "authorEmail": "highcarbschwabe@prospectum.com",
  "license": "???",
  "pluginUrl": "labseven.prospectum.com",
  "manualUrl": "labseven.prospectum.com",
  "sourceUrl": "https://github.com/LabSevenDevVCVRack/LabSeven_VCVRack_modules.git",
  "donateUrl": "https://paypal.me/labseven",
  "latestVersion": "0.6.1",
  "status": "available"
}

**Comment by LabSevenDevVCVRack** [comment]
Ok, I think I'll take

"license": "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International Public License"

I think the manifest is complete now. Correct?

**Comment by LabSevenDevVCVRack** [comment]
Ok, I did the git push. The current version is 0.6.1, the commit hash is 
3a4482d4ecbafeb4ae950daaf2b964f271c76cfd

What about the builds and inclusion in the plugin manager? Anything else I have to do? Thanks!

**Comment by cschol** [comment]
I will review the code and integrate it in the `library` repository if everything looks good. After that, the next time Andrew updates the builds your plugin will appear in the plugin manager for all supported platforms (GNU/Linux, Mac, Windows). You don't have to do anything. We take it from here. I will let you know in this issue when the integration has been completed and Andrew will comment when the build has been updated and the plugin is available.

**Comment by LabSevenDevVCVRack** [comment]
Awesome, thanks!

**Comment by AndrewBelt** [comment]
Update build

**Comment by cschol** [comment]
@LabSevenDevVCVRack I was looking at your code and saw a 32 MB source file with what looks like noise samples? Can you explain the purpose of that vs generating those samples on the fly? Thanks!

**Comment by LabSevenDevVCVRack** [comment]
This is indeed a noise sample (coloured noise). Using that eliminates the need to need  for calculation/filtering (performance improvement) + the sound is as close to the real thing as possible. In binary form, the sample is ~4.5MB. Which, compared to the >25GB for my latest virtual organ, is almost nothing and therefore should (I hope!) not cause trouble. This is simply the most efficient and best sounding way to implement the noise source.

**Comment by AndrewBelt** [comment]
Can you precomute it in `init()`?

**Comment by LabSevenDevVCVRack** [comment]
I think so. In that case I would analyze the spectrum of the noise, create a filter from that and apply the filter to white noise by partitioned convolution. But that is quite a bit of extra code + uses fftw and quite a bit of work. As a result, I would end up with a similar sample. Bu why? What is the benefit?

**Comment by AndrewBelt** [comment]
Would save like 100-500 GB of bandwidth.

**Comment by LabSevenDevVCVRack** [comment]
We replace one sample by another other one and save bandwidth that way? How does that work? Sorry if that is a stupid question, I am rather new to the realtime stuff...

**Comment by AndrewBelt** [comment]
Server bandwidth, not memory bandwidth...

**Comment by LabSevenDevVCVRack** [comment]
Ah ok, I see :-) Is it ok if I provide that as an update (right with the next version)? I will be very busy for a while.

**Comment by LabSevenDevVCVRack** [comment]
Oh, and I forgot that I would also need to loop it (=> reliable seamless loop detection algorithm required). Ideally multiple overlapping loops, played back in random order.

**Comment by AndrewBelt** [comment]
I'll wait until the update

**Comment by LabSevenDevVCVRack** [comment]
Ok, I will inform people that for now they need to build the plugin themselves. Maybe, since now the precalculation has become rather complex (and time consuming - especially since the module is free), I could alternatively try to turn the high quality filter into something that can be calculated in realtime (eliminating the need for loops, too). With PROSPECTUM, I avoid all shortcuts that decrease the quality of my final products, so I am not too happy. But maybe there is a good solution.

P.S.: Our PROSPECTUM server has unlimited bandwidth and I was told that -except in extreme cases- bandwidth is not any issue today. So I didn't consider using one rather small sample a problem. Sorry for that.

**Comment by AndrewBelt** [comment]
Looks like 4.5MB is fine. You should load the sample as a resource though instead of compiling into the binary.

**Comment by LabSevenDevVCVRack** [comment]
I can do that. What path do I need to use to load it (res/..... did not work when I tried)?

**Comment by cschol** [comment]
Example on how to access resources in `res` at runtime:
```
setPanel(SVG::load(assetPlugin(plugin, "res/Logistiker.svg")));
```

**Comment by LabSevenDevVCVRack** [comment]
Ok, I do it right away. Is it ok if I get back to you in ~1h and post the new hash code?

**Comment by cschol** [comment]
Take your time. I'll be checking in later today.

**Comment by LabSevenDevVCVRack** [comment]
Ok. Thanks!

**Comment by LabSevenDevVCVRack** [comment]
I have removed the .h file with the noise source, put the noise source class in the .h file with the rest of the VCO-3340 stuff, put the raw data in a pcm file in /res and updated the repository.
c3016ef383e762f069dfd1b38aa8e77ab8a947ec

**Comment by AndrewBelt** [comment]
Could you remove the file from git history as well? Google around, or use something like `git filter-branch --tree-filter 'rm -f file' HEAD`.

**Comment by cschol** [comment]
[Here](https://help.github.com/articles/removing-sensitive-data-from-a-repository/#purging-a-file-from-your-repositorys-history) is a reference for options to purge files from git repositories.

**Comment by LabSevenDevVCVRack** [comment]
Thanks!

**Comment by LabSevenDevVCVRack** [comment]
highcarbschwabe@psp-pc2:~/Dokumente/gernot/qtprojects/vcv_rack/temp/LabSeven_VCVRack_modules$ git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch LabSeven_3340_VCO_noise.h' --prune-empty --tag-name-filter cat -- --all
Rewrite c3016ef383e762f069dfd1b38aa8e77ab8a947ec (8/8) (1 seconds passed, remaining 0 predicted)    
WARNING: Ref 'refs/heads/master' is unchanged
WARNING: Ref 'refs/remotes/origin/master' is unchanged
WARNING: Ref 'refs/remotes/origin/master' is unchanged

**Comment by AndrewBelt** [comment]
You need to tell it where your file is: `src/`

**Comment by LabSevenDevVCVRack** [comment]
Ok, I guess it worked. When I clone the repository, the whole folder is now 21 MB while it was 54 MB before...

**Comment by LabSevenDevVCVRack** [comment]
I must admit that I have not used gut a lot before (but subversion)...

**Comment by LabSevenDevVCVRack** [comment]
Wait a minute, I still need to fix something...

**Comment by LabSevenDevVCVRack** [comment]
Ok, hope it is nice and clean now:
5fcd5c9d90ec9958711f4bbcfd18b608af3027fa

**Comment by cschol** [comment]
Thank you for your patience. Your plugin has been integrated in the `library` repository and the next time Andrew updates the builds it will be available in the Plugin Manager for all supported platforms.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by LabSevenDevVCVRack** [comment]
Thank YOU for your patience, too :-)

**Comment by LabSevenDevVCVRack** [comment]
Hi!

I have fixed a bug and made some minor improvements to the VCO-3340.
This is version 0.6.2 (it is also tagged):

c726c4d05f901be8a2c26a9c0b42c3dd66adf9ac

Thanks!

**Comment by AndrewBelt** [comment]
Updated build
