### ISSUE TITLE
MicMusic

### ISSUE THREAD

**Issue by very-cool-name** [VCVRack/library#539]
Hi! I would like to propose my module for addition to VCV Rack plugins.
https://github.com/very-cool-name/MicMusic-VCV
It now has simple distortion. Distortion cuts signal from below and above. Levels above and below can be adjusted using knobs or CVs.
I plan to extend my module in future. After distortion I would like to add scale plugin, which takes midi input and generate notes according to different scales and temperaments.

**Comment by cschol** [comment]
Please change the `VERSION` in the `Makefile` to **0.6.0** to indicate that this plugin is for version 0.6.x release of Rack. Any updates to the plugin would be 0.6.1, 0.6.2, etc. Thank you!

**Comment by very-cool-name** [comment]
That was fast reply - thank you. Done. For future reference - how do I find which version of Rack my plugin supports?

**Comment by cschol** [comment]
It supports whichever version you release against, but usually plugins only supported the latest available version via the Plugin Manager.

I also need the following information for the manifest to finish integration:

```
{
  "name": "MicMusic",
  "author": "",
  "license": "",
  "authorEmail": "",
  "manualUrl": "https://github.com/very-cool-name/MicMusic-VCV/blob/master/README.md",
  "sourceUrl": "https://github.com/very-cool-name/MicMusic-VCV.git",
  "pluginUrl": "https://github.com/very-cool-name/MicMusic-VCV/blob/master/README.md"
}
```

Author name, License type, and Author email are still to be provided.

**Comment by very-cool-name** [comment]
`
{
  "name": "MicMusic",
  "author": "Mike Maximov",
  "license": "MIT",
  "authorEmail": "vigorous.activity@gmail.com",
  "manualUrl": "https://github.com/very-cool-name/MicMusic-VCV/blob/master/README.md",
  "sourceUrl": "https://github.com/very-cool-name/MicMusic-VCV.git",
  "pluginUrl": "https://github.com/very-cool-name/MicMusic-VCV/blob/master/README.md"
}
`
I updated license to be copy of MIT.

**Comment by cschol** [comment]
Your plugin has been integrated in the repository and builds will be available for all supported platforms the next time Andrew performs an update. Please comment in **this** issue when a new version of your plugin is available and we will reopen it. Thank you for submitting your plugin!

**Comment by very-cool-name** [comment]
Thank you for support!

**Comment by AndrewBelt** [comment]
Updated build

**Comment by very-cool-name** [comment]
Hi! I've opened debug file on every module creation. I've fixed this in latest commit, please update.

**Comment by AndrewBelt** [comment]
Build updated

**Comment by very-cool-name** [comment]
Hi. Committed new plugin - adder. Please update module.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by very-cool-name** [comment]
Updated plugin per user request. Please update build.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by very-cool-name** [comment]
Hi! I've updated my plugins fro Rack V1. Please update build.

**Comment by cschol** [comment]
`plugin.json` issues: https://github.com/very-cool-name/MicMusic-VCV/issues/3

**Comment by very-cool-name** [comment]
Updated, expect it to work now.
