### ISSUE TITLE
Edge 

### ISSUE THREAD

**Issue by Edge-Modules** [VCVRack/library#540]
Hello :)

First, i would like to thank you for VCV of course but also WaveEdit wich is such a great tool !

Then,i would like my plugin to be distributed via the official VCV Rack Plugin Manager.

* **name**: Edge

* **version**: 0.6.3

* **source code repository**: https://github.com/Edge-Modules/Edge

{
"name": "Edge",
"author": "Barit Nicolas",
"authorEmail": "mayatito51@hotmail.com",
"license": "GNU GENERAL PUBLIC LICENSE",
"pluginUrl": "https://github.com/Edge-Modules/Edge",
"sourceUrl": "https://github.com/Edge-Modules/Edge.git",
"latestVersion": "0.6.3",
"status": "available"
}

Thank you!

**Comment by cschol** [comment]
Your plugin has been integrated in the Rack library of modules. The next time Andrew updates the builds, your plugin will be made available via the plugin manager for all supported platforms. When a new version of your plugin becomes available, please notify us in **this** issue. We will reopen it and process the changes. Thank you for submitting your plugin!

**Comment by Edge-Modules** [comment]
Nice ! Thank you ;)

**Comment by AndrewBelt** [comment]
Updated build

**Comment by Edge-Modules** [comment]
Hi,

Commited new update,

WCO -> add a sync input
K-ru5h -> add a trim and a mix inputs

    name: Edge

    version: 0.6.4

    source code repository: https://github.com/Edge-Modules/Edge

{
"name": "Edge",
"author": "Barit Nicolas",
"authorEmail": "mayatito51@hotmail.com",
"license": "GNU GENERAL PUBLIC LICENSE",
"pluginUrl": "https://github.com/Edge-Modules/Edge",
"sourceUrl": "https://github.com/Edge-Modules/Edge.git",
"donateUrl": "https://paypal.me/edgemodules",
"latestVersion": "0.6.4",
"status": "available"
}


Please update build ;)

Thank you!

**Comment by Edge-Modules** [comment]
Sorry, version updated in the makefile.

Thank you ;)

**Comment by AndrewBelt** [comment]
Updated build.

**Comment by Edge-Modules** [comment]
Hi,

Commited update 0.6.5
correcting a major Bug on both of my modules.

* **name**: Edge

* **version**: 0.6.5

* **source code repository**: https://github.com/Edge-Modules/Edge
{
"authorEmail": "edgemodules@gmail.com",
"donateUrl": "https://paypal.me/edgemodules",
"latestVersion": "0.6.5",
"status": "available"
}

Latest commit :      17cbb24 
( https://github.com/Edge-Modules/Edge/commit/17cbb24adec2a3a30c1b64c8d91bb1764160e992 )

Thank you!

**Comment by AndrewBelt** [comment]
Updated build

**Comment by Edge-Modules** [comment]
Hi  ;)
Can you please update my mail ( this was my personal mail ) and add the donateUrl.
{
"authorEmail": "edgemodules@gmail.com",
"donateUrl": "https://paypal.me/edgemodules",
}

Thank you !

**Comment by cschol** [comment]
Sorry, I missed that during yesterday's update and will correct it tonight.

**Comment by Edge-Modules** [comment]
No problem ! 
Thank you very much ;)

**Comment by Edge-Modules** [comment]
Hi,

Commited update 1.0.1

Compatibility for Rack V1
Polyphony X 16 on WCO + Optimisation

{
"name": "Edge",
"author": "Barit Nicolas",
"authorEmail": "mayatito51@hotmail.com",
"license": "GNU GENERAL PUBLIC LICENSE",
"pluginUrl": "https://github.com/Edge-Modules/Edge",
"sourceUrl": "https://github.com/Edge-Modules/Edge.git",
"donateUrl": "https://paypal.me/edgemodules",
"latestVersion": "1.0.1",
"status": "available"
}

Latest commit :  
[ 419661e ](https://github.com/Edge-Modules/Edge/commit/419661ea6cdc028f979e1c7bf33a43359da3e275)

Thank you!

**Comment by cschol** [comment]
Build failure on Mac platform (cross-compile): https://github.com/Edge-Modules/Edge/issues/10

**Comment by Edge-Modules** [comment]
Oops! Sorry for that.
Array initialisation corrected.
Latest commit :
[ 2a6ffe8](https://github.com/Edge-Modules/Edge/commit/2a6ffe80e65e37eb953388bbb883e94d62bf4728)

Thank you ;)

**Comment by cschol** [comment]
Invalid license ID in `plugin.json`: https://github.com/Edge-Modules/Edge/issues/11

**Comment by Edge-Modules** [comment]
Invalid license ID changed from
"GNU GENERAL PUBLIC LICENSE"
to
"GPL-3.0-or-later"

Latest commit :
[ 6f8bd44](https://github.com/Edge-Modules/Edge/commit/6f8bd44b82b055fe5b4aa97bc969cd870538c4c9)

Thank you.

**Comment by AndrewBelt** [comment]
Brand is incorrectly set to "VCV". Please release a new update which fixes this.

**Comment by Edge-Modules** [comment]
Sorry for that :/ 

I ve change the brand to 'Edge'.
Latest commit :
[ 3df4023](https://github.com/Edge-Modules/Edge/commit/3df40239f84253d8142b6bdbb2c071089564cd26)

Thank you.
