### ISSUE TITLE
UnforgettableLuncheon 

### ISSUE THREAD

**Issue by johnnymurf** [VCVRack/library#541]
Howdy folks new plugin I'd like to add to VCV, first time doing this so sorry if I've missed anything.

{
    "name": "UnforgettableLuncheon",
    "author": "JohnnyMurf",
    "license": "CreativeCommons",
    "pluginUrl": "https://github.com/johnnymurf/Unforgettable-Luncheon",
    "authorUrl": "https://github.com/johnnymurf/Unforgettable-Luncheon",
    "authorEmail": "",
    "manualUrl": "hhttps://github.com/johnnymurf/Unforgettable-Luncheon/blob/master/README.md",
    "sourceUrl": "https://github.com/johnnymurf/Unforgettable-Luncheon/tree/master/src",
    "latestVersion": "0.6.2",
    "status": "available"
  }

**Comment by cschol** [comment]
Thank you for submitting your plugin. 

One comment: can you please remove the `plugin.so` from the repository? Please follow [these](https://help.github.com/en/articles/removing-sensitive-data-from-a-repository) instructions to **permanently** remove the file from the history. Just `git rm` will not be enough. Thank you!

**Comment by johnnymurf** [comment]
Followed the instructions so I think I've done that. Out of curiosity why is that necessary?

**Comment by cschol** [comment]
In general, it is bad practice to commit binary outputs of the build process to the source code repository. git makes that even worse by storing copies of each revision in the source control system. The result is a growing source code repository size. The build server needs to download a copy of the repository for every build and large repositories are using unnecessary bandwidth.

Thank you for removing the file. Your plugin has now been integrated. When Andrew updates the builds, your plugin will be available via the plugin manager for all supported platforms. Comment in **this** issue when a new version is available and we will reopen it to process the new version. Thank you for submitting your plugin.

**Comment by AndrewBelt** [comment]
Build updated

**Comment by johnnymurf** [comment]
Update:

commit 960ab790961bba37039111b95f5a976d9d630848

**Comment by cschol** [comment]
The version was updated to `0.6.21`. Is that intentional? I would have expected a `0.6.3`.

**Comment by johnnymurf** [comment]
whoops, fixed, thanks

commit 790dfbdc3ac4ad95b1c7d9f41466340386ec50ba

**Comment by johnnymurf** [comment]
Sorry forgot a merge.
Correct commit:
commit d05f5a29cd8291738c6de44899f9c59f243e5ae8

**Comment by AndrewBelt** [comment]
Updated build
