### ISSUE TITLE
Sculpt-O-Sound

### ISSUE THREAD

**Issue by josbouten** [VCVRack/library#542]
plugin name: Vocode-O-Matic
slug name: Sculpt-O-Sound
version: 0.6.04
repository: https://github.com/josbouten/Sculpt-O-Sound
email address: josbouten@gmail.com
commit hash: 66d78a4..387e01a

This is an update with bug fixes and some added functionality.

**Comment by cschol** [comment]
Thank you for the update. Please reuse the original issue for reporting new versions in the future. We will reopen it.
