### ISSUE TITLE
8Mode

### ISSUE THREAD

**Issue by 8Mode** [VCVRack/library#546]
Hello! - New plugin for release review:

Slug: 8Mode
Ver: 0.6.1
Commit: abbaa86f866e91ee6adefbce1e653b42f176d068

Thank you!

{
  "name": "8Mode",
  "author": "Matt Dwyer, 8Mode",
  "license": "BSD-3-Clause",
  "pluginUrl": "https://www.8mode.com/vcv-modules",
  "authorUrl": "https://www.8mode.com",
  "authorEmail": "matt@8mode.com",
  "manualUrl": "https://github.com/8Mode/8Mode-VCV_Modules/blob/master/README.md",
  "sourceUrl": "https://github.com/8Mode/8Mode-VCV_Modules",
  "donateUrl": "https://www.paypal.me/8ModeLLC",
  "latestVersion": "0.6.1",
  "status": "available"
}

**Comment by cschol** [comment]
Your plugin has been added to the repository. Next time Andrew updates the builds your plugin will be made available via the plugin manager for all supported platforms. Please let us know in **this issue** when a new version of the plugin is available. We will reopen the issue then. Thank you for providing your plugin to the VCV Rack community!

**Comment by AndrewBelt** [comment]
Updated build.

**Comment by 8Mode** [comment]
Upgraded 8Mode plugins to work with VCVRack 1.0

4d633d4ff2059aad82e4a48c3425bcae000f242c

Thank you

**Comment by cschol** [comment]
Invalid URL in `plugin.json`: https://github.com/8Mode/8Mode-VCV_Modules/issues/6

**Comment by 8Mode** [comment]
Removed URLs. Thank you.

1343400426ff41f5d767b420351520435a8dcc7a

**Comment by msdlogic** [comment]
v2
fe5a642ee0a455e882e105f422cf85f7e83fd31f
2.0.0

**Comment by 8Mode** [comment]
v2
fe5a642ee0a455e882e105f422cf85f7e83fd31f
2.0.0
