### ISSUE TITLE
ExpertSleepers-Encoders

### ISSUE THREAD

**Issue by expertsleepers** [VCVRack/library#547]
Hello! I'd like to add a plug-in to Rack if I may.

{
  "name": "Encoders",
  "author": "Expert Sleepers",
  "license": "MIT",
  "authorUrl": "http://expert-sleepers.co.uk",
  "authorEmail": "os@expert-sleepers.co.uk",
  "sourceUrl": "https://github.com/expertsleepersltd/externals/tree/master/vcvrack",
  "latestVersion": "0.6.0",
  "status": "available"
}

Thanks!

**Comment by AndrewBelt** [comment]
In order to fit into my automated build system, could the source be split into its own repo with the plugin at the repo's root?

**Comment by expertsleepers** [comment]
Sure. I don't use git more than once or twice a year so bear with me.

**Comment by expertsleepers** [comment]
OK, now at https://github.com/expertsleepersltd/vcvrack-encoders

**Comment by AndrewBelt** [comment]
Added manifest and updated build. Comment on this issue to request updates to the source or information.

**Comment by expertsleepers** [comment]
Please could you add a website/user manual link?

http://expert-sleepers.co.uk/vcvrack_encoders.html

Thanks.

**Comment by expertsleepers** [comment]
Also please update to 0.6.1.
https://github.com/expertsleepersltd/vcvrack-encoders/tree/0.6.1
Thanks.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by expertsleepers** [comment]
This plug-in is updated for Rack v1 now.
Thanks.

**Comment by expertsleepers** [comment]
Code updated to 1.1.0. Please could you update the release? Thanks.

**Comment by expertsleepers** [comment]
This plug-in has been updated for Rack v2. Please update. Thanks.

**Comment by expertsleepers** [comment]
This plug-in is updated to v2.1.0. Please grab the changes. Thanks.
