### ISSUE TITLE
Starling_Via

### ISSUE THREAD

**Issue by liquidcitymotors** [VCVRack/library#548]
Hi,

I would like to add our plugins to the library. If any changes need to be made, just let me know.

Thanks!
```
{
  "name": "Via",
  "author": "Starling",
  "license": "MIT",
  "pluginUrl": "https://starling.space/via/rack",
  "authorUrl": "https://starling.space",
  "authorEmail": "admin@starling.space",
  "manualUrl": "https://starling.space/via/rack#manual",
  "sourceUrl": "https://github.com/starlingcode/Via-for-Rack",
  "donateUrl": "https://paypal.me/ssttaarrlliinngg"
  "latestVersion": "0.6.0",
  "status": "available"
}
```

**Comment by cschol** [comment]
Hey @liquidcitymotors, in your submodule `Via` you have an Eclipse settings folder committed (`.settings` in the project root) that is **135 MB** on my filesystem. Was that committed intentionally? This obviously significantly increases the overall cloned repo size for the build system.

**Comment by liquidcitymotors** [comment]
Yikes, I see why that is a big issue. It doesn't need to be like that. I will update the thread when I have a cleaner repo structure. Thanks for your help!

**Comment by liquidcitymotors** [comment]
Hi! 

I think we are in much better shape with the latest commit, 452bf55af2026f9ed91745bf714c9dfb825227e1

I was able to find a few minor bugs in the process :) 

Let me know if anything else needs to be done!

**Comment by AndrewBelt** [comment]
Updated build

**Comment by liquidcitymotors** [comment]
Hi, I have made a few minor bug fixes would like to request an update to the 0.6.1 version at:
f408a0ac66b0bae75c247baece5bfa55709c6943

Thanks!

**Comment by AndrewBelt** [comment]
Updated build

**Comment by liquidcitymotors** [comment]
Hello, we would like to request an update to version 0.6.2 which can be found at:

680a23fe2869ce08239807c1f52d5643c15ba20a 

Thanks!

**Comment by AndrewBelt** [comment]
Updated build

**Comment by liquidcitymotors** [comment]
Hello!

We now have version 1.0.0 ready, the commit hash is:
11d7638d9b92a51460e5308dde01cd95a927f2bd

Let me know if anything problems arise; lots of updates. Thanks!

**Comment by liquidcitymotors** [comment]
Sorry for the last minute update; a small issue caught my eye as I was checking over everything. If possible, I would like to use commit:

54428ab624fdc7e4165d9fc4e71113f015834ae2

as the reference for v1.0.0. Thanks again.

**Comment by liquidcitymotors** [comment]
Hello,

Version 1.0.1 is now ready on 1058b0ce6ac5a6d36fb1d58b4f3fac0d390ab2cf.

Thanks!

**Comment by liquidcitymotors** [comment]
Hey folks,

2.0.0 is ready on 44e0cef36719736d5f702f81664bd6a5ac5cddd4

**Comment by cschol** [comment]
Build failure: https://github.com/starlingcode/Via-for-Rack/issues/36

**Comment by liquidcitymotors** [comment]
@cschol could we give 7ceab8f69b5e95c41d0859b64857686fc96915fc a try?

**Comment by liquidcitymotors** [comment]
2.0.1 is ready on d96fbc6987f34d34ee5751c443b14d51bec06bf2
