### ISSUE TITLE
catromodulo

### ISSUE THREAD

**Issue by catronomix** [VCVRack/library#549]
My first batch of modules yay!
Everything is ready except I'm still awaiting a mac and linux build, but I'll leave this here already to be prepared :)

```
{
  "slug": "catromodulo",
  "name": "Catro Modulo",
  "author": "catronomix",
  "license": "BSD 3-clause",
  "latestversion": "0.6.4",
  "manual": "https://github.com/catronomix/catro-modulo/blob/master/CM-manual-v0.6.4.pdf",
  "source": "https://github.com/catronomix/catro-modulo.git"
  "pluginUrl": "https://github.com/catronomix/catro-modulo/",
}
```

**Comment by catronomix** [comment]
The Linux and Mac builds have been added to the release.
commit hash: d708a56cdc533616bcd8244ab0510cc0b87e6948

**Comment by cschol** [comment]
Your plugin has been integrated in the library repository and builds for all supported platforms will be provided in the Plugin Manager with the next build update. Please let us know in **this** issue when a new version of the plugin is available. We will reopen it. Thank you for providing your plugin to the VCV Rack Community!

**Comment by catronomix** [comment]
Awesome, thank you! Updates will be coming, already working on some improvements and more modules ^_^

**Comment by AndrewBelt** [comment]
Updated build

**Comment by catronomix** [comment]
Hi, I released an update with bug fixes and an extra module

Version: 0.6.5
Binaries: https://github.com/catronomix/catro-modulo/releases/tag/0.6.5

Commit: 
a4a0b1deec254425d814bb899a4cda2f23cadde0

Updated manual: 
https://github.com/catronomix/catro-modulo/blob/master/CM%20manual%20v0.6.5.pdf

**Comment by AndrewBelt** [comment]
Updated build

**Comment by catronomix** [comment]
Updated to version 0.6.6. with 4 new modules.

release url: https://github.com/catronomix/catro-modulo/releases/tag/0.6.6
commit: 403cfe8ea6f2da4e3f4087b8228dd67434f4688d

I don't have builds for linux and mac as for the love of god I can't get Travis to upload to my github :/
Manual will be updated asap.

**Comment by cschol** [comment]
With the upcoming release of Rack 1.0, all plugin updates for 0.6 have been suspended. 

I would recommend focusing on a port of the plugin for 1.0 instead.
See the migration guide for details: https://vcvrack.com/manual/Migrate1.html

Let us know in this issue when an updated version for 1.0 is available.

**Comment by catronomix** [comment]
I am focussing on that, see the 1.0.0 branch ;)
But as long as veeseevst is not gonna be ported to v1, and there is no official v1 vst coming out, this is the only way to run my plugins inside veeseevst, which is essential to my workflow.

**Comment by catronomix** [comment]
Version 1.0.0 is ready for public use.
https://github.com/catronomix/catro-modulo/releases/tag/1.0.0
879c62f472bf199b7d2bba46b52a19d236d77679

**Comment by catronomix** [comment]
Ow yeah there's still no mac and linux build sorry, I'll ask around if anyone can compile those.

**Comment by AndrewBelt** [comment]
We make builds of all open-source plugins, no need to make builds yourself.

**Comment by catronomix** [comment]
v1.0.1 - Critical bug fixes (was crashing rack sometimes when loading patches)

https://github.com/catronomix/catro-modulo/releases/tag/1.0.1
commit: 4611e9ab164adcccab7d83a088f6762cf2190bdf

**Comment by catronomix** [comment]
If I have a very small bugfix update, should I still increment the version or keep it the same?

**Comment by cschol** [comment]
Once the plugin version is built, the version must be incremented when making any changes.

**Comment by catronomix** [comment]
Ok In that case: v1.0.2, more bugfixes and corrected use of deprecated functions :)

https://github.com/catronomix/catro-modulo/releases/tag/1.0.2
commit: ccb32c60575e883f4eae6461569b843315912789

**Comment by catronomix** [comment]
There is now a complete manual/tutorial.
Link: https://youtu.be/v8RQwWqrJWI

**Comment by catronomix** [comment]
finally another update: v1.0.3
https://github.com/catronomix/catro-modulo/releases/tag/1.0.3
commit: 0a3fcccc3de0c5d21a200975563a31e5c0d69f63
No manual, current manual outdated.

**Comment by catronomix** [comment]
2.0.0 update:
https://github.com/catronomix/catro-modulo/commit/80422acf5a0cf5d4e8f14298e7f41ff8fab39543
