### ISSUE TITLE
Milkrack

### ISSUE THREAD

**Issue by korfuri** [VCVRack/library#550]
Hi, I'd like to release my plugin Milkrack to the library.

Name: Milkrack
Version: 0.6.0
Release hash: 0a6ba85c3c97dbb0894beeb0dd9b93e85fa91ed4 aka tag 0.6.0 (prebuilt for all platforms by Travis-CI here: https://github.com/korfuri/Milkrack/releases/tag/0.6.0)

```
{
  "name": "Milkrack",
  "author": "korfuri",
  "license": "LGPL",
  "pluginUrl": "https://github.com/korfuri/Milkrack",
  "authorUrl": "https://github.com/korfuri",
  "authorEmail": "korfuri@gmail.com",
  "manualUrl": "https://github.com/korfuri/Milkrack",
  "sourceUrl": "https://github.com/korfuri/Milkrack",
  "latestVersion": "0.6.0",
  "status": "available"
}
```

Compatibility notes: this assumes that OpenGL 3.3+ is installed on the system (Rack only assumes 2.0+). In case OpenGL is not recent enough, the rendering will simply be bypassed to a no-op, and won't crash Rack. All OpenGL rendering is done in a context separate from Rack's gWindow. On Linux/Windows the "embedded" version of the module uses context sharing to send its completed texture to gWindow's context, on OSX this is not possible so that module does not render anything.

Performance notes: the rendering itself is done on the GPU (unless you don't have a GPU, in which case this will literally eat all your CPU) and managing the OpenGL stuff is done in a separate thread, so this will not block the UI or audio threads.

Thanks!

**Comment by cschol** [comment]
@korfuri This plugin does not build for me out of the box on Ubuntu 18.04:

```
checking for glm/glm.hpp... no
configure: error: libglm is required.
Makefile:47: recipe for target 'src/deps/projectm/src/libprojectM/.libs/libprojectM.a' failed
make: *** [src/deps/projectm/src/libprojectM/.libs/libprojectM.a] Error 1
```

You have to ensure that the plugins builds after running the following commands:

```
git submodule update --init --recursive
make dep
make
```

This should be working on **all supported platforms** (Linux, Mac, Windows). It is not acceptable if other libraries (e.g. `libglm`) have to be installed via a package manager. The plugin should supply all of its own dependencies.

Also, @AndrewBelt can you take a look at the repo size after cloning dependencies and advise on the size? The total size is 259MB right now. It looks like there are library binaries included in the repo (~25MB).

**Comment by AndrewBelt** [comment]
Yes, these two problems (dependencies and repo size) need to be fixed to be accepted to the Plugin Manager.

**Comment by korfuri** [comment]
I don't think I can fix both: the repo size is due to vendoring 3rd party deps. projectM is the main big one, it weighs a good 100MB at least when you clone it, partly due to embedded assets in there (30MB of "presets" as they call them, some of which I include in the final dist). The prebuilt binaries are also projectM, as building it on Windows requires a lot of ad-hoc patching at the moment.

If there's a size limit, what should I aim for?

I'll work on the glm dep asap.

**Comment by AndrewBelt** [comment]
One option is to email contact@vcvrack.com and ask information about submitting binaries yourself. In this case, you will have to assume liability of malware, so VCV requires that a government photo ID is on file. This is also the case when including `.a` binaries in a repo such as this.

**Comment by korfuri** [comment]
I think it's easier to let projectM work on their windows build (they've made great progress recently) and to wait until @dizzysound can provide his build recipe, so we have a chance to build everything from scratch.

I'm going to close this and I'll ping back when we have a build-fully-from-source on Windows as well.

The size limit may still be an issue though: vendoring projectM takes a whole bunch of space. Do I need to worry about that? I can try various hacks (instead of a git submodule, I could like, vendor a tgz and decompress during the build process) but I'd like to keep it clean if I can, and just vendor via submodules.

**Comment by korfuri** [comment]
Additional question: is it acceptable to depend on packages that are listed at https://vcvrack.com/manual/Building.html for building? I'm looking in particular at `libglu1-mesa-dev` on Linux.
