### ISSUE TITLE
sb-StochKit

### ISSUE THREAD

**Issue by smbddha** [VCVRack/library#551]
Hello !

I would like to have my plugin listed on the VCV Plugin Manager.

**name**: sb-StochKit,
**version**: 0.6.2
**source**: https://github.com/smbddha/sb-StochKit
**last commit hash**: dbe9bbb18006e891c575db0b019d854b6b6c9c7e

Thanks!

```
{
  "name": "sb-StochKit",
  "author": "Samuel Laing",
  "license": "CC0 1.0 Universal",
  "pluginUrl": "https://github.com/smbddha/sb-StochKit",
  "authorUrl": "https://github.com/smbddha",
  "manualUrl": "https://github.com/smbddha/sb-StochKit/blob/master/README.md",
  "sourceUrl": "https://github.com/smbddha/sb-StochKit",
  "latestVersion": "0.6.2"
}
```

**Comment by cschol** [comment]
Thank you for submitting your plugin. It has been integrated to the repository and will be included in the next build update. Binaries will be made available in the Plugin Manager for all supported platforms. Please use **this** issue for reporting new versions of your plugin. We will reopen it.

**Comment by AndrewBelt** [comment]
Updated build

**Comment by smbddha** [comment]
sb-StochKit has been updated:
**version** 1.0.0
**source**: https://github.com/smbddha/sb-StochKit
**last commit hash**: e7f9e2487733f4fc850c12bd63023dc0e93f0e1b

thanks!

**Comment by cschol** [comment]
`plugin.json` issues: https://github.com/smbddha/sb-StochKit/issues/3

**Comment by smbddha** [comment]
whoops sorry... fixed that. new commit hash: 767383b9eda7b61ea5c8187296c676dd4fcf94fa
