### ISSUE TITLE
LOGinstruments

### ISSUE THREAD

**Issue by LOGUNIVPM** [VCVRack/library#554]
Please modify the JSON manifest of LOGinstruments to:

{
  "name": "LOGinstruments",
  "author": "leopard86 (Leonardo Gabrielli)",
  "license": "BSD-3-Clause",
  "manualUrl": "https://github.com/LOGUNIVPM/LOGinstruments/blob/master/README.md",
  "sourceUrl": "https://github.com/LOGUNIVPM/LOGinstruments",
  "latestVersion": "0.6.0",
  "status": "available",
  "pluginUrl": "https://github.com/LOGUNIVPM/LOGinstruments/blob/master/README.md"
}

The paths have changed. Thank you

**Comment by LOGUNIVPM** [comment]
I just updated my plugins to v1 in my git. The has of the last commit is c5159469

**Comment by cschol** [comment]
Compile failure on all platforms: https://github.com/LOGUNIVPM/LOGinstruments/issues/13

**Comment by LOGUNIVPM** [comment]
Needed to delete old files from the repo. Now it should work properly. Hash: 07e1cd3e

**Comment by cschol** [comment]
`plugin.json` issues: https://github.com/LOGUNIVPM/LOGinstruments/issues/14

**Comment by LOGUNIVPM** [comment]
I updated the info on the JSON. See commit 25822aec

**Comment by cschol** [comment]
`plugin.json` issues: https://github.com/LOGUNIVPM/LOGinstruments/issues/15

**Comment by LOGUNIVPM** [comment]
@cschol thank you. I have taken a look at my JSON and validated using an online tool. The JSON is syntactically correct. I don't see where's the issue. The tags are valid. Is the JSON script you are using a bit too strict? The only potential issue I see is the lack of linefeed after "Noise", see below.
Could you check this so we don't keep on iterating on these small issues?

`    {
      "slug": "Velvet",
      "name": "Velvet",
      "description": "Velvet Noise generator",
      "tags": [
        "Noise","Random"
      ]
    }`

**Comment by cschol** [comment]
I apologize. I was looking at an older version and this was updated on the 26th. All good.

**Comment by LOGUNIVPM** [comment]
Reopening for a slight update. See commit  6c0bd7fb 
Thanks

**Comment by LOGUNIVPM** [comment]
Reopening for the update to v2:

Version: 2.0.1

Source: https://github.com/LOGUNIVPM/LOGinstruments

**Comment by LOGUNIVPM** [comment]
Updated plugin v2.0.2
Commit a2ebaa0 (bug fix)
https://github.com/LOGUNIVPM/LOGinstruments

**Comment by LOGUNIVPM** [comment]
Fixed loadFont for VST version.
Commit: 5488a20a
https://github.com/LOGUNIVPM/LOGinstruments

**Comment by LOGUNIVPM** [comment]
Reopening for update to v 2.0.4
Commit: [1fc62fa](https://github.com/LOGUNIVPM/LOGinstruments/commit/1fc62fafe66bd622432db895a09ef1e3afc4531c)
