### ISSUE TITLE
Library repo maintenance

### ISSUE THREAD

**Issue by cschol** [VCVRack/library#555]
@AndrewBelt 

I created a project board for library maintenance (right now for v0.6, later for v1.0):

https://github.com/VCVRack/library/projects/2

If an existing issue assigned to this project gets reopened, it gets automatically assigned to the "Plugin integration in repo" column. Once I integrate it, I will move it to the "Plugin build update" column. When you update the build and close the issue, it will automatically move it to the "Plugin available for v0.6" column.

Only issues labelled "plugin" are assigned to this board.

Issues for new plugins should be assigned to the "v0.6 library maintenance" project. Then they will automatically assigned to the "Plugin integration in repo" column.

This should make it more obvious for the Library team, which plugins need updates. I sometimes miss them in the normal issue list and they sit there for a while.

**Comment by AndrewBelt** [comment]
Oh yeah, I forgot about project hooks/triggers. Those will make things a lot easier.

**Comment by cschol** [comment]
Proposal to remove the following plugins from the library (`master` branch):

- Autodafe Blank Panels (I have confirmed with the author that they are obsolete)
- dekstop (The plugin was actually never available in the plugin manager for any version of Rack)

**Comment by AndrewBelt** [comment]
Removing old plugins is fine with me.

**Comment by cschol** [comment]
I am trying to get to portable review capabilities with my Mac. 

Two issues I found on a Mac (non-case sensitive file system...):

- `manifests` contains `Mental.json` (valid) and `mental.json` (old, obsolete). I would like to remove `mental.json`.
- `repos/Quadraphonics` repo has two folders with the same name and different capitalization. Since it has not been updated, can we remove it from `repos`? We can readd it once it has been ported to `v1`. I filed an issue with the plugin author, but it is unlikely to be fixed anytime soon.

**Comment by AndrewBelt** [comment]
- Yes, remove `mental.json`.
- Sure. We don't have to strictly follow the rule of "every open-source build needs a submodule in `repos/`.

**Comment by cschol** [comment]
Cool. Thanks. I will make those updates.

**Comment by cschol** [comment]
I did a fresh clone of the library repo and found a few issues:

Repositories no longer available on GitHub:
- RacketScience
- luckyxxl
- TheXOR

Repositories with invalid URL in library, but still available on GitHub:
- EH_modules

Repositories with invalid **dependency** URLs:
- RJModules: invalid reference to soundpipe repo

Recommended action:
- EH_modules should be updated to new URL
- All other repositories should be removed from library repo with notification of user in library repo issue so they can resubmit if desired

**Comment by AndrewBelt** [comment]
I think broken git URLs should be removed from this repo, and if they request an update in the future, we can simply add the new URL.

**Comment by cschol** [comment]
Sounds good. I remove them and test that the check out works on my laptop.
