### ISSUE TITLE
feature request Jack CV output

### ISSUE THREAD

**Issue by infamedavid** [VCVRack/library#556]
I m thinking in a module that actually is very similar to the 8 out (perhaps arranged horizontally like a mixer) that the main feature  of this module  is a offset-multiply knob (or slider)

the single knob will commute the functions of the both knobs of the  befaco Attenuverter depending if a signal is connected or not to the channel output

* if a cable is connected to the output channel the knob will multiply by a value between -1 and 1 

* if any is connected to the channel the knob will offset the value (addition )

what is useful  this module for?

this module allow send principally CV out to the vcv rack since  jack allow send and use jack CV (some software compatible with jack cv are Carla that also allow convert cv to midi ,  NON mixer, Ingen  and even another  instance of vcv rack ,  maybe jack through the network and hardware -I have not tried this- among others software and uses)

also allow handle the volume of the audio output.

the actual SKjack can do it beside a befaco atenueverter

**Comment by AndrewBelt** [comment]
The repo is for maintaining the database of Rack modules. It would be better to post this in the Patches and Plugins category of the forum, for example.
