### ISSUE TITLE
CYC

### ISSUE THREAD

**Issue by mrletourneau** [VCVRack/library#566]
Hi, I'd like to submit to a plugin. Here's the repo: https://github.com/mrletourneau/strong_kar

**Comment by cschol** [comment]
Thank you for submitting your plugin. 

Please provide some more information:
- Does it compile against Rack v1.0.0? It needs to as the 0.6.x line is being sunsetted. 
- Please provide a SHA to check out.

**Comment by mrletourneau** [comment]
The commit is: https://github.com/mrletourneau/strong_kar/commit/f0fe2d2eaa9f56f409e28af0949538a4f00e4f68

And this is for Rack 1.0.
