### ISSUE TITLE
MosquitoLabs

### ISSUE THREAD

**Issue by rmosquito** [VCVRack/library#569]
Hello!

I recently ported my modules to 1.0, and community testers seemed okay with them.

Source is available at:
https://github.com/rmosquito/vcv-mosquito/

Thanks!
RM

**Comment by cschol** [comment]
Thank you for submitting your plugin. 

It has been integrated in the library repository and is waiting for the next build update. Once that happens it will be available for all supported platforms.

When a new version of your plugin is available, please use **this** issue to notify us. We will reopen it.

**Comment by rmosquito** [comment]
Hi VCVers.

My version is now 1.1.0.

Commit hash:
41df6a3a0fb23aeef39e82fdfd51e6b8b2162cb8

Thank you!
-RM

**Comment by rmosquito** [comment]
Hello priests of the VCV.  I'm sorry to do this again... someone opened an issue.  My version is now 1.1.1.

Commit hash:
15c36b4618668905cfd4e05ca3de0ff831c1c851

Thank you again!
- RM
