### ISSUE TITLE
AmalgamatedHarmonics: How is the windows version being built?

### ISSUE THREAD

**Issue by jhoar** [VCVRack/library#570]
I see a strange discrepancy in the function of the Arp3.1 module between the Library version and a version built locally

A version built locally behaves as normal, note the six steps on Scope.

![Local](https://user-images.githubusercontent.com/13257489/60089271-67ff5a80-9740-11e9-907b-2379d1b2c081.jpg)

The library version has seven steps, with the first step corresponding to 0V

![Library](https://user-images.githubusercontent.com/13257489/60089186-3d150680-9740-11e9-8b5a-6150e1972991.jpg)

It's quite probably that there's a bug in the code somewhere. Maybe it's appearing only through the way that the module is built (cross-compilation?). I can't reproduce it at the moment so I'd at least like to see if I can reproduce the steps from Github to Library and see if there something obvious there.

**Comment by AndrewBelt** [comment]
#384
