### ISSUE TITLE
RJModules 1.0.0!

### ISSUE THREAD

**Issue by Miserlou** [VCVRack/library#571]
My migration to 1.0.0+ is complete!

URL: https://github.com/Miserlou/RJModules/
Commit: 4120b4228ce4f5159c1aed24e4c5901f6d1012ce

The major new addition, besides the migration, is '[Acid](https://github.com/Miserlou/RJModules/#acid)', my take on the TB-303!

**Comment by Miserlou** [comment]
I'd also really really love it if somebody could take a quick look at: https://github.com/Miserlou/RJModules/issues/38 in case anything jumps out at them..

**Comment by cschol** [comment]
Please reuse #507 for announcements of 1.0.0 versions.
