### ISSUE TITLE
ChortlingHamsterModules

### ISSUE THREAD

**Issue by ghost** [VCVRack/library#572]
Here is my source code: https://github.com/chortlinghamster/modules

There's only one module at the moment, and that's a ridiculously simple sample and hold module. I understand if you reject it, as there's probably too many modules with S&H functions already. :)

Thanks.

**Comment by cschol** [comment]
`plugin.json` issues: https://github.com/chortlinghamster/modules/issues/3

**Comment by immortaljellyfishy** [comment]
OK. I've pushed an update to pluginUrl in the JSON manifest. Thanks.

**Comment by ghost** [comment]
Remove this plugin from the library.

**Comment by AndrewBelt** [comment]
Any reason why? We can honor requests from the developer as a courtesy, but the BSD license states that we are allowed to distribute it.

**Comment by ghost** [comment]
Please add the new version 1.1.0 to the Library.

The commit hash is https://github.com/chortlinghamster/modules/commit/fe494f6c21d549eda9addf5a564413bbc6880cea.

Thanks you.

**Comment by ghost** [comment]
Please add version 1.1.1 to the Library.

The commit hash is https://github.com/chortlinghamster/modules/commit/374fe749c2f398a21b67d846f88210219266aa01.

Thanks.

**Comment by ghost** [comment]
Please add version 1.1.2 to the library.

The commit hash is https://github.com/chortlinghamster/modules/commit/9f6a131bf724cf62b8731144fd36b8faca45c290

Thanks!

**Comment by alanholding** [comment]
Please add version 1.1.2.1 to the library.

The commit hash is https://github.com/chortlinghamster/modules/commit/1448a841a4f02bf77a4921380243a9a121f324de

This is a minor update to change the plugin's licensing to GPLv3.

Thank you and I hope you're well.

**Comment by alanholding** [comment]
Please add version 1.1.2.2 to the library.

The commit hash is https://github.com/chortlinghamster/modules/commit/26f94e247ef9718615e8c9c9eddae51fb2382c4b

This is a minor update to roll back code in one module so that it uses the standard VCV lights code instead of custom lights code.

Thank you and I hope you're well.

**Comment by alanholding** [comment]
Please add my plugin to the v2 library.

The commit hash is ed72dd18180b6bed4dcc9b14f947d20299123ae6.

https://github.com/chortlinghamster/modules/commit/ed72dd18180b6bed4dcc9b14f947d20299123ae6

Thank you.
