### ISSUE TITLE
SLM

### ISSUE THREAD

**Issue by salvolm84** [VCVRack/library#573]
Dears VCV Library maintainers
I am starting my plugin development and I'd like to start by sharing my first module:
https://github.com/salvolm84/SLM-vcv-rack

Tested on Windows, unfortunately at the moment I can't build for Mac nor Linux.

Cheers!

**Comment by cschol** [comment]
`plugin.json` issues: https://github.com/salvolm84/SLM-vcv-rack/issues/2

**Comment by salvolm84** [comment]
fixed in last commit

**Comment by salvolm84** [comment]
Dears

I have a new update
1.1.0 (2019-07-31)
New Module: The Tailor (waveforms morphing tool)
Mux Freak: New Panel, minor code cleanup

Version: 1.1.0
Commit: d3d69e01ec22f221e82156ada51fb83e5fc3c5a8
Branch: master

Thanks,
Salvo.
