### ISSUE TITLE
JACK-MIDI no longer available?

### ISSUE THREAD

**Issue by polyzium** [VCVRack/library#574]
I'd prefer JACK-MIDI over ALSA-MIDI because of better timing on stock Linux kernels. Since 0.6 JACK-MIDI support is no longer available for some reason, and it's still not present in 1.1.1.
![image](https://user-images.githubusercontent.com/22579935/60655309-354b1580-9e56-11e9-9a24-287b58be5b6d.png)
Using the official build from https://vcvrack.com/Rack.html

**Comment by cschol** [comment]
Jack is not supported by the official build. It can be enabled for audio via the third party plugin `SkJack`.

For Jack MIDI support you can file a feature request at https://github.com/VCVRack/Rack/issues.
